### ISSUE TITLE
[cli]  chain get_txn  Internal error when txn is discard.

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#1047]
chain get_txn hash

Server returned rpc error Internal error: Internal error

2020-08-05T17:24:53.440631+08:00 ERROR - rpc return internal_error for: get transaction_info ids error.

**Comment by fanngyuan** [comment]
好像已经修复？

**Comment by jolestar** [comment]
这个一方面是 error code 的问题，另外一方面是失败的交易信息查询的问题。错误码的问题需要和 #1080 一起确认下。

**Comment by lerencao** [comment]
event filer from to 限制。
