### ISSUE TITLE
[testing] Test helper crate and test framework

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#1073]
抽取出一个测试帮助的模块以及简单测试框架，方便测试 Chain，State, Network 以及 Node

1. 初始化 Node 的时候可以指定模块，比如是否初始化网络，是否启动 Miner （这个可以和 Node 启动的重构一起考虑）。
2. 方便模拟账号以及读取状态 （这个可以和 Account 模块的改进一起考虑）
3. 方便监听事件，链或者合约中的事件，通过事件驱动测试，避免长时间的等待。

**Comment by fanngyuan** [comment]
已经有了？

**Comment by jolestar** [comment]
这个基本已经实现，虽然还不是一个框架，但也够用。等有机会再重构，这个可以先关闭了。
