### ISSUE TITLE
Introduce a framework to cluster test

### ISSUE THREAD

**Issue by fikgol** [starcoinorg/starcoin#1095]
1. Use k8s to manage cluster
2. Use Chaos Mesh for supporting basic Chaos Operator

**Comment by zhouqiang-cl** [comment]
> 1. Use k8s to manage cluster
> 2. Use Chaos Mesh for supporting basic Chaos Operator

Thank you for your interest in Chaos Mesh. If you have any problem in using Chaos Mesh, we are very pleasure if we can help

**Comment by zhouqiang-cl** [comment]
Now we have created a github action, you can directly use Chaos Mesh in PRs. https://github.com/chaos-mesh/chaos-mesh-action /cc @fikgol @jolestar
