### ISSUE TITLE
Chain connect block blocking on a future

### ISSUE THREAD

**Issue by lerencao** [starcoinorg/starcoin#1130]
Network remote state reader 有一个 future 的 block 调用. see https://github.com/starcoinorg/starcoin/blob/b862c5cce6c2071c25af6ea59da6b612e5a04c11/network-rpc/api/src/remote_chain_state.rs#L61

这导致chain 在 block connect 总是会在 get_epoch 上block 一会。
https://github.com/starcoinorg/starcoin/blob/b862c5cce6c2071c25af6ea59da6b612e5a04c11/chain/src/lib.rs#L161

**Comment by lerencao** [comment]
@tiangong3624749 @fikgol 看下这个对block 同步影响大不大。

**Comment by fikgol** [comment]
这里或许后面可以优化为 remote state 在一个独立线程里同步。

**Comment by lerencao** [comment]
> 这里或许后面可以优化为 remote state 在一个独立线程里同步。

感觉我们代码需要变。

**Comment by tiangong3624749** [comment]
> @tiangong3624749 @fikgol 看下这个对block 同步影响大不大。

这块逻辑不是我加的，俊哥看看？

**Comment by fikgol** [comment]
> > @tiangong3624749 @fikgol 看下这个对block 同步影响大不大。
> 
> 这块逻辑不是我加的，俊哥看看？

ConnectBlockWithoutExe 得从网络获取 EpochInfo，逻辑上没问题，实现上看后面怎么优化一下。

**Comment by lerencao** [comment]
<img width="898" alt="图片" src="https://user-images.githubusercontent.com/1456096/90466973-a37b9600-e145-11ea-83ad-adfccf8a6cb0.png">


block_connect 这里，我理解，只要 pivot 在，基本上都会走到 without exe。

而 pivot 只有 sync task 完成了，才会清除掉。

<img width="743" alt="图片" src="https://user-images.githubusercontent.com/1456096/90467150-0f5dfe80-e146-11ea-8535-bb0439f63d0b.png">

不知道理解对不对。

**Comment by fikgol** [comment]
> <img alt="图片" width="898" src="https://user-images.githubusercontent.com/1456096/90466973-a37b9600-e145-11ea-83ad-adfccf8a6cb0.png">
> 
> block_connect 这里，我理解，只要 pivot 在，基本上都会走到 without exe。
> 
> 而 pivot 只有 sync task 完成了，才会清除掉。
> 
> <img alt="图片" width="743" src="https://user-images.githubusercontent.com/1456096/90467150-0f5dfe80-e146-11ea-8535-bb0439f63d0b.png">
> 
> 不知道理解对不对。

我理解也是这样的。

**Comment by lerencao** [comment]
那这是不是会影响 block 同步的速度。

**Comment by fikgol** [comment]
嗯是的，如果是 fast sync 会影响, 如果是full sync 就没有影响了。因为触发调用是在apply_without_execute里。

**Comment by lerencao** [comment]
没理解。

try_connect_without_execute 就是触发 apply_without_execute。

<img width="783" alt="图片" src="https://user-images.githubusercontent.com/1456096/90475506-2575ba00-e15a-11ea-92d6-0a49f873e1f4.png">

<img width="729" alt="图片" src="https://user-images.githubusercontent.com/1456096/90475537-31617c00-e15a-11ea-94c5-ace176d6d921.png">

**Comment by jolestar** [comment]
chain 对 remote state reader 的依赖已经删除。
