### ISSUE TITLE
Starcoin node panicked at Unable to open StarcoinDB

### ISSUE THREAD

**Issue by sanlee42** [starcoinorg/starcoin#1173]
2020-08-24T10:01:41.495373498+00:00 ERROR - panic occurred:
panic occurred:
2020-08-24T10:01:41.495447549+00:00 ERROR - details: panicked at 'Unable to open StarcoinDB: Corruption: Can't access /023232.sst: IO error: No such file or directorywhile stat a file for size: /data/proxima/starcoindb/db/starcoindb/023232.sst: No such file or directory
Sst file size mismatch: /data/proxima/starcoindb/db/starcoindb/023233.sst. Size recorded in manifest 43669, actual size 1348949
Sst file size mismatch: /data/proxima/starcoindb/db/starcoindb/023235.sst. Size recorded in manifest 9897, actual size 1349085
', /starcoin/storage/src/db_storage/mod.rs:21:9
details: panicked at 'Unable to open StarcoinDB: Corruption: Can't access /023232.sst: IO error: No such file or directorywhile stat a file for size: /data/proxima/starcoindb/db/starcoindb/023232.sst: No such file or directory
Sst file size mismatch: /data/proxima/starcoindb/db/starcoindb/023233.sst. Size recorded in manifest 43669, actual size 1348949
Sst file size mismatch: /data/proxima/starcoindb/db/starcoindb/023235.sst. Size recorded in manifest 9897, actual size 1349085
', /starcoin/storage/src/db_storage/mod.rs:21:9
2020-08-24T10:01:41.495794615+00:00 ERROR - backtrace:    0:     0x5583a0cdc347 - backtrace::backtrace::trace::hbebe05fbe8d5bb88
   1:     0x5583a0cc9125 - backtrace::capture::Backtrace::new::h9a18d227733e97d0
   2:     0x55839f729c20 - starcoin_node::crash_handler::handle_panic::h4a1dad2b6e92066a
   3:     0x55839f729b99 - starcoin_node::crash_handler::setup_panic_handler::{{closure}}::h1327e2d1ccf523ed
   4:     0x5583a0d818dc - std::panicking::rust_panic_with_hook::h88a1f16ec8a7bb20
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/panicking.rs:490
   5:     0x5583a0d814bb - rust_begin_unwind
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/panicking.rs:388
   6:     0x5583a0da7151 - core::panicking::panic_fmt::hbddb7fe6f399b81a
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/panicking.rs:101
   7:     0x5583a0da6e13 - core::option::expect_none_failed::h60849c4323f09783
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/option.rs:1272
   8:     0x55839f6c6829 - starcoin_node::node::start::{{closure}}::h71e61de2c0b8ae12
   9:     0x55839f6ba8fb - <core::future::from_generator::GenFuture::poll::h73ad0fa11e8d80a0
  10:     0x55839f741049 - tokio::macros::scoped_tls::ScopedKey<T>::set::h7f48a2ecf3c5a5f9
  11:     0x55839f6b76ec - <core::future::from_generator::GenFuture::poll::h38cdbbcde58b129a
  12:     0x55839f742e03 - tokio::runtime::context::enter::h78e9415a97d5a9e1
  13:     0x55839f74addb - actix_rt::builder::SystemRunner::block_on::h18e8fff64391297b
  14:     0x55839f673f64 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2428a8fdfd6f6026
  15:     0x55839f674068 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h46facced78f71cb6
  16:     0x5583a0d86f9a - <alloc::boxed::Box>::call_once::hcf205bcf9b46c587
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/liballoc/boxed.rs:1076
                           <alloc::boxed::Box>::call_once::h2d53e2246128f5d8
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/liballoc/boxed.rs:1076
                           std::sys::unix::thread::Thread::new::thread_start::h3b6d8a0cd87a87c6
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/sys/unix/thread.rs:87
  17:     0x7f99c24836db - start_thread
  18:     0x7f99c36a9a3f - __clone
  19:                0x0 - <unknown>
backtrace:    0:     0x5583a0cdc347 - backtrace::backtrace::trace::hbebe05fbe8d5bb88
   1:     0x5583a0cc9125 - backtrace::capture::Backtrace::new::h9a18d227733e97d0
   2:     0x55839f729c20 - starcoin_node::crash_handler::handle_panic::h4a1dad2b6e92066a
   3:     0x55839f729b99 - starcoin_node::crash_handler::setup_panic_handler::{{closure}}::h1327e2d1ccf523ed
   4:     0x5583a0d818dc - std::panicking::rust_panic_with_hook::h88a1f16ec8a7bb20
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/panicking.rs:490
   5:     0x5583a0d814bb - rust_begin_unwind
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/panicking.rs:388
   6:     0x5583a0da7151 - core::panicking::panic_fmt::hbddb7fe6f399b81a
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/panicking.rs:101
   7:     0x5583a0da6e13 - core::option::expect_none_failed::h60849c4323f09783
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/option.rs:1272
   8:     0x55839f6c6829 - starcoin_node::node::start::{{closure}}::h71e61de2c0b8ae12
   9:     0x55839f6ba8fb - <core::future::from_generator::GenFuture::poll::h73ad0fa11e8d80a0
  10:     0x55839f741049 - tokio::macros::scoped_tls::ScopedKey<T>::set::h7f48a2ecf3c5a5f9
  11:     0x55839f6b76ec - <core::future::from_generator::GenFuture::poll::h38cdbbcde58b129a
  12:     0x55839f742e03 - tokio::runtime::context::enter::h78e9415a97d5a9e1
  13:     0x55839f74addb - actix_rt::builder::SystemRunner::block_on::h18e8fff64391297b
  14:     0x55839f673f64 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2428a8fdfd6f6026
  15:     0x55839f674068 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h46facced78f71cb6
  16:     0x5583a0d86f9a - <alloc::boxed::Box>::call_once::hcf205bcf9b46c587
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/liballoc/boxed.rs:1076
                           <alloc::boxed::Box>::call_once::h2d53e2246128f5d8
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/liballoc/boxed.rs:1076
                           std::sys::unix::thread::Thread::new::thread_start::h3b6d8a0cd87a87c6
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/sys/unix/thread.rs:87
  17:     0x7f99c24836db - start_thread
  18:     0x7f99c36a9a3f - __clone

**Comment by fikgol** [comment]
when random killed a node, this panic may happen.
