### ISSUE TITLE
[stdlib] Use libra move's compatibility check to replace current compatibility check

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#1188]
But the libra's compatibility check is under the stdlib crate, consider submitting a PR to migrate it to a move-related crate.

https://github.com/libra/libra/pull/5529

**Comment by guangyuz** [comment]
libra's compatibility check includes two part: 1. normalized.rs under vm/src, and 2. compatibility.rs under stdlib. Part 2 is actually just a wrapper for Part 1. So it's ok for me to leave the check in stdlib.

But libra's compatibility check doesn't show more advantage than Starcoin at the moment. So let's keep using the current implementation until there is further improvements.
