### ISSUE TITLE
[stdlib]: Support deposit to a receiver without a sender (in case of mint token to receiver)

### ISSUE THREAD

**Issue by lerencao** [starcoinorg/starcoin#1203]
Currently, to deposit tokens to a payee, we need a payer (to emit send event of payer).
But, in some case, the token is mint from air, so there is no payer, or no send event handle.

I think we need to support this case in Account module.

**Comment by lerencao** [comment]
cc @jolestar @guangyuz

**Comment by jolestar** [comment]
不会有这种场景吧？move 中的任何操作都必须有个 signer，即便是  mint 或者从合约中提款出来，也肯定有发起人。

**Comment by lerencao** [comment]
发起人是发起人，但不是 payer，我们现在是强制限制需要payer，去改payer 的 send payement event。

**Comment by lerencao** [comment]
大家公投一个 mint，我去触发了， 不能说这个钱是从我账户转出去的吧。

**Comment by jolestar** [comment]
那感觉可以改一下 event 里的 payee 字段的名字以及整个 event 的语义，叫做 sender？

**Comment by lerencao** [comment]
> 那感觉可以改一下 event 里的 payee 字段的名字以及整个 event 的语义，叫做 sender？

SendPaymentEvent 的语义其实不好改，你看看。这个 event 本意是我给你转钱，我的账户有一个 send money 的event。

**Comment by lerencao** [comment]
> 不会有这种场景吧？move 中的任何操作都必须有个 signer，即便是 mint 或者从合约中提款出来，也肯定有发起人。

说的是接口，接口不一定需要 signer。既然拿到 token resource 了，应该可以直接deposit 到某人账户吧。这个时候signer 做啥用。
