### ISSUE TITLE
VM run_failure_epilogue with a new Session for avoid unexpected state change

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#1257]
1. 通过一个单元测试模拟这种场景： 执行一个交易被 abort，但链上的状态被修改了（除了扣 gas 费之外的变更）。
2. 通过重构 run_failure_epilogue 修复这个 bug。

**Comment by guangyuz** [comment]
未复现这个 bug。failed_transaction_cleanup()是在新的session中run_epilogue的。
