### ISSUE TITLE
Halley Testnet deploy

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#128]

**Comment by fikgol** [comment]
solution :
1. 用 github action 和 docker 去构建分发 master 分支的 binary。
2. 写脚本或者用 terraform （Not support digitalocean）去做集群管理。

**Comment by jolestar** [comment]
好像 digitalocean 支持 docker-machine @fikgol

**Comment by fikgol** [comment]
> 好像 digitalocean 支持 docker-machine @fikgol

确实支持 https://docs.docker.com/machine/examples/ocean/
