### ISSUE TITLE
chain head is broken

### ISSUE THREAD

**Issue by lerencao** [starcoinorg/starcoin#1442]
<img width="808" alt="image" src="https://user-images.githubusercontent.com/1456096/95807638-3f3c1380-0d3d-11eb-82e2-8cbe93c7d2b7.png">

我提交了一个交易后，
`chain head`  和 chain list_block 的最新区块 不一致。

**Comment by jolestar** [comment]
chain show 已经重命名为 chain info，改变了实现机制，应该没有这个问题了，如果再发现，请重开。
