### ISSUE TITLE
cryptonight is outdated

### ISSUE THREAD

**Issue by z1617** [starcoinorg/starcoin#1494]
1. there are asics available and cpu verification isn't efficient
2. can consult [tromp](https://github.com/tromp/) to develop a cuckoo variant
3. or some randomx variant

**Comment by fikgol** [comment]
The consensus hash algorithm can be decided by the community after a vote, and we support switching through the smart contracts on chain. @z1617

**Comment by z1617** [comment]
@fikgol Thanks for your reply. However an outdated mining algo isn't a good choice for starcoin. There are some better alternatives: such as randomx, progpow.

**Comment by jolestar** [comment]
clean issue for prepare 1.0.
