### ISSUE TITLE
A single node should not have a uncle block

### ISSUE THREAD

**Issue by ssyuan** [starcoinorg/starcoin#1753]
starcoin% chain epoch_info
{
  "ok": {
    "epoch": {
      "block_difficulty_window": 24,
      "block_gas_limit": 150000,
      "block_time_target": 10000,
      "end_block_number": 240,
      "max_uncles_per_block": 2,
      "new_epoch_events": {
        "count": 0,
        "key": "0x090000000000000000000000000000000000000000000001"
      },
      "number": 0,
      "reward_per_block": 1000000000,
      "reward_per_uncle_percent": 10,
      "start_block_number": 0,
      "start_time": 1606973016000,
      "strategy": 3
    },
    "epoch_data": {
      "total_gas": 7223048,
      "total_reward": 197300000000,
      "uncles": 3
    }
  }
}
starcoin% node peers
{
  "ok": []
}

**Comment by tiangong3624749** [comment]
chain unlce list_epoch_uncles_by_number把3个uncle找出来，先确认一下是不是非法uncle？

**Comment by jolestar** [comment]
没有复现，暂时关闭。
