### ISSUE TITLE
[performance] Performance analysis - general

### ISSUE THREAD

**Issue by guangyuz** [starcoinorg/starcoin#1787]
1. data analysis
**Scenario#1:** customized proxima，primary node with tx_factory connected，tps > 20，block gas > 50000
cpu% top modules:
cryptonight 52%
tx_pool::add_txns  30%
others  18% 
![1](https://user-images.githubusercontent.com/13956325/101597395-9efb2600-3a31-11eb-8fce-5fdb4a692543.png)
将 tx_pool::add_txns 放大，其中紫色部分是bytecode_verifier相关代码，占比较大
![2](https://user-images.githubusercontent.com/13956325/101597505-bfc37b80-3a31-11eb-916d-6861f21e00fa.png)
其它 18%放大后：
![3](https://user-images.githubusercontent.com/13956325/101597578-db2e8680-3a31-11eb-8f0b-b061d0472acd.png)

**Scenario#2:** customized proxima， slave node without tx_factory connected，tps > 20，block gas > 50000
![4](https://user-images.githubusercontent.com/13956325/101597701-07e29e00-3a32-11eb-8fc1-e390f89bfc74.png)

**Comment by guangyuz** [comment]
2.Optimization Opportunity
i) in scenario#1, BlockChain::new occupies 4.2% + 2.3%, it's not necessary to new a block chain every time.
ii) in scenario#2, tx_pool::import::verify_transaction() occupies 24%, consider to verify multiple txns in one vm call

**Comment by tiangong3624749** [comment]
#1788
