### ISSUE TITLE
Node exits abnormally: Connection refused (os error 111)

### ISSUE THREAD

**Issue by onemedicine** [starcoinorg/starcoin#1877]
Ubuntu 20.04
starcoinv0.9.3

ERROR：
INFO - Try to connect node by ipc: "/root/.starcoin/proxima/starcoin.ipc"
2020-12-24T09:04:08.181917265+00:00 ERROR - Node exits abnormally: Connection refused (os error 111)

Description：
When the process is directly killed, it cannot be started again because the "starcoin.ipc" file already exists, and manually delete it can be restored.

**Comment by jolestar** [comment]
if the process exit abnormally, the starcoin.ipc file can not bean released, need manual delete it.
