### ISSUE TITLE
Check if gas cost of token_name_of (=4004) is correct

### ISSUE THREAD

**Issue by guangyuz** [starcoinorg/starcoin#1950]

**Comment by guangyuz** [comment]
[unit nanosecond]
native_destroy_empty execution time 1913
native_destroy_empty execution time 2203
native_destroy_empty execution time 1781
native_destroy_empty execution time 1962
native_swap execution time 2270
native_swap execution time 1117
native_swap execution time 2513
native_swap execution time 1093
token_name of execution time 8269 (part1=361, part2=4198, part3=52, part4=3658)
token_name of execution time 7374  (part1=205, part2=5139, part3=52, part4=1978)
token_name of execution time 6497  (part1=260, part2=4053, part3=51, part4=2133)
token_name of execution time 6606  (part1=252, part2=4156, part3=53, part4=2145)
---------------------------------------------------------------------------------------
Part1:
let cost = native_gas(
    context.cost_table(),
    NativeCostIndex::TOKEN_NAME_OF,
    1,
);

Part2:
let type_tag = context.type_to_type_tag(&ty_args[0])?;

Part3:
if let TypeTag::Struct(struct_tag) = type_tag {
    
Part4:
    let mut name = struct_tag.name.as_bytes().to_vec();
    let type_args_info = format_type_params(&struct_tag.type_params).expect("format should never fail");
    name.append(&mut type_args_info.into_bytes());

**Comment by jolestar** [comment]
奇怪，context.type_to_type_tag 这么耗时。format_type_params 时候把 name 传递进去直接 append，是不是会好些。
