### ISSUE TITLE
node panic

### ISSUE THREAD

**Issue by tiangong3624749** [starcoinorg/starcoin#2083]
panic occurred:
details: panicked at 'Print result should success.: All rows in the table should have same number of cells/columns', /Users/dqm/workspace/starcoin/commons/scmd/src/context.rs:397:50
backtrace:    0:        0x10b88efda - backtrace::backtrace::libunwind::trace::h5fed1b184bd94099
                               at /Users/dqm/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.55/src/backtrace/libunwind.rs:90:5
                           backtrace::backtrace::trace_unsynchronized::hc96229322fab81c1
                               at /Users/dqm/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.55/src/backtrace/mod.rs:66:5
   1:        0x10b88ef68 - backtrace::backtrace::trace::h6fc4df531300a842
                               at /Users/dqm/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.55/src/backtrace/mod.rs:53:14
   2:        0x10b8d9aca - backtrace::capture::Backtrace::create::h5787f8ff0a3103de
                               at /Users/dqm/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.55/src/capture.rs:176:9
   3:        0x10b8d99ff - backtrace::capture::Backtrace::new::h2185d29be787857d
                               at /Users/dqm/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.55/src/capture.rs:140:22
   4:        0x107323d73 - starcoin_node::crash_handler::handle_panic::h4e48c47dc0ffb842
                               at /Users/dqm/workspace/starcoin/node/src/crash_handler.rs:21:38
   5:        0x1075a6718 - starcoin_node::crash_handler::setup_panic_handler::{{closure}}::hc635144838d5d32c
                               at /Users/dqm/workspace/starcoin/node/src/crash_handler.rs:14:9
   6:        0x10bb4ad7e - std::panicking::rust_panic_with_hook::h76436d4cf7a368ac
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:597:17
   7:        0x10bb4a885 - std::panicking::begin_panic_handler::{{closure}}::h516c76d70abf04f6
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:499:13
   8:        0x10bb48698 - std::sys_common::backtrace::__rust_end_short_backtrace::h653290b4f930faed
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141:18
   9:        0x10bb4a7ea - rust_begin_unwind
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
  10:        0x10bba1d9f - core::panicking::panic_fmt::hde9134dd19c9a74f
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
  11:        0x10bba1ca5 - core::option::expect_none_failed::h686aad664d56bca5
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/option.rs:1268:5
  12:        0x10aa111ca - core::result::Result<T,E>::expect::h8b2c9478b384553b
                               at /Users/dqm/.rustup/toolchains/1.49.0-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:933:23
  13:        0x10705853e - scmd::context::CmdContext<State,GlobalOpt>::console_inner::h82ecafa50b68e113
                               at /Users/dqm/workspace/starcoin/commons/scmd/src/context.rs:396:45
  14:        0x107055a8e - scmd::context::CmdContext<State,GlobalOpt>::exec_inner::hf2d2f30748be318a
                               at /Users/dqm/workspace/starcoin/commons/scmd/src/context.rs:224:21
  15:        0x107059a40 - scmd::context::CmdContext<State,GlobalOpt>::exec::h002465f7eb3a1408
                               at /Users/dqm/workspace/starcoin/commons/scmd/src/context.rs:184:39
  16:        0x107047163 - starcoin::run::he789ee122bf690bc
                               at /Users/dqm/workspace/starcoin/cmd/starcoin/src/main.rs:114:5
  17:        0x1070471c5 - starcoin::main::h7240684c6bdb4556
                               at /Users/dqm/workspace/starcoin/cmd/starcoin/src/main.rs:119:11
  18:        0x10702429e - core::ops::function::FnOnce::call_once::h76e16dab72843da8
                               at /Users/dqm/.rustup/toolchains/1.49.0-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  19:        0x107041a91 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb21b60db26e8d2a1
                               at /Users/dqm/.rustup/toolchains/1.49.0-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  20:        0x107040084 - std::rt::lang_start::{{closure}}::hb811aaa845e3a3c2
                               at /Users/dqm/.rustup/toolchains/1.49.0-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:66:18
  21:        0x10bb4b1b4 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h81f763a559f81b5c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:259:13
                           std::panicking::try::do_call::h8f7e7501b4b6c841
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:381:40
                           std::panicking::try::h5def58989e0f2c84
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:345:19
                           std::panic::catch_unwind::h8210e1d7d92e8f91
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panic.rs:396:14
                           std::rt::lang_start_internal::h36ccce6e8a047133
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/rt.rs:51:25
  22:        0x107040061 - std::rt::lang_start::hb741698cf7ce8c72
                               at /Users/dqm/.rustup/toolchains/1.49.0-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:65:5
  23:        0x107047e42 - _main

**Comment by tiangong3624749** [comment]
通过构造假的total difficulty，保证同步target的number比共同祖先的number低，就一定会panic；

**Comment by jolestar** [comment]
暂时不能复现

**Comment by jolestar** [comment]
暂时报错，但不 panic，tracked by #2178
