### ISSUE TITLE
Windows build failed since determinator library

### ISSUE THREAD

**Issue by sanlee42** [starcoinorg/starcoin#2121]
error[E0433]: failed to resolve: could not find `unix` in `os`
   --> C:\Users\fikgol\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\determinator-0.1.1\src\paths0.rs:171:26
    |
171 |             use std::os::unix::ffi::OsStrExt;
    |                          ^^^^ could not find `unix` in `os`

error[E0599]: no function or associated item named `new_unix` found for struct `Paths0` in the current scope
  --> C:\Users\fikgol\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\determinator-0.1.1\src\paths0.rs:89:29
   |
69 | pub struct Paths0 {
   | ----------------- function or associated item `new_unix` not found for this
...
89 |             return Ok(Self::new_unix(buf));
   |                             ^^^^^^^^ function or associated item not found in `Paths0`

error[E0599]: no function or associated item named `new_unix` found for struct `Paths0` in the current scope
   --> C:\Users\fikgol\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\determinator-0.1.1\src\paths0.rs:106:29
    |
69  | pub struct Paths0 {
    | ----------------- function or associated item `new_unix` not found for this
...
106 |             return Ok(Self::new_unix(buf));
    |                             ^^^^^^^^ function or associated item not found in `Paths0`

error[E0599]: no function or associated item named `from_bytes` found for struct `OsStr` in the current scope
   --> C:\Users\fikgol\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\determinator-0.1.1\src\paths0.rs:176:50
    |
176 |                     .map(|path| Path::new(OsStr::from_bytes(path))),
    |                                                  ^^^^^^^^^^ function or associated item not found in `OsStr`

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0433, E0599.
For more information about an error, try `rustc --explain E0433`.
error: could not compile `determinator`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by jolestar** [comment]
@fikgol 这个问题解决了吗？

**Comment by fikgol** [comment]
> @fikgol 这个问题解决了吗？
还不行， 等朱老师升级diem的时候合进去。
