### ISSUE TITLE
合约任务排查

### ISSUE THREAD

**Issue by lerencao** [starcoinorg/starcoin#2131]
stdlib 中的每个合约至少需要2人检查过说没有漏洞。
以下是合约列表，检查过的人，可以在后面加上自己的名字。

- [x] Account.move: @lerencao @tiangong3624749 
- [x] Authenticator.move: @lerencao @tiangong3624749 
- [x] BCS.move: @lerencao @tiangong3624749 
- [x] Bitwise.move: @lerencao @tiangong3624749 
- [ ] Block.move: @lerencao @tiangong3624749 
- [ ] BlockReward.move : @lerencao @tiangong3624749 
- [ ] Box.move: @lerencao @tiangong3624749 
- [ ] ChainId.move: @lerencao @tiangong3624749 
- [ ] Compare.move: @lerencao @tiangong3624749 
- [ ] Config.move: @lerencao @tiangong3624749 
- [ ] ConsensusConfig.move: @lerencao @tiangong3624749 
- [ ] ConsensusStrategy.move: @lerencao @tiangong3624749 
- [ ] CoreAddresses.move: @lerencao @tiangong3624749 
- [ ] Dao.move: @lerencao @tiangong3624749 
- [ ] Debug.move: @lerencao @tiangong3624749 
- [ ] DummyToken.move: @lerencao @tiangong3624749 
- [ ] Epoch.move: @lerencao @tiangong3624749 
- [ ] Errors.move: @lerencao @tiangong3624749 
- [ ] Event.move: @lerencao @tiangong3624749 
- [ ] FixedPoint32.move @tiangong3624749 
- [ ] Hash.move: @lerencao @tiangong3624749 
- [ ] Math.move: @lerencao @tiangong3624749 
- [ ] MintDaoProposal.move: @lerencao @tiangong3624749 
- [ ] ModifyDaoConfigProposal.move: @lerencao @tiangong3624749 
- [ ] Offer.move: @lerencao @tiangong3624749 
- [ ] OnChainConfigDao.move: @lerencao @tiangong3624749 
- [ ] Option.move: @lerencao @tiangong3624749 
- [ ] PackageTxnManager.move @tiangong3624749 
- [ ] RewardConfig.move: @lerencao @tiangong3624749 
- [ ] STC.move: @lerencao @tiangong3624749 
- [ ] SharedEd25519PublicKey.move: @lerencao @tiangong3624749 
- [ ] Signature.move: @lerencao @tiangong3624749 
- [ ] SignedInteger64.move: @lerencao @tiangong3624749 
- [ ] Signer.move: @lerencao @tiangong3624749 
- [ ] Timestamp.move: @lerencao @tiangong3624749 
- [ ] Token.move: @lerencao @tiangong3624749 
- [ ] TransactionFee.move: @lerencao @tiangong3624749 
- [ ] TransactionManager.move: @lerencao @tiangong3624749 
- [ ] TransactionPublishOption.move: @lerencao @tiangong3624749 
- [ ] TransactionTimeout.move: @lerencao @tiangong3624749 
- [ ] TransactionTimeoutConfig.move: @lerencao @tiangong3624749 
- [ ] UpgradeModuleDaoProposal.move: @lerencao @tiangong3624749 
- [ ] VMConfig.move: @lerencao @tiangong3624749 
- [ ] Vector.move: @lerencao  有些函数在 move 里面实现比较耗gas。建议放到 native 方法。 @tiangong3624749 
- [ ] Version.move: @lerencao @tiangong3624749

**Comment by tiangong3624749** [comment]
stdlib合约里面好几个地方有18446744073709551615常量，要不要考虑统一一下？

**Comment by lerencao** [comment]
基本上可以close 了。
