### ISSUE TITLE
relation of txn and block broken

### ISSUE THREAD

**Issue by lerencao** [starcoinorg/starcoin#2183]
indexer 在索引链数据时，卡在这个错误。

![image](https://user-images.githubusercontent.com/1456096/108597949-94acbf00-73c6-11eb-87f4-68b44459eba0.png)

搜索代码， *cannot find block* 只在这里出现。

![image](https://user-images.githubusercontent.com/1456096/108597938-8bbbed80-73c6-11eb-9286-fa00dac3e737.png)

看起来是 txn 反查它的 block 时，出现了问题。

**Comment by jolestar** [comment]
txn -> blockid 的映射表有问题，同一个 txn 可能会在多个 block 中出现，后面的会覆盖掉前面的，所以会出现这种情况

**Comment by lerencao** [comment]
closed in #2196
