### ISSUE TITLE
get blocks by number hang or oom 

### ISSUE THREAD

**Issue by fikgol** [starcoinorg/starcoin#2191]
![image](https://user-images.githubusercontent.com/2162274/108681956-aeffad80-752a-11eb-9fe4-3d2fc2617b01.png)

curl --data-binary '{"jsonrpc":"2.0","id":"curltext","method":"chain.get_blocks_by_number","params":[23992, 23993]}' -H 'Content-Type: application/json' http://localhost:9850

**Comment by jolestar** [comment]
第二个是 count 参数，需要限制一下大小

**Comment by tiangong3624749** [comment]
restful接口的size限制是不是跟NetworkRpc接口一样统一考虑一下？

**Comment by jolestar** [comment]
> restful接口的size限制是不是跟NetworkRpc接口一样统一考虑一下？

对，需要统一过一遍。
