### ISSUE TITLE
[rpc] some barnard node panic 

### ISSUE THREAD

**Issue by ssyuan** [starcoinorg/starcoin#2220]
2021-02-26T16:29:26.499647162+08:00 ERROR - panic occurred:
2021-02-26T16:29:26.499677022+08:00 ERROR - details: panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/shutdown.rs:51:21
2021-02-26T16:29:26.499715079+08:00 ERROR - backtrace:    0:     0x560bdca57d65 - backtrace::capture::Backtrace::create::hdd2377ea43fecba1
   1:     0x560bdca57c93 - backtrace::capture::Backtrace::new::h4aa08d3c41aa7e16
   2:     0x560bdb001eb0 - starcoin_node::crash_handler::handle_panic::h3163385e00435dfb
                               at /home/test/starcoin/node/src/crash_handler.rs:21:38
   3:     0x560bdb001e29 - starcoin_node::crash_handler::setup_panic_handler::{{closure}}::h6adadd5f309af2a4
                               at /home/test/starcoin/node/src/crash_handler.rs:14:9
   4:     0x560bdcb1f636 - std::panicking::rust_panic_with_hook::hb27ea14285131c61
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:595:17
   5:     0x560bdc5c6bf4 - std::panicking::begin_panic::{{closure}}::h917f6c73a59d432c
   6:     0x560bdc5c60bc - std::sys_common::backtrace::__rust_end_short_backtrace::hd8c8d30f5eaf7629
   7:     0x560bdc5c359c - std::panicking::begin_panic::h0880582a99070896
   8:     0x560bdc5c21a7 - tokio::runtime::blocking::shutdown::Receiver::wait::he8dbb6f96f25a0fc
   9:     0x560bdc5b3dac - tokio::runtime::blocking::pool::BlockingPool::shutdown::h274d79514b7241ce
  10:     0x560bdc5b4054 - <tokio::runtime::blocking::pool::BlockingPool as core::ops::drop::Drop>::drop::hbb0c1e09329f73fc
  11:     0x560bdbf66fde - core::ptr::drop_in_place::h524b37ee90df89ec
  12:     0x560bdbf67ee2 - jsonrpc_server_utils::reactor::Executor::close::h289422966d9df916
  13:     0x560bdb472c6a - jsonrpc_ipc_server::server::InnerHandles::close::h83276b72e63b669e
  14:     0x560bdb472a86 - jsonrpc_ipc_server::server::Server::close::h47a2b36524a073c8
  15:     0x560bdb4172b8 - starcoin_rpc_server::service::RpcService::close::h633fef9aaa167f18
  16:     0x560bdb4171f7 - <starcoin_rpc_server::service::RpcService as starcoin_service_registry::service::ActorService>::stopped::hbc1f38ef7a463fe5
  17:     0x560bdb069739 - <starcoin_service_registry::handler_proxy::ServiceHandlerProxy<S> as starcoin_service_registry::handler_proxy::HandlerProxy<S>>::stop::hffae00b8ce133a57
                               at /home/test/starcoin/commons/service-registry/src/handler_proxy.rs:88:13
  18:     0x560bdb1190a8 - <starcoin_service_registry::service_actor::ServiceActor<S> as actix::actor::Actor>::stopped::h1542c4c64fc7ae46
                               at /home/test/starcoin/commons/service-registry/src/service_actor.rs:88:25
  19:     0x560bdb1e3860 - <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll::hc8477a4671cad4e7
  20:     0x560bdb05a68a - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::h6a90d3729eadb00e
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:173:17
                           tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h879c21559a178768
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/loom/std/unsafe_cell.rs:14:9
                           tokio::runtime::task::core::Core<T,S>::poll::h269793dc27342391
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:158:13
                           tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}::h4f521bc81362ee40
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:107:27
                           core::ops::function::FnOnce::call_once::h84c94d94d4037864
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:227:5
                           <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h1a7647446cd629b6
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panic.rs:322:9
  21:     0x560bdb1d341f - std::panicking::try::do_call::h87bc6bba7f54cd32
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:379:40
                           std::panicking::try::hef0fe18032453743
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:343:19
                           std::panic::catch_unwind::h24e6c9d65c9110df
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panic.rs:396:14
                           tokio::runtime::task::harness::Harness<T,S>::poll::hde7e284e09f1fd32
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:89:19
  22:     0x560bdc5c6213 - std::thread::local::LocalKey<T>::with::h0c2c099868699fdb
  23:     0x560bdc5c4a07 - tokio::task::local::LocalSet::tick::h0c13cd26c0d1dc97
  24:     0x560bdc5a9a7a - tokio::macros::scoped_tls::ScopedKey<T>::set::h22a2609930851d83
  25:     0x560bdc5b039b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0ac0512438d99982

**Comment by jolestar** [comment]
什么情况下 panic 的？停止服务的时候？
