### ISSUE TITLE
Vector module 有些函数实现比较耗gas，建议放到 native 方法

### ISSUE THREAD

**Issue by lerencao** [starcoinorg/starcoin#2227]
看看这个要不要做。不做的话就先 close 掉，或者优先级放低。

**Comment by jolestar** [comment]
这个 Move 那边把 vector 通过指令实现了

**Comment by guangyuz** [comment]
提供一个测试：https://github.com/starcoinorg/starcoin/pull/2228

**Comment by guangyuz** [comment]
Diem pr6991 将vector的native方法换成bytecode，但是内部实现没有大的变化。gas消耗维持不变：
native function：
        (N::LENGTH, GasCost::new(98, 1)),
        (N::EMPTY, GasCost::new(84, 1)),
        (N::BORROW, GasCost::new(1334, 1)),
        (N::BORROW_MUT, GasCost::new(1902, 1)),
        (N::PUSH_BACK, GasCost::new(53, 1)),
        (N::POP_BACK, GasCost::new(227, 1)),
        (N::DESTROY_EMPTY, GasCost::new(572, 1)),
        (N::SWAP, GasCost::new(1436, 1)),

bytecode：

        (VecEmpty(SignatureIndex::new(0)), GasCost::new(84, 1)),
        (VecLen(SignatureIndex::new(0)), GasCost::new(98, 1)),
        (VecImmBorrow(SignatureIndex::new(0)), GasCost::new(1334, 1)),
        (VecMutBorrow(SignatureIndex::new(0)), GasCost::new(1902, 1)),
        (VecPushBack(SignatureIndex::new(0)), GasCost::new(53, 1)),
        (VecPopBack(SignatureIndex::new(0)), GasCost::new(227, 1)),
        (VecDestroy(SignatureIndex::new(0)), GasCost::new(572, 1)),
        (VecSwap(SignatureIndex::new(0)), GasCost::new(1436, 1)),

所以，如果想要减少remove和index_of的gas消耗，可以考虑实现这两个native方法。

**Comment by jolestar** [comment]
> Diem pr6991 将vector的native方法换成bytecode，但是内部实现没有大的变化。gas消耗维持不变：
> native function：
> (N::LENGTH, GasCost::new(98, 1)),
> (N::EMPTY, GasCost::new(84, 1)),
> (N::BORROW, GasCost::new(1334, 1)),
> (N::BORROW_MUT, GasCost::new(1902, 1)),
> (N::PUSH_BACK, GasCost::new(53, 1)),
> (N::POP_BACK, GasCost::new(227, 1)),
> (N::DESTROY_EMPTY, GasCost::new(572, 1)),
> (N::SWAP, GasCost::new(1436, 1)),
> 
> bytecode：
> 
> ```
>     (VecEmpty(SignatureIndex::new(0)), GasCost::new(84, 1)),
>     (VecLen(SignatureIndex::new(0)), GasCost::new(98, 1)),
>     (VecImmBorrow(SignatureIndex::new(0)), GasCost::new(1334, 1)),
>     (VecMutBorrow(SignatureIndex::new(0)), GasCost::new(1902, 1)),
>     (VecPushBack(SignatureIndex::new(0)), GasCost::new(53, 1)),
>     (VecPopBack(SignatureIndex::new(0)), GasCost::new(227, 1)),
>     (VecDestroy(SignatureIndex::new(0)), GasCost::new(572, 1)),
>     (VecSwap(SignatureIndex::new(0)), GasCost::new(1436, 1)),
> ```
> 
> 所以，如果想要减少remove和index_of的gas消耗，可以考虑实现这两个native方法。

感觉可以先不考虑这个，能用 Move 实现的还是尽量用 Move 比较合适。

**Comment by jolestar** [comment]
暂时先关闭。
