### ISSUE TITLE
Move core types removes dependency on diem-crypto, AccountAddress::random() break

### ISSUE THREAD

**Issue by guangyuz** [starcoinorg/starcoin#2237]
The diem commit c2d0499 has been revert temporarily. 
https://github.com/starcoinorg/diem/commit/9a46fba8ed34382c8d54b3f99fc4de2950481756

Todo - remove the above WA and fix the break.

**Comment by jolestar** [comment]
可以通过 rand 直接生成一些 bytes

**Comment by guangyuz** [comment]
不只AccountAddress::random()， starcoin的AccountAddress 源自move_core_type::AccountAddress， Diem去掉move_core_type对 diem-crypto的依赖后，AccountAddress 的 CryptoHasher derive没了，很多地方都会有问题
