### ISSUE TITLE
jsonrpc interface access leads to OOM 

### ISSUE THREAD

**Issue by ssyuan** [starcoinorg/starcoin#2238]
1、通过websocket方式访问list_block接口
count = 50
 mac下会卡顿，ubuntu直接OOM：

4 23:27:59 localhost kernel: [1643250.973248] Out of memory: Kill process 10321 (starcoin) score 694 or sacrifice child
4 23:27:59 localhost kernel: [1643250.846050] gmain invoked oom-killer: gfp_mask=0x14200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=0

count=30，内存缓慢增长，大约两三个小时也会OOM

Mar  5 02:20:36 localhost kernel: [1653608.319775] apport invoked oom-killer: gfp_mask=0x14200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=0
Mar  5 02:20:36 localhost kernel: [1653608.334670]  oom_kill_process+0x21f/0x420
Mar  5 02:20:36 localhost kernel: [1653608.445996] [ pid ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
Mar  5 02:20:36 localhost kernel: [1653608.818570] oom_reaper: reaped process 12977 (starcoin), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

 
测试脚本：

block_num=15812
while [ $block_num -gt 0 ]
do
     echo "number: $block_num"
     ./starcoin -c ws://127.0.0.1:9870 -o json chain list_block  -n $block_num -c 30 |grep -v INFO | jq ".ok|.[]| {\"number\" : .number, \"author\" : .author }" >> barnard_block_author
    printf "\n \r"
    block_num=$((block_num-30))
done

**Comment by lerencao** [comment]
通过 http 接口有这个问题吗

**Comment by ssyuan** [comment]
http没有试过，我验证下

**Comment by lerencao** [comment]
卡顿的原因在于，当rpc 请求返回的数据超过 10M 时，

```
[36mstarcoin1_1  |[0m 2021-03-05T08:15:32.628372200Z 2021-03-05T08:15:32.100038900+00:00 TRACE - Handler will send: 
[36mstarcoin1_1  |[0m 2021-03-05T08:15:32.628420600Z <FRAME>
[36mstarcoin1_1  |[0m 2021-03-05T08:15:32.628434300Z final: true
[36mstarcoin1_1  |[0m 2021-03-05T08:15:32.628448800Z reserved: false false false
[36mstarcoin1_1  |[0m 2021-03-05T08:15:32.628460300Z opcode: TEXT
[36mstarcoin1_1  |[0m 2021-03-05T08:15:32.628471400Z length: 11892247
[36mstarcoin1_1  |[0m 2021-03-05T08:15:32.628483600Z payload length: 11892237

```

websocket server 的 buffer 无法承载，导致向上抛出错误。

```
[36mstarcoin1_1  |[0m 2021-03-05T08:15:36.905192500Z 2021-03-05T08:15:36.903377500+00:00 ERROR - WS Error <Io(Custom { kind: InvalidInput, error: "Exceeded maximum buffer capacity" })>
[36mstarcoin1_1  |[0m 2021-03-05T08:15:36.905588700Z 2021-03-05T08:15:36.905434100+00:00 DEBUG - Connection closing due to (Abnormal) 
[36mstarcoin1_1  |[0m 2021-03-05T08:15:36.906065200Z 2021-03-05T08:15:36.905892300+00:00 TRACE - Scheduling connection to 172.24.0.1:64264 as (empty)
```

但上层在 handle 这个错误时，只是不处理 connection 的 read write events: `Scheduling connection to 172.24.0.1:64264 as (empty)`。并没有真的 close 这个 connection。

<img width="632" alt="image" src="https://user-images.githubusercontent.com/1456096/110267094-12dda800-7ffa-11eb-8044-76342bec7cbb.png">

这导致客户端一直在等待对端的数据。
所以出现卡住的情况。

**Comment by lerencao** [comment]
接口优化了，返回的数据变少。
