### ISSUE TITLE
rpc

### ISSUE THREAD

**Issue by kongtaoxing** [starcoinorg/starcoin#2287]
node network rpc is slow sometimes in China, please change a better one, or can someone create a better one?

**Comment by jolestar** [comment]
Do you connect to Halley network? the Halley network's node only available in digitalocean.

ps: discussion and question topic should be post at  https://github.com/starcoinorg/starcoin/discussions.

**Comment by jolestar** [comment]
Thanks for feedback, please post the report at https://github.com/starcoinorg/starcoin/discussions/2291

**Comment by kongtaoxing** [comment]
The problem is solved, thank you for helping.
