### ISSUE TITLE
Cpu usage diagnose

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#241]
Cpu 偶尔会异常高，需要诊断原因

**Comment by fikgol** [comment]
可能是这个 https://github.com/starcoinorg/starcoin/pull/258  ，有待继续观察。

**Comment by fikgol** [comment]
阻塞的很多 generate block event 突然被调度到， 每一个生成了一个 event 生成了 一个 thread 造成。
现在只 spawn 一个新线程去处理。
