### ISSUE TITLE
block storage coherence bug

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#2452]
barnard4 的数据好像有问题了，看起来是数据不一致，然后同步的时候卡在 194253 这个高度一直死循环

```
2021-04-26T13:56:47.410500359+00:00 INFO - [sync] Start sync block, ancestor: BlockIdAndNumber { id: HashValue(0x99ddd2085f335a3ba9f46be87d24ed52583a4698fc53915f2bb5795ed567e653), number: 194253 }, start_number: 194254, check_local_store: false, target_number: 195316
2021-04-26T13:56:47.433211250+00:00 WARN - [sync] Sync task is interrupted by Can not find block by number 194227, head block number: 194253, cause:"Can not find block by number 194227, head block number: 194253"
```
chain get_block_by_number 194227 报告找不到区块。194226，194228 存在。

<img width="831" alt="Screen Shot 2021-04-26 at 22 05 42" src="https://user-images.githubusercontent.com/77268/116178433-2975c500-a748-11eb-9824-3ff437086a7e.png">

当时执行 194227 区块前后的日志

```
2021-04-25T20:58:12.383363855+00:00 INFO - [chain] Select new head, id: 0x74fb1426615f2780bee0e04a74a07d352b7167bdbcd3cb0148bf36f6a78d35c4, number: 194227, total_difficulty: 20699011716, enacted_block_count: 1, retracted_b
lock_count: 0
2021-04-25T20:59:23.917551994+00:00 WARN - BlockConnector fail: Can not find block HashValue(0x74fb1426615f2780bee0e04a74a07d352b7167bdbcd3cb0148bf36f6a78d35c4)., peer_id:PeerId(PeerId("12D3KooWEXZwhQqxrm9CJZuQWb1SFNtwVamE
vNs2jtrCsiUVFwQg"))
2021-04-25T20:59:31.338050153+00:00 INFO - [chain] Select new head, id: 0x6fd3301210e794da964976acf718793d6f031e77ed1698cb456243eb65dae52b, number: 194228, total_difficulty: 20699418468, enacted_block_count: 1, retracted_b
lock_count: 0 
```

节点重启后恢复了。

**Comment by ssyuan** [comment]
问题初步定位，出在rocksdb上：
出问题的starcoin1节点上的wal达到最大值后一直清理不掉：
Interval WAL: 2280 writes, 2280 syncs, 1.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Cumulative WAL: 1119K writes, 1119K syncs, 1.00 writes per sync, written: 1.44 GB, 0.00 MB/s
Interval WAL: 2188 writes, 2188 syncs, 1.00 writes per sync, written: 0.00 MB, 0.00 MB/s
2021/04/25-02:33:53.592861 7f12bddf6700 [db/db_impl/db_impl_write.cc:1262] Flushing all column families with data in WAL number 203. **Total log size is 1073745602 while max_total_wal_size is 1073741824**
2021/04/25-02:33:53.603244 7f12bf5fe700 [db/db_impl/db_impl_files.cc:418] [JOB 42] Try to delete WAL files size 567412358, prev total WAL file size 1073749357, number of live WAL files 18.
Cumulative WAL: 1122K writes, 1122K syncs, 1.00 writes per sync, written: 1.45 GB, 0.00 MB/s
Interval WAL: 2225 writes, 2225 syncs, 1.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Cumulative WAL: 1124K writes, 1124K syncs, 1.00 writes per sync, written: 1.45 GB, 0.00 MB/s
Interval WAL: 2276 writes, 2276 syncs, 1.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Cumulative WAL: 1126K writes, 1126K syncs, 1.00 writes per sync, written: 1.45 GB, 0.00 MB/s
Interval WAL: 2442 writes, 2442 syncs, 1.00 writes per sync, written: 0.00 MB, 0.01 MB/s
2021/04/25-03:10:15.658370 7f12bf5fe700 [db/db_impl/db_impl_files.cc:418] [JOB 43] Try to delete WAL files size 29842337, prev total WAL file size 518403880, number of live WAL files 10.
Cumulative WAL: 1129K writes, 1129K syncs, 1.00 writes per sync, written: 1.46 GB, 0.00 MB/s
Interval WAL: 2506 writes, 2506 syncs, 1.00 writes per sync, written: 0.00 MB, 0.01 MB/s
Cumulative WAL: 1130K writes, 1130K syncs, 1.00 writes per sync, written: 1.46 GB, 0.00 MB/s
Interval WAL: 1663 writes, 1663 syncs, 1.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Cumulative WAL: 1133K writes, 1133K syncs, 1.00 writes per sync, written: 1.46 GB, 0.00 MB/s
Interval WAL: 2133 writes, 2133 syncs, 1.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Cumulative WAL: 1135K writes, 1135K syncs, 1.00 writes per sync, written: 1.46 GB, 0.00 MB/s
Interval WAL: 2059 writes, 2059 syncs, 1.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Cumulative WAL: 1136K writes, 1136K syncs, 1.00 writes per sync, written: 1.46 GB, 0.00 MB/s
Interval WAL: 1516 writes, 1516 syncs, 1.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Cumulative WAL: 1137K writes, 1137K syncs, 1.00 writes per sync, written: 1.47 GB, 0.00 MB/s
Interval WAL: 754 writes, 754 syncs, 1.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Cumulative WAL: 1138K writes, 1138K syncs, 1.00 writes per sync, written: 1.47 GB, 0.00 MB/s
Interval WAL: 859 writes, 859 syncs, 1.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Cumulative WAL: 1139K writes, 1139K syncs, 1.00 writes per sync, written: 1.47 GB, 0.00 MB/s
Interval WAL: 975 writes, 975 syncs, 1.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Cumulative WAL: 1140K writes, 1140K syncs, 1.00 writes per sync, written: 1.47 GB, 0.00 MB/s
Interval WAL: 973 writes, 973 syncs, 1.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Cumulative WAL: 1141K writes, 1141K syncs, 1.00 writes per sync, written: 1.47 GB, 0.00 MB/s
Interval WAL: 1193 writes, 1193 syncs, 1.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Cumulative WAL: 1146K writes, 1146K syncs, 1.00 writes per sync, written: 1.48 GB, 0.00 MB/s
Interval WAL: 5130 writes, 5130 syncs, 1.00 writes per sync, written: 0.00 MB, 0.01 MB/s
Cumulative WAL: 1147K writes, 1147K syncs, 1.00 writes per sync, written: 1.48 GB, 0.00 MB/s
Interval WAL: 798 writes, 798 syncs, 1.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Cumulative WAL: 1148K writes, 1148K syncs, 1.00 writes per sync, written: 1.48 GB, 0.00 MB/s
Interval WAL: 866 writes, 866 syncs, 1.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Cumulative WAL: 1148K writes, 1148K syncs, 1.00 writes per sync, written: 1.48 GB, 0.00 MB/s

跟发生问题的区块时间吻合
正常节点的wal日志：
Cumulative WAL: 119K writes, 119K syncs, 1.00 writes per sync, written: 0.12 GB, 0.00 MB/s
Interval WAL: 118 writes, 118 syncs, 0.99 writes per sync, written: 0.00 MB, 0.00 MB/s
Cumulative WAL: 119K writes, 119K syncs, 1.00 writes per sync, written: 0.12 GB, 0.00 MB/s
Interval WAL: 121 writes, 121 syncs, 0.99 writes per sync, written: 0.00 MB, 0.00 MB/s
Cumulative WAL: 120K writes, 120K syncs, 1.00 writes per sync, written: 0.12 GB, 0.00 MB/s
Interval WAL: 389 writes, 389 syncs, 1.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Cumulative WAL: 120K writes, 120K syncs, 1.00 writes per sync, written: 0.12 GB, 0.00 MB/s
Interval WAL: 573 writes, 573 syncs, 1.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Cumulative WAL: 121K writes, 121K syncs, 1.00 writes per sync, written: 0.12 GB, 0.00 MB/s
Interval WAL: 642 writes, 642 syncs, 1.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Cumulative WAL: 121K writes, 121K syncs, 1.00 writes per sync, written: 0.12 GB, 0.00 MB/s

wal参数需要进一步优化调整

**Comment by jolestar** [comment]
#2654 和这个问题一样

**Comment by nkysg** [comment]
处理类似#2654
