### ISSUE TITLE
[stdlib] Check the compatibility between latest stdlib and previous stable stdlib.

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#2460]
当前检查兼容性的策略是拿当前代码和前一次 latest 的编译二进制进行比较，如果开发过程中产生了不兼容性变更，就需要加上 --no-check-compatibility 跳过检查，编译出新的二进制。但这样也可能导致不兼容的修改出现。

期望：latest 和 previous stable stdlib 应该是兼容的。

**Comment by guangyuz** [comment]
It's better add a unit test to check compatibility between the latest and previous stable version.

**Comment by jolestar** [comment]
版本之间的升级以及测试用例已经在 #2465 这个中增加了，但当前编译过程中的默认兼容性检查，感觉也应该是和上一个 stable 版本之间比较，这样开发过程中就比较容易发现不兼容问题。

**Comment by jolestar** [comment]
和 stable 版本之间的检查也在  #2465  中实现了。
