### ISSUE TITLE
p2p nat penetration

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#248]
利用 libp2p 实现 p2p nat 穿透

**Comment by fikgol** [comment]
rust-libp2p 应该是不支持upnp协议的(bitcoin的nat方案) substrate的这个issue讨论过: https://github.com/paritytech/substrate/issues/2772

**Comment by fikgol** [comment]
还有个内网不可达 ip 污染 dht 的问题: https://github.com/paritytech/substrate/issues/4920

**Comment by jolestar** [comment]
@fikgol 这两个 issue 确实和我们遇到的问题相关，看怎么去实现这个。

**Comment by fikgol** [comment]
libp2p 开发者对 nat 的现状描述和开发计划: https://github.com/libp2p/rust-libp2p/issues/794#issuecomment-474782253
总结下就是不打算支持 upnp, 但做了一个类似stun/tun的协议，但 relay 部分还在开发中。还不能用。目前的 rust-libp2p 版本没法打洞。

**Comment by fikgol** [comment]
附2个代码实现的例子用于理解:
1. bitcoin/ethereum 的 nat 方案 upnp pythone example: https://raw.githubusercontent.com/miniupnp/miniupnp/master/miniupnpc/testupnpigd.py
2. TCP hold punching example in rust:
https://github.com/libp2p/rust-libp2p/issues/348

**Comment by jolestar** [comment]
等 rust-libp2p 那边的实现
