### ISSUE TITLE
Node exit for an unexpected error: Corruption: SST file is ahead of WALs

### ISSUE THREAD

**Issue by yourmoonlight** [starcoinorg/starcoin#2508]
can't start, just after manual killed the process

**Comment by nkysg** [comment]
这个有日志吗，为啥数据会不一致

**Comment by nkysg** [comment]
这个有日志吗

**Comment by yourmoonlight** [comment]
> 这个有日志吗

抱歉，时间有点久，我这里没日志了

**Comment by nkysg** [comment]
还记得您是什么环境吗，Linux？还是Mac，磁盘空间够吗

**Comment by nkysg** [comment]
> > 这个有日志吗
> 
> 抱歉，时间有点久，我这里没日志了

还记得您是什么环境吗，Linux？还是Mac，磁盘空间够吗

**Comment by nkysg** [comment]
This error unlike https://github.com/starcoinorg/starcoin/issues/3128 . they are different issues.
On my mac, I used ```kill -9 starcoin``` command many times. only found this error 
```
2021-12-30T18:56:20.890594+08:00 INFO - Try to connect node by ipc: "/Users/test/main/starcoin.ipc"
2021-12-30T18:56:20.891966+08:00 ERROR - Starcoin cmd exits abnormally: Connection refused (os error 61)
```
then i remove /Users/test/main/starcoin.ipc, restart starcoin it looks work fine
Could you help me to repetition this bug. Thank you! @yourmoonlight

**Comment by nkysg** [comment]
same as https://github.com/starcoinorg/starcoin/issues/3128
