### ISSUE TITLE
mint tools && pool

### ISSUE THREAD

**Issue by sanlee42** [starcoinorg/starcoin#2525]
- [x]  Miner client support stratum protocol. (support mint by cpu&&s1-mini in pool with macos&&linux)
- [ ]  cnr cpu optimizer
- [x]  Add reward info in subscribe MintBlockEvent rpc
- [x]  Return block hash in response of submit seal rpc 
- [x]  Support change mint reward address outside of node (with out private key)

**Comment by jolestar** [comment]
“Support change mint reward address outside of node (with out private key)” implement by #2536
