### ISSUE TITLE
CreateBlockTemplate miner panic

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#253]
tarcoin% thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: BlockTransactionDiscard(VMStatus { major_status: SEQUENCE_NUMBER_TOO_OLD, sub_status: None, message: None }, HashValue(c9de449ac4d5af9b03b8d782d81b1e81e7e5e5e668734ef0a41efeda1f401523))', /Users/jolestar/opensource/src/github.com/starcoinorg/starcoin/chain/src/chain.rs:211:13
stack backtrace:
   0:        0x109061085 - backtrace::backtrace::libunwind::trace::h5c84db184dbe55ed
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:        0x109061085 - backtrace::backtrace::trace_unsynchronized::hfabf504f184a4062
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:        0x109061085 - std::sys_common::backtrace::_print_fmt::hb18545a457444b58
                               at src/libstd/sys_common/backtrace.rs:77
   3:        0x109061085 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hff7732c2e44ef8b9
                               at src/libstd/sys_common/backtrace.rs:59
   4:        0x1090816dd - core::fmt::write::hd42cb3dea57bae40
                               at src/libcore/fmt/mod.rs:1052
   5:        0x109059a1b - std::io::Write::write_fmt::ha39f6009af02b1d2
                               at src/libstd/io/mod.rs:1426
   6:        0x10906348a - std::sys_common::backtrace::_print::h5cfb8cdd320f1e64
                               at src/libstd/sys_common/backtrace.rs:62
   7:        0x10906348a - std::sys_common::backtrace::print::hef683e3bc77ce269
                               at src/libstd/sys_common/backtrace.rs:49
   8:        0x10906348a - std::panicking::default_hook::{{closure}}::h389f076017b5df43
                               at src/libstd/panicking.rs:204
   9:        0x10906318a - std::panicking::default_hook::h04b06ec20c41bf02
                               at src/libstd/panicking.rs:224
  10:        0x109063add - std::panicking::rust_panic_with_hook::hccde7faed9a5c398
                               at src/libstd/panicking.rs:472
  11:        0x1090636a2 - rust_begin_unwind
                               at src/libstd/panicking.rs:380
  12:        0x1090b2def - std::panicking::begin_panic::hc520a8a43176ea4c
  13:        0x1090b2cf5 - std::panicking::begin_panic::hc520a8a43176ea4c
  14:        0x105ae7837 - core::result::Result<T,E>::unwrap::h51feb3ac1101fd6b
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/result.rs:963
  15:        0x105a525a3 - starcoin_chain::chain::BlockChain<C,S,P>::create_block_template_inner::h9dc32ffe2350d1cf
                               at /Users/jolestar/opensource/src/github.com/starcoinorg/starcoin/chain/src/chain.rs:211
  16:        0x105a498ad - <starcoin_chain::chain::BlockChain<C,S,P> as starcoin_traits::chain::ChainReader>::create_block_template::he56156afe212d5e2
                               at /Users/jolestar/opensource/src/github.com/starcoinorg/starcoin/chain/src/chain.rs:338
  17:        0x105a8ff4e - starcoin_miner::stratum::mint::h76ecd4228ebfd6d6
                               at /Users/jolestar/opensource/src/github.com/starcoinorg/starcoin/miner/src/stratum.rs:55
  18:        0x105a33c21 - <starcoin_miner::MinerActor<C,P,CS,S,H> as actix::handler::Handler<starcoin_miner::GenerateBlockEvent>>::handle::{{closure}}::{{closure}}::h9995d7a93d6630c1
                               at /Users/jolestar/opensource/src/github.com/starcoinorg/starcoin/miner/src/lib.rs:178
  19:        0x1059c0763 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha495512e2d43469f
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/sys_common/backtrace.rs:129
  20:        0x105ac5fe3 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h304ebe4329b3c125
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/thread/mod.rs:475
  21:        0x105bd9043 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::he18742a1f17b13b6
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panic.rs:318
  22:        0x105918ca8 - std::panicking::try::do_call::h651b236da3ddb950
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panicking.rs:305
  23:        0x1090682ab - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  24:        0x1059151bd - std::panicking::try::h90f4ed683486a89b
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panicking.rs:281
  25:        0x105bd9933 - std::panic::catch_unwind::h92428193e34009b7
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panic.rs:394
  26:        0x105ac58ac - std::thread::Builder::spawn_unchecked::{{closure}}::haf97e684e31a4e5a
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/thread/mod.rs:474
  27:        0x105af7505 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hb5787caaf4dd83e6
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/ops/function.rs:232
  28:        0x10905190e - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h606f2dced48ff3c4
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
  29:        0x1090677ee - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h0ece8cce658c93ae
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
  30:        0x1090677ee - std::sys_common::thread::start_thread::h30bbd9f3fb79e88c
                               at src/libstd/sys_common/thread.rs:13
  31:        0x1090677ee - std::sys::unix::thread::Thread::new::thread_start::h7199626a1bd56873
                               at src/libstd/sys/unix/thread.rs:80

**Comment by fikgol** [comment]
https://github.com/starcoinorg/starcoin/pull/257/commits/9aa92d47248ab3faec5af3f94d9bad9e71df43dd

**Comment by fikgol** [comment]
https://github.com/starcoinorg/starcoin/pull/258
