### ISSUE TITLE
Transaction argument and event display for human

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#2556]
当前 transaction 构造后， argument 为二进制，如果想展示给人看的时候，非常不方便（比如 cli 操作时检查交易参数，未来其他钱包也会有类似的问题，包括当前的区块浏览器）。

考虑通过 abi 提供一种通用的 transaction argument parse 的方法，用在这种场景中。

Event 的展示也类似。

**Comment by fikgol** [comment]
这样api使用者是否就不用依赖bcs了？

**Comment by jolestar** [comment]
> 这样api使用者是否就不用依赖bcs了？

看这个转换在那一层实现。感觉 api 这层转换比较难，估计还是得 sdk 层转换。

**Comment by jolestar** [comment]
依赖 #2636
