### ISSUE TITLE
一个偶发问题，从节点查不到交易状态

### ISSUE THREAD

**Issue by GXKe** [starcoinorg/starcoin#2577]
0xfd28c75a8cc54e9f13a8e36746169aeae540eb92e6ed669dbf4285132e24bd7e   
同一区块的兄弟交易，在两分钟前就查到状态了，但当时这一笔连续重试都从节点查不出来
查询接口是sdk的get_transaction_info
区块号357957

日志：
`
[PID:322502 2021-06-08 09:17:03,819 INFO]: tx wait status success, tx_id:0x6f124c305c4f3099f13e86e8c732e1f253874c58569f2568ed8a9e51bdf1b57c
[PID:322502 2021-06-08 09:17:03,839 INFO]: tx wait status success, tx_id:0x87a2a5a294a9ebc9fca6fc97d1de3dda82ee112e5dba07c6a88748e811696b3a
[PID:322502 2021-06-08 09:17:03,855 INFO]: tx wait status success, tx_id:0x54f632bca8816c1862919851de2239170cbb102fe3f47e72d0784e50894baf53
[PID:322502 2021-06-08 09:19:54,038 WARNING]: get transaction info timeout, for:0xfd28c75a8cc54e9f13a8e36746169aeae540eb92e6ed669dbf4285132e24bd7e status:None
[PID:322502 2021-06-08 09:19:54,039 ERROR]: tx wait status fail, tx_id:0xfd28c75a8cc54e9f13a8e36746169aeae540eb92e6ed669dbf4285132e24bd7e
`

sdk调用代码

![image](https://user-images.githubusercontent.com/4132888/121112173-a1083b00-c842-11eb-8adf-20e32fe70fe6.png)

**Comment by fikgol** [comment]
区块浏览器里能查到。 是不是 sdk 连接的节点分叉了。

**Comment by GXKe** [comment]
目前节点也能查到，仅当时查不到。
分叉有可能，主块变孤块，再变回主块

**Comment by jolestar** [comment]
当时的节点日志有么？

**Comment by jolestar** [comment]
看日志是这个交易的 seq number 重复了，另外一个节点打包了另外一个交易。
