### ISSUE TITLE
barnard test network startup error

### ISSUE THREAD

**Issue by ssyuan** [starcoinorg/starcoin#2598]
env：starcoin/starcoin:v1.2.0
error：

2021-06-15T10:13:19.737431621+00:00 WARN - Unable to determine socket peer address, ignoring connection Transport endpoint is not connected (os error 107)
2021-06-15T10:13:19.750893027+00:00 INFO - 13 /starcoin/rpc/get_blocks 254 true 74
2021-06-15T10:13:19.783021613+00:00 INFO - 14 /starcoin/rpc/get_blocks 254 true 106
2021-06-15T10:13:19.783221999+00:00 INFO - 16 /starcoin/rpc/get_blocks 254 true 103
2021-06-15T10:13:19.783335404+00:00 INFO - 18 /starcoin/rpc/get_blocks 254 true 101
2021-06-15T10:13:19.794780026+00:00 ERROR - panic occurred:
panic occurred:
2021-06-15T10:13:19.794809123+00:00 ERROR - details: panicked at 'removal index (is 287) should be < len (is 286)', library/alloc/src/vec/mod.rs:1349:13
details: panicked at 'removal index (is 287) should be < len (is 286)', library/alloc/src/vec/mod.rs:1349:13
2021-06-15T10:13:19.794828203+00:00 ERROR - backtrace:    0:     0x55aedfe35447 - backtrace::backtrace::trace::h7fbdb819c87803b5
   1:     0x55aedfe21e25 - backtrace::capture::Backtrace::new::h472fbfebdaa3d7fd
   2:     0x55aede0f3d0e - starcoin_node::crash_handler::handle_panic::h35444a513c65f0d7
                               at /starcoin/node/src/crash_handler.rs:21:38
   3:     0x55aede0f3c89 - starcoin_node::crash_handler::setup_panic_handler::{{closure}}::hb3e23b755ae701a7
                               at /starcoin/node/src/crash_handler.rs:14:9
   4:     0x55aedfeedf06 - std::panicking::rust_panic_with_hook::h71e6a073d87de1f5
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   5:     0x55aedfeeda27 - std::panicking::begin_panic_handler::{{closure}}::hd549436f6bb6dbb8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
   6:     0x55aedfeeb35c - std::sys_common::backtrace::__rust_end_short_backtrace::h4e5f4b72b04174c3
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   7:     0x55aedfeed989 - rust_begin_unwind
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   8:     0x55aedff0c571 - core::panicking::panic_fmt::hcd56f7f635f62c74
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   9:     0x55aedff06a26 - alloc::vec::Vec<T,A>::remove::assert_failed::h9cc7fd73decf979c
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/vec/mod.rs:1349:13
  10:     0x55aedf208be9 - alloc::vec::Vec<T,A>::remove::h0b5b924a1c120c8b
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/vec/mod.rs:1354:13
                           move_vm_runtime::loader::ModuleCache::remove::h6110ecbaeb01532e
                               at /usr/local/cargo/git/checkouts/diem-5aa6d6b8b0487904/6e1cc95/language/move-vm/runtime/src/loader.rs:174:25
                           move_vm_runtime::loader::Loader::unload_module::h8da5f09dc04a3c50
                               at /usr/local/cargo/git/checkouts/diem-5aa6d6b8b0487904/6e1cc95/language/move-vm/runtime/src/loader.rs:989:9
  11:     0x55aedf1dcca1 - move_vm_runtime::runtime::VMRuntime::publish_module::h3a447bf51f9adea4
                               at /usr/local/cargo/git/checkouts/diem-5aa6d6b8b0487904/6e1cc95/language/move-vm/runtime/src/runtime.rs:93:13
  12:     0x55aedf1c69a4 - move_vm_runtime::session::Session<R>::publish_module::h2b339adacb0742dc
                               at /usr/local/cargo/git/checkouts/diem-5aa6d6b8b0487904/6e1cc95/language/move-vm/runtime/src/session.rs:161:9
                           move_vm_runtime::move_vm_adapter::SessionAdapter<R>::publish_module::hac2052048e58ca2b
                               at /usr/local/cargo/git/checkouts/diem-5aa6d6b8b0487904/6e1cc95/language/move-vm/runtime/src/move_vm_adapter.rs:128:9
                           starcoin_vm_runtime::starcoin_vm::StarcoinVM::execute_package::hb3b9087dad7e9f5e
                               at /starcoin/vm/vm-runtime/src/starcoin_vm.rs:397:25
  13:     0x55aedf1c9fa0 - starcoin_vm_runtime::starcoin_vm::StarcoinVM::execute_user_transaction::hdbf2240b7e40a7f7
                               at /starcoin/vm/vm-runtime/src/starcoin_vm.rs:707:55
                           starcoin_vm_runtime::starcoin_vm::StarcoinVM::execute_block_transactions::h39c7ff680600361f
                               at /starcoin/vm/vm-runtime/src/starcoin_vm.rs:833:29
  14:     0x55aedf1bebe2 - starcoin_executor::executor::do_execute_block_transactions::hfd64308a1bdb2808
                               at /starcoin/executor/src/executor.rs:38:18
  15:     0x55aedf1b4c94 - starcoin_executor::executor::execute_block_transactions::hef785f6cb15bde4f
                               at /starcoin/executor/src/executor.rs:26:5
                           starcoin_executor::block_executor::block_execute::h56e6c9f632efbea1
                               at /starcoin/executor/src/block_executor.rs:36:9
  16:     0x55aedea9878b - starcoin_chain::chain::BlockChain::execute_block_and_save::h740bd3787368e347
                               at /starcoin/chain/src/chain.rs:386:13
  17:     0x55aedea9f28b - <starcoin_chain::chain::BlockChain as starcoin_chain_api::chain::ChainReader>::execute::hcdc2616284b754fb
                               at /starcoin/chain/src/chain.rs:754:9
  18:     0x55aedeaa1c24 - starcoin_chain::chain::BlockChain::apply_with_verifier::ha874caec2e1b81c1
                               at /starcoin/chain/src/chain.rs:337:30
                           <starcoin_chain::chain::BlockChain as starcoin_chain_api::chain::ChainWriter>::apply::h41f388414e78c8a5
                               at /starcoin/chain/src/chain.rs:911:9
  19:     0x55aede4b0f5a - starcoin_sync::tasks::block_sync_task::BlockCollector<N,H>::apply_block::h622fc2a38861a91d
                               at /starcoin/sync/src/tasks/block_sync_task.rs:229:13
                           <starcoin_sync::tasks::block_sync_task::BlockCollector<N,H> as stream_task::collector::TaskResultCollector<starcoin_sync::tasks::block_sync_task::SyncBlockData>>::collect::hfe7877c752706e4b
                               at /starcoin/sync/src/tasks/block_sync_task.rs:284:17
  20:     0x55aede450284 - stream_task::collector::FutureTaskSink<Item,Output>::new::{{closure}}::h31bce0fddeddd86e
                               at /starcoin/commons/stream-task/src/collector.rs:164:39
                           <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h658575a5eeb73be3
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/future/mod.rs:80:19
  21:     0x55aede45ed0e - <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::{{closure}}::hc4dff2c81766c722
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/builder.rs:199:17
                           async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}::ha9fb517206d85900
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/task_locals_wrapper.rs:60:13
                           std::thread::local::LocalKey<T>::try_with::h5b9f6a884d32d6c0
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/local.rs:272:16
                           std::thread::local::LocalKey<T>::with::h223acb3e18379429
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/local.rs:248:9
                           async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::habbc16ce9fa306a7
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/task_locals_wrapper.rs:55:9
                           <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::hddd376ef609c9c69
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/builder.rs:197:13
                           async_executor::Executor::spawn::{{closure}}::h8890e9183287dbfd
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.0/src/lib.rs:138:13
                           <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hfd03e1bfcc185267
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/future/mod.rs:80:19
  22:     0x55aede4226e6 - <core::pin::Pin<P> as core::future::future::Future>::poll::h3d25a6ea9d1ebd33
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/future/future.rs:119:9
                           async_task::raw::RawTask<F,T,S>::run::h3b1c42064644959d
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/raw.rs:489:20
  23:     0x55aedf0a4000 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h191f375b7ad3d5f4
  24:     0x55aedf0a4ee1 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hba45fcc27456f4ad
  25:     0x55aedf0a2758 - async_io::driver::block_on::hbf565014ead8bca3
  26:     0x55aedf09c97a - std::thread::local::LocalKey<T>::with::h6bb35e138613eaa6
  27:     0x55aedf09b76a - async_global_executor::threading::thread_main_loop::hbce59a93adf18c99
  28:     0x55aedf09c7c7 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbad39d38001c34c1
  29:     0x55aedf09d082 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc5f26f0b00cdeeea
  30:     0x55aedfef33ba - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h61144a2be4ee36d8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
                           <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcf5d395fdd120c17
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
                           std::sys::unix::thread::Thread::new::thread_start::hb5e40d3d934ebb7a
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
  31:     0x7fb01bb546db - start_thread
  32:     0x7fb01ca0571f - __clone
  33:                0x0 - <unknown>

backtrace:    0:     0x55aedfe35447 - backtrace::backtrace::trace::h7fbdb819c87803b5
   1:     0x55aedfe21e25 - backtrace::capture::Backtrace::new::h472fbfebdaa3d7fd
   2:     0x55aede0f3d0e - starcoin_node::crash_handler::handle_panic::h35444a513c65f0d7
                               at /starcoin/node/src/crash_handler.rs:21:38
   3:     0x55aede0f3c89 - starcoin_node::crash_handler::setup_panic_handler::{{closure}}::hb3e23b755ae701a7
                               at /starcoin/node/src/crash_handler.rs:14:9
   4:     0x55aedfeedf06 - std::panicking::rust_panic_with_hook::h71e6a073d87de1f5
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   5:     0x55aedfeeda27 - std::panicking::begin_panic_handler::{{closure}}::hd549436f6bb6dbb8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
   6:     0x55aedfeeb35c - std::sys_common::backtrace::__rust_end_short_backtrace::h4e5f4b72b04174c3
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   7:     0x55aedfeed989 - rust_begin_unwind
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   8:     0x55aedff0c571 - core::panicking::panic_fmt::hcd56f7f635f62c74
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   9:     0x55aedff06a26 - alloc::vec::Vec<T,A>::remove::assert_failed::h9cc7fd73decf979c
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/vec/mod.rs:1349:13
  10:     0x55aedf208be9 - alloc::vec::Vec<T,A>::remove::h0b5b924a1c120c8b
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/vec/mod.rs:1354:13
                           move_vm_runtime::loader::ModuleCache::remove::h6110ecbaeb01532e
                               at /usr/local/cargo/git/checkouts/diem-5aa6d6b8b0487904/6e1cc95/language/move-vm/runtime/src/loader.rs:174:25
                           move_vm_runtime::loader::Loader::unload_module::h8da5f09dc04a3c50
                               at /usr/local/cargo/git/checkouts/diem-5aa6d6b8b0487904/6e1cc95/language/move-vm/runtime/src/loader.rs:989:9
  11:     0x55aedf1dcca1 - move_vm_runtime::runtime::VMRuntime::publish_module::h3a447bf51f9adea4
                               at /usr/local/cargo/git/checkouts/diem-5aa6d6b8b0487904/6e1cc95/language/move-vm/runtime/src/runtime.rs:93:13
  12:     0x55aedf1c69a4 - move_vm_runtime::session::Session<R>::publish_module::h2b339adacb0742dc
                               at /usr/local/cargo/git/checkouts/diem-5aa6d6b8b0487904/6e1cc95/language/move-vm/runtime/src/session.rs:161:9
                           move_vm_runtime::move_vm_adapter::SessionAdapter<R>::publish_module::hac2052048e58ca2b
                               at /usr/local/cargo/git/checkouts/diem-5aa6d6b8b0487904/6e1cc95/language/move-vm/runtime/src/move_vm_adapter.rs:128:9
                           starcoin_vm_runtime::starcoin_vm::StarcoinVM::execute_package::hb3b9087dad7e9f5e
                               at /starcoin/vm/vm-runtime/src/starcoin_vm.rs:397:25
  13:     0x55aedf1c9fa0 - starcoin_vm_runtime::starcoin_vm::StarcoinVM::execute_user_transaction::hdbf2240b7e40a7f7
                               at /starcoin/vm/vm-runtime/src/starcoin_vm.rs:707:55
                           starcoin_vm_runtime::starcoin_vm::StarcoinVM::execute_block_transactions::h39c7ff680600361f
                               at /starcoin/vm/vm-runtime/src/starcoin_vm.rs:833:29
  14:     0x55aedf1bebe2 - starcoin_executor::executor::do_execute_block_transactions::hfd64308a1bdb2808
                               at /starcoin/executor/src/executor.rs:38:18
  15:     0x55aedf1b4c94 - starcoin_executor::executor::execute_block_transactions::hef785f6cb15bde4f
                               at /starcoin/executor/src/executor.rs:26:5
                           starcoin_executor::block_executor::block_execute::h56e6c9f632efbea1
                               at /starcoin/executor/src/block_executor.rs:36:9
  16:     0x55aedea9878b - starcoin_chain::chain::BlockChain::execute_block_and_save::h740bd3787368e347
                               at /starcoin/chain/src/chain.rs:386:13
  17:     0x55aedea9f28b - <starcoin_chain::chain::BlockChain as starcoin_chain_api::chain::ChainReader>::execute::hcdc2616284b754fb
                               at /starcoin/chain/src/chain.rs:754:9
  18:     0x55aedeaa1c24 - starcoin_chain::chain::BlockChain::apply_with_verifier::ha874caec2e1b81c1
                               at /starcoin/chain/src/chain.rs:337:30
                           <starcoin_chain::chain::BlockChain as starcoin_chain_api::chain::ChainWriter>::apply::h41f388414e78c8a5
                               at /starcoin/chain/src/chain.rs:911:9
  19:     0x55aede4b0f5a - starcoin_sync::tasks::block_sync_task::BlockCollector<N,H>::apply_block::h622fc2a38861a91d
                               at /starcoin/sync/src/tasks/block_sync_task.rs:229:13
                           <starcoin_sync::tasks::block_sync_task::BlockCollector<N,H> as stream_task::collector::TaskResultCollector<starcoin_sync::tasks::block_sync_task::SyncBlockData>>::collect::hfe7877c752706e4b
                               at /starcoin/sync/src/tasks/block_sync_task.rs:284:17
  20:     0x55aede450284 - stream_task::collector::FutureTaskSink<Item,Output>::new::{{closure}}::h31bce0fddeddd86e
                               at /starcoin/commons/stream-task/src/collector.rs:164:39
                           <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h658575a5eeb73be3
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/future/mod.rs:80:19
  21:     0x55aede45ed0e - <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::{{closure}}::hc4dff2c81766c722
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/builder.rs:199:17
                           async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}::ha9fb517206d85900
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/task_locals_wrapper.rs:60:13
                           std::thread::local::LocalKey<T>::try_with::h5b9f6a884d32d6c0
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/local.rs:272:16
                           std::thread::local::LocalKey<T>::with::h223acb3e18379429
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/local.rs:248:9
                           async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::habbc16ce9fa306a7
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/task_locals_wrapper.rs:55:9
                           <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::hddd376ef609c9c69
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/builder.rs:197:13
                           async_executor::Executor::spawn::{{closure}}::h8890e9183287dbfd
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.0/src/lib.rs:138:13
                           <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hfd03e1bfcc185267
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/future/mod.rs:80:19
  22:     0x55aede4226e6 - <core::pin::Pin<P> as core::future::future::Future>::poll::h3d25a6ea9d1ebd33
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/future/future.rs:119:9
                           async_task::raw::RawTask<F,T,S>::run::h3b1c42064644959d
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/raw.rs:489:20
  23:     0x55aedf0a4000 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h191f375b7ad3d5f4
  24:     0x55aedf0a4ee1 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hba45fcc27456f4ad
  25:     0x55aedf0a2758 - async_io::driver::block_on::hbf565014ead8bca3
  26:     0x55aedf09c97a - std::thread::local::LocalKey<T>::with::h6bb35e138613eaa6
  27:     0x55aedf09b76a - async_global_executor::threading::thread_main_loop::hbce59a93adf18c99
  28:     0x55aedf09c7c7 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbad39d38001c34c1
  29:     0x55aedf09d082 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc5f26f0b00cdeeea
  30:     0x55aedfef33ba - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h61144a2be4ee36d8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
                           <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcf5d395fdd120c17
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
                           std::sys::unix::thread::Thread::new::thread_start::hb5e40d3d934ebb7a
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
  31:     0x7fb01bb546db - start_thread
  32:     0x7fb01ca0571f - __clone
  33:                0x0 - <unknown>

**Comment by jolestar** [comment]
这个问题应该已经解决
