### ISSUE TITLE
ABI 以及  resource/event/code parser

### ISSUE THREAD

**Issue by lerencao** [starcoinorg/starcoin#2636]
提供机制，可以描述 ScriptFunction，Resource，Event，Module，方便应用层设计通用的 resource 以及 event 解析器，ScriptFunction 构造器。

应用场景描述：

1. 通过通用的方式将任意的 resource 以及 event 解析成 json 对象，然后展示，索引。
2. 提供一个浏览器输入表单，可以允许用户填写参数构造出 Transaction。

方案描述：

1. ScriptFunction 可以通过当前的 ScriptFunctionABI 描述，只是通过 CompiledModule 解析出的 ScriptFunctionABI 没有参数名。 
2. Resource/Event 是否需要定义一种 StructABI 来描述，还是直接使用现在的 FatStructType。
```rust
StructABI{
  name: String,
  module_name: ModuleId,
  fields: Vec<FieldABI>,
}
FieldABI {
  name: String,
  type_tag: TypeTag,
}
```
3. Module 感觉可以解析成多个 ScriptFunctionABI 来描述。
 
```rust
ModuleABI{
  module_name: String,
  script_functions: Vec<ScriptFunctionABI>,
}
```

接口设计：

1. contract.resolve_function(FunctionID)-> ScriptFunctionABI
2. contract.resolve_struct(StructTag) -> StructABI
3. contract.resolve_module(ModuleID) -> ModuleABI

现有接口改造：

1. contract.get_code  保持不变，但声明废弃
2. contract.get_resource 保持不变，但声明废弃
3. state.get_resource 新增，返回 resource bytes hex，以及通过 StructABI 解析后的 resource json object。可以通过参数控制是否解析 resource，默认为 false。
4. state.get_code 新增，返回 code bytes hex，和 contract.get_code 一致。

问题：

1.  Transaction payload 中的 ScriptFunction 接口输出时是否提供 ABI 自动解析？想不出好的输出方式，感觉可以暂时不考虑。另外 payload 是否需要输出成 json？
2. ContractEvent 是否提供 ABI 自动解析？这个担心有性能问题。

**Comment by lerencao** [comment]
ModuleABI 应该还包括 Vec<StructABI>.

**Comment by lerencao** [comment]
state.get_code 可以添加是否返回 module interface。

**Comment by jolestar** [comment]
#2659 初步实现了 resolve 相关的接口

**Comment by jolestar** [comment]
#2703 依赖于 ABI

**Comment by jolestar** [comment]
#2702 实现了 abi decoder

**Comment by lerencao** [comment]
closed now.
