### ISSUE TITLE
[stdlib] Dao unstack votes zero token failed.

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#2641]
```
public ( script ) fun unstake_vote<Token: copy + drop + store, Action: copy + drop + store>(
        signer: signer,
        proposer_address: address,
        proposal_id: u64,
    ) {
        let my_token = Dao::unstake_votes<Token, Action>(&signer, proposer_address, proposal_id);
        Account::deposit(Signer::address_of(&signer), my_token);
    }
```

这个方法中，unstake_votes 返回的 Token 有可能是 zero，直接 Account::deposit 会报错。deposit 之前需要判断一下是否为 zero。

思考：

deposit zero token 是不是不应该报错？deposit zero 并没有副作用，如果每次 deposit 前都检查一下是 zero 的话直接 Token::destroy_zero ，还不如在 deposit 方法内部 destroy_zero ？

**Comment by jolestar** [comment]
case:

https://explorer.starcoin.org/main/transactions/detail/0xcd9c7e8e79aa8e4176be40285b26a8ff7f30eccc60a431b7073a10bc779043c8
https://explorer.starcoin.org/main/transactions/detail/0xfc84130c39098eced755caaba797901a247debacf2a496d4f64d075f579e63bd

https://explorer.starcoin.org/main/address/0xc96e71bc3b1a7b40b1896253fb0895eb

**Comment by jolestar** [comment]
另外当前 revoke_vote 是一次性 revoke 所有的 token，是否应该支持设置数量？如果不支持设置数量，revoke_vote 之后是不是应该将 Vote 对象销毁掉。

**Comment by jolestar** [comment]
```
module {{sender}}::DaoVoteScripts {
    use 0x1::Dao;
    use 0x1::Token;
    use 0x1::Account;
    use 0x1::Signer;

    public ( script ) fun unstake_vote<Token: copy + drop + store, Action: copy + drop + store>(
        signer: signer,
        proposer_address: address,
        proposal_id: u64,
    ) {
        let my_token = Dao::unstake_votes<Token, Action>(&signer, proposer_address, proposal_id);
        if (Token::value(&my_token)==0){
            Token::destroy_zero(my_token);
        }else{
            Account::deposit(Signer::address_of(&signer), my_token);
        }
    }
}
```
如果遇到这个 bug，并且不能等待 stdlib 升级，可以先自己部署这样一个 module，然后调用该 module 的 unstake_vote 方法。

**Comment by Foorgoo** [comment]
mark~
