### ISSUE TITLE
建立连接订阅时新挖矿任务时，没有立即返回新任务

### ISSUE THREAD

**Issue by GXKe** [starcoinorg/starcoin#2646]
目前订阅新任务，是在链上爆块后触发新任务广播到每个订阅

但是在ws刚建立时，不回返任务，需要等待下次爆块时广播

在测试网场景下，没有其他算力爆块的情况下，矿池也不能获取到新任务，不能继续爆块

**Comment by jolestar** [comment]
这个问题已知，测试的时候可以把进程内 miner 也打开
