### ISSUE TITLE
[sync] sync task is interrupted by get block from local storage

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#2654]
2021-07-01T09:21:02.365206794+08:00 WARN - BlockConnector fail: Can not find block by number 753171, head block number: 753185, peer_id:PeerId(PeerId("12D3KooWM8dHyvKkMv7uaEWmWXWQGJYPyCUDLcqGFd8pB6BMjdST"))

2021-07-01T09:43:59.676420623+08:00 WARN - [sync] Sync task is interrupted by Can not find block by number 753171, head block number: 753185, cause:"Can not find block by number 753171, head block number: 753185"

the sync task is back to normal after restart the node.

the error is raise from chain/src/chain.rs 
```
fn epoch_uncles(&self) -> Result<HashMap<HashValue, MintedUncleNumber>>
```

**Comment by jolestar** [comment]
这个症状出现后，节点无法自行恢复，sync task 会一直出错一直重试。

按道理这个问题不应该出现，因为是从本地存储中获取数据。

**Comment by nkysg** [comment]
2021-10-25又发生这问题，日志保存在starcoin-7节点的debug-ysg目录

**Comment by nkysg** [comment]
目前我们max_total_wal_size设置为了1G, 感觉像是我们options.wal_bytes_per_sync 没有设置默认值为0，https://github.com/facebook/rocksdb/wiki/IO 参考这个链接， 这样会导致我们的wal写到很大，由操作系统把pagecache刷到磁盘，参考链接中也写道这个会影响查询性能。

https://github.com/facebook/rocksdb/wiki/Basic-Operations#purging-wal-files 这个链接是何时删除过期的wal,目前我们只修改wal_bytes_per_sync

**Comment by templexxx** [comment]
> 

看上去只要设置了 wal_bytes_per_sync  就可以控制每次 sync 的长度了，也就没有 burst I/O （以及超大 wal block 写入）的问题了？ @nkysg 是这样吗

**Comment by templexxx** [comment]
> 下面的都不对，目前我们采用了https://github.com/facebook/rocksdb/wiki/WAL-Performance 这个里面的sync方式， https://github.com/starcoinorg/starcoin/blob/master/storage/src/db_storage/mod.rs#L171
> 
> ```
> 目前我们max_total_wal_size设置为了1G, max_total_wal_size作用参考这个https://github.com/facebook/rocksdb/wiki/Write-Ahead-Log#dboptionsmax_total_wal_size, 感觉像是我们options.wal_bytes_per_sync 没有设置默认值为0，https://github.com/facebook/rocksdb/wiki/IO#range-sync 参考这个链接， 这样会导致我们的wal写到很大，由操作系统把pagecache刷到磁盘，参考链接中也写道这个会影响查询性能。
> 
> https://github.com/facebook/rocksdb/wiki/Basic-Operations#purging-wal-files 这个链接是何时删除过期的wal,
> 目前我们只修改wal_bytes_per_sync
> ```

看上去只要设置了 wal_bytes_per_sync  就可以控制每次 sync 的长度了，也就没有 burst I/O （以及超大 wal block 写入）的问题了？ @nkysg 是这样吗

**Comment by nkysg** [comment]
> > 下面的都不对，目前我们采用了https://github.com/facebook/rocksdb/wiki/WAL-Performance 这个里面的sync方式， https://github.com/starcoinorg/starcoin/blob/master/storage/src/db_storage/mod.rs#L171
> > ```
> > 目前我们max_total_wal_size设置为了1G, max_total_wal_size作用参考这个https://github.com/facebook/rocksdb/wiki/Write-Ahead-Log#dboptionsmax_total_wal_size, 感觉像是我们options.wal_bytes_per_sync 没有设置默认值为0，https://github.com/facebook/rocksdb/wiki/IO#range-sync 参考这个链接， 这样会导致我们的wal写到很大，由操作系统把pagecache刷到磁盘，参考链接中也写道这个会影响查询性能。
> > 
> > https://github.com/facebook/rocksdb/wiki/Basic-Operations#purging-wal-files 这个链接是何时删除过期的wal,
> > 目前我们只修改wal_bytes_per_sync
> > ```
> 
> 看上去只要设置了 wal_bytes_per_sync 就可以控制每次 sync 的长度了，也就没有 burst I/O （以及超大 wal block 写入）的问题了？ @nkysg 是这样吗

这个是因为我们缓存不一致的问题，这里我误导了，处理见这个 https://github.com/starcoinorg/starcoin/pull/3008
