### ISSUE TITLE
get_transaction_info 返回block_hash为叔块hash

### ISSUE THREAD

**Issue by GXKe** [starcoinorg/starcoin#2686]
0x87589aafccbd0e7b4a88ae49233eff96faa45b267fb90361dbd7026f1139b140

![image](https://user-images.githubusercontent.com/4132888/125012651-23cc2200-e09d-11eb-99c2-03d83e0a983a.png)

![image](https://user-images.githubusercontent.com/4132888/125013470-74904a80-e09e-11eb-8da2-74a305a3e92c.png)

![image](https://user-images.githubusercontent.com/4132888/125013497-8245d000-e09e-11eb-8c0f-b079fd7a8635.png)

**Comment by jolestar** [comment]
给一下这个节点上

```bash
chain get-txn-info 0x87589aafccbd0e7b4a88ae49233eff96faa45b267fb90361dbd7026f1139b140
chain get-block 890723 
```

的结果
