### ISSUE TITLE
[stdlib] Support auto accept token

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#2741]
当前用户要接受一个新的 Token，需要发起一个交易，调用 Account::do_accept_token 方法。

这个限制主要是因为：

Starcoin 的状态空间是分拆到具体用户的，用户需要在自己的状态空间创建一个 Balance<Token> 类型的容器，才能接受该 Token，而 Move 中的  move_to 指令是需要 signer，也就是说只能当前用户自己操作。

但这样也会带来许多用户体验上的难题，所以考虑设计一种可以自动 accept_token 的方案。

1. 定义一个新的 Resource 
```
struct AutoAcceptToken{
   accept: bool,
}
```
2. 链上创建用户时默认写入 AutoAcceptToken{accept: true}。
3. Account::deposit 方法中检测收款方账号的 AutoAcceptToken 设置，如果为 true，则自动通过 Account::create_signer 方法模拟收款用户，代为初始化用户的收款 Balance。
4. 用户可以发起交易设置 AutoAcceptToken 为 false，避免接受自己不愿意接受的 Token。

状态存储以及兼容性问题：

1. Token 所占用的状态空间只是一个 u128 的类型，使用的空间有限，很难造成用户的状态空间爆炸。
2. 链上已有用户，状态下不存在 AutoAcceptToken，默认为 false，需要用户手动设置 AutoAcceptToken（或者不存在识为 true ？）。

需要分析安全问题。

**Comment by lerencao** [comment]
looks ok

**Comment by lerencao** [comment]
closed in #2745
