### ISSUE TITLE
deploy contracts package dependency error

### ISSUE THREAD

**Issue by wh-antares** [starcoinorg/starcoin#2748]
There is a problem with the dependency processing when deploying   contracts..

I use `dev package` under the console to package it into a blob file. and run `dev deploy` txn dry run faild by  `MiscellaneousError`.

I have also tried to submit multiple contract files directly in submitTransaction, but the same dependency processing is problematic.

~The only solution is that I first deploy A and then deploy B, so that it will be deployed successfully.~

If i  **exchange file name** ,it will be success..

**It seems that the contracts are not reordered online, but are checked in the order of file names**

``` json
txn dry run failed
{
  "ok": {
    "type": "DryRun",
    "vm_status": {
      "Error": 1081
    },
    "output": {
      "events": [],
      "gas_used": "600",
      "status": "MiscellaneousError",
      "write_set": [`
``` 

``` rust
module A {

    public fun test_a(): u64 {
        1u64
    }
}

``` 
``` rust
module B {
    use 0x1::Signer;
    use address::A;


    struct Counter has key, store {
        value: u64,
    }

    public fun init(account: &signer) {
        move_to(account, Counter { value: 0 });
    }

    public fun incr(account: &signer) acquires Counter {
        let counter = borrow_global_mut<Counter>(Signer::address_of(account));
        counter.value = counter.value + A::test_a();
    }

    public(script) fun init_counter(account: signer) {
        Self::init(&account)
    }

    public(script) fun incr_counter(account: signer)  acquires Counter {
        Self::incr(&account)
    }
}

```

**Comment by lerencao** [comment]
latest version of starcoin fixed this. please check.
close this now. if situation still remains, please reopen this.
