### ISSUE TITLE
node panic

### ISSUE THREAD

**Issue by tiangong3624749** [starcoinorg/starcoin#2753]
2021-06-17T02:25:43.483567675+00:00 INFO - [network-p2p] receive notification from 12D3KooWShVxmvpoKKJszk4dBj4Ek6TJwTcQbQ8U5FVL7YxwcWoq /starcoin/block/1 1075
2021-06-17T02:25:45.889717043+00:00 ERROR - panic occurred:
2021-06-17T02:25:45.889989333+00:00 ERROR - details: panicked at 'removal index (is 287) should be < len (is 286)', library/alloc/src/vec/mod.rs:1349:13
2021-06-17T02:25:45.890992450+00:00 ERROR - backtrace:    0:     0x559ab6d43417 - backtrace::backtrace::trace::hacf1fe84a32f5ef2
   1:     0x559ab6d2fdf5 - backtrace::capture::Backtrace::new::h15b19b8be9133bec
   2:     0x559ab5037e5e - starcoin_node::crash_handler::handle_panic::h3e851ed7519c2d92
                               at /starcoin/node/src/crash_handler.rs:21:38
   3:     0x559ab5037dd9 - starcoin_node::crash_handler::setup_panic_handler::{{closure}}::hb45a38f6ce35d443
                               at /starcoin/node/src/crash_handler.rs:14:9
   4:     0x559ab6dfb5f6 - std::panicking::rust_panic_with_hook::h71e6a073d87de1f5
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   5:     0x559ab6dfb117 - std::panicking::begin_panic_handler::{{closure}}::hd549436f6bb6dbb8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
   6:     0x559ab6df8a4c - std::sys_common::backtrace::__rust_end_short_backtrace::h4e5f4b72b04174c3
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   7:     0x559ab6dfb079 - rust_begin_unwind
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   8:     0x559ab6e19c61 - core::panicking::panic_fmt::hcd56f7f635f62c74
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   9:     0x559ab6e14116 - alloc::vec::Vec<T,A>::remove::assert_failed::h9cc7fd73decf979c
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/vec/mod.rs:1349:13
  10:     0x559ab6120f69 - alloc::vec::Vec<T,A>::remove::hd7d35fa94ce88fed
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/vec/mod.rs:1354:13
                           move_vm_runtime::loader::ModuleCache::remove::h6aff4730df715439
                               at /usr/local/cargo/git/checkouts/diem-5aa6d6b8b0487904/6e1cc95/language/move-vm/runtime/src/loader.rs:174:25
                           move_vm_runtime::loader::Loader::unload_module::h4c994738956217e2
                               at /usr/local/cargo/git/checkouts/diem-5aa6d6b8b0487904/6e1cc95/language/move-vm/runtime/src/loader.rs:989:9
  11:     0x559ab60f4d31 - move_vm_runtime::runtime::VMRuntime::publish_module::ha988c000b940ee42
                               at /usr/local/cargo/git/checkouts/diem-5aa6d6b8b0487904/6e1cc95/language/move-vm/runtime/src/runtime.rs:93:13
  12:     0x559ab60dec14 - move_vm_runtime::session::Session<R>::publish_module::h28bd31dc5b79fa12
                               at /usr/local/cargo/git/checkouts/diem-5aa6d6b8b0487904/6e1cc95/language/move-vm/runtime/src/session.rs:161:9
                           move_vm_runtime::move_vm_adapter::SessionAdapter<R>::publish_module::h5ac83e9b6b66d599
                               at /usr/local/cargo/git/checkouts/diem-5aa6d6b8b0487904/6e1cc95/language/move-vm/runtime/src/move_vm_adapter.rs:128:9
                           starcoin_vm_runtime::starcoin_vm::StarcoinVM::execute_package::hf5b1def9e7d36bc7
                               at /starcoin/vm/vm-runtime/src/starcoin_vm.rs:397:25
  13:     0x559ab60e2210 - starcoin_vm_runtime::starcoin_vm::StarcoinVM::execute_user_transaction::ha525927ce01c655a
                               at /starcoin/vm/vm-runtime/src/starcoin_vm.rs:707:55
                           starcoin_vm_runtime::starcoin_vm::StarcoinVM::execute_block_transactions::h3821d51e5830bf06
                               at /starcoin/vm/vm-runtime/src/starcoin_vm.rs:833:29
  14:     0x559ab60cdc22 - starcoin_executor::executor::do_execute_block_transactions::h29998e97518d994a
                               at /starcoin/executor/src/executor.rs:38:18
  15:     0x559ab60cdb09 - starcoin_executor::executor::execute_block_transactions::hf3a061ffa83ce081
                               at /starcoin/executor/src/executor.rs:26:5
  16:     0x559ab59d8437 - starcoin_open_block::OpenedBlock::push_txns::hcefa05b071da67ef
  17:     0x559ab55b50a6 - starcoin_miner::create_block_template::Inner<P>::create_block_template::h12999f2655fd0b3c
                               at /starcoin/miner/src/create_block_template/mod.rs:312:29
                           <starcoin_miner::create_block_template::CreateBlockTemplateService as starcoin_service_registry::service::ServiceHandler<starcoin_miner::create_block_template::CreateBlockTemplateService,starcoin_miner::create_block_template::CreateBlockTemplateRequest>>::handle::h531d33e2691a070f
                               at /starcoin/miner/src/create_block_template/mod.rs:124:24
  18:     0x559ab55c8924 - <starcoin_service_registry::handler_proxy::ServiceHandlerProxy<S> as starcoin_service_registry::service::ServiceHandler<S,R>>::handle::hdaff73da02e3dc91
                               at /starcoin/commons/service-registry/src/handler_proxy.rs:117:9
                           <starcoin_service_registry::service_actor::ServiceActor<S> as actix::handler::Handler<starcoin_service_registry::service_actor::ServiceMessage<R>>>::handle::h5f8e430a0a7fc60b
                               at /starcoin/commons/service-registry/src/service_actor.rs:153:13
  19:     0x559ab55b7a51 - <actix::address::envelope::SyncEnvelopeProxy<A,M> as actix::address::envelope::EnvelopeProxy>::handle::h2ff31044650394e9
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.10.0/src/address/envelope.rs:112:23
  20:     0x559ab50f5469 - <actix::address::envelope::Envelope<A> as actix::address::envelope::EnvelopeProxy>::handle::ha01d16b638374816
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.10.0/src/address/envelope.rs:71:9
                           actix::mailbox::Mailbox<A>::poll::h2c5c80b423669aa2
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.10.0/src/mailbox.rs:101:25
  21:     0x559ab518b180 - <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll::had7330660a387799
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.10.0/src/contextimpl.rs:375:13
  22:     0x559ab51ba28a - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::h38b1ef1ff90783cf
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:173:17
                           tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h1572f97ca08dfc47
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/loom/std/unsafe_cell.rs:14:9
                           tokio::runtime::task::core::Core<T,S>::poll::ha802a6676ae49790
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:158:13
                           tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}::hc5929a9ee630a7c4
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:107:27
                           core::ops::function::FnOnce::call_once::hd39ddbcc4372171b
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:227:5
                           <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h3c83da0bfc08d48e
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:344:9
  23:     0x559ab5226a7c - std::panicking::try::do_call::h371a3b6307d8c197
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:379:40
                           std::panicking::try::h308f67ce4c22c092
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:343:19
                           std::panic::catch_unwind::h09c784d4152835c5
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:431:14
                           tokio::runtime::task::harness::Harness<T,S>::poll::h89cb90660c58bf45
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:89:19
                           tokio::runtime::task::raw::poll::h3d2968c62acecd7e
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:104:5
  24:     0x559ab66fb323 - std::thread::local::LocalKey<T>::with::h0a3417616d27bdde
  25:     0x559ab66f9927 - tokio::task::local::LocalSet::tick::hf3547f267adfac2a
  26:     0x559ab66e6866 - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::hff03c6a3327f671c
  27:     0x559ab66d2717 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h6e281b869a58de4a
  28:     0x559ab66ccbc2 - std::thread::local::LocalKey<T>::with::hf871654ca2c7ba97
  29:     0x559ab66e60b5 - tokio::macros::scoped_tls::ScopedKey<T>::set::hbde7080add94086d
  30:     0x559ab66d246a - tokio::runtime::context::enter::hf713f9a1aafa355c
  31:     0x559ab66d0301 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc1fd04b118d698f7
  32:     0x559ab66d91e3 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h029b6f372783e5b5
  33:     0x559ab6e00aaa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h61144a2be4ee36d8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
                           <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcf5d395fdd120c17
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
                           std::sys::unix::thread::Thread::new::thread_start::hb5e40d3d934ebb7a
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
  34:     0x7f8d24b196db - start_thread
  35:     0x7f8d259ca71f - __clone
  36:                0x0 - <unknown>

**Comment by jolestar** [comment]
这个应该是旧版本硬分叉的那个 bug，确认一下 node 的版本
