### ISSUE TITLE
stdlib 的 Oracle. init_data_source 方法是否可以考虑去掉 init_value 参数？

### ISSUE THREAD

**Issue by wubuku** [starcoinorg/starcoin#2759]
vm/stdlib/modules/Oracle.move

`    public fun init_data_source<OracleT:  copy+store+drop, Info: copy+store+drop, ValueT: copy+store+drop>(signer: &signer, init_value: ValueT) acquires OracleInfo{`
 
对于价格 Oracle 来说很可能实际操作是这样的：register_oracle 是一次性的操作，init_data_source 对于一个数据源来说也是一次性的操作，这些操作可能通过 console 手动做一下就可以了，不太值得写程序（去检查是否已经注册/初始化，如果没有就做响应的操作）；然后是启动后台服务去更新 token 的价格。在 init_data_source 的时候，虽然可以手动去查询 token 的价格后填入，但是 token 比较多的时候这个操作就麻烦了，而这时候如果是嫌麻烦随便填入一个价格可能会带来资金风险。

**Comment by jolestar** [comment]
如果 init_value 去掉，DataRecord 中的 value 就需要设置成 Option，read 也需要改成返回 Option，会增加使用的复杂度。

可以考虑下，这个复杂度是让 datasource 提供方承担还是使用者承担。

**Comment by wubuku** [comment]
从确定“会有一个数据源”到“数据源可以提供价格”之间可能会有时间差。或者可以先在脚本里面增加 is_data_source_initiailzed 方法，返回是否数据源已经初始化。这样数据源那边的后台服务在启动之后，第一次更新价格时，可以先检测一下是否之前已经做过初始化的动作，如果没有，就先初始化一下。

**Comment by jolestar** [comment]
is_data_source_initiailzed 这个好加，也可以通过取 OracleInfo 是否存在来判断。

**Comment by jolestar** [comment]
可以一起看看 Oracle 还有什么需要增加的。另外有需要 @wubuku 直接修改了提 pr 也行。

**Comment by wubuku** [comment]
还是加一个方法来隐藏实现的细节好一些。暂时没有需要增加更多方法。
