### ISSUE TITLE
chain get-block 1439835  返回的像是叔块

### ISSUE THREAD

**Issue by GXKe** [starcoinorg/starcoin#2785]
![image](https://user-images.githubusercontent.com/4132888/129298202-b8ac2d51-9050-4483-a9e4-b3593413ad58.png)

0x9593f6846bcae0aab302e0316987ee74a591ac10dfa47115ad3a1bbf455d0e7f

![image](https://user-images.githubusercontent.com/4132888/129298231-5d70d676-a3fa-49cf-aba4-312101201913.png)
https://explorer.starcoin.org/main/transactions/detail/0x9593f6846bcae0aab302e0316987ee74a591ac10dfa47115ad3a1bbf455d0e7f

**Comment by GXKe** [comment]
starcoin 1.4.0 (build:v1.4.2)

**Comment by ssyuan** [comment]
浏览器的数据分叉，已经修复
