### ISSUE TITLE
BCS serialize  and deserialize  not the same protocol structure

### ISSUE THREAD

**Issue by wh-antares** [starcoinorg/starcoin#2790]
when we submit  a hex  hex_transaction ,we need  serialize a string to vector<u8> ,this is  a structure to move lang.
example:
if we serialize a string  `STC`  ,hex is `0x03535443` .
but when we call the json rpc whit the param decode=true ,we got a result is `0x535443`.
its not the same result from `move lang`  vecotr<u8>,looks like is `Rust` str .
In the definition in the bcs structure, the array needs to have a length, so   the length definition is missing in the returned result.

we can see the result from this curl example.
```
curl --location --request POST 'https://barnard-seed.starcoin.org' \
--header 'Content-Type: application/json' \
--data-raw '{
 "id":101, 
 "jsonrpc":"2.0", 
 "method":"contract.call_v2", 
 "params":[ {"function_id":"0x1::Token::token_code","type_args":["0x1::STC::STC"],"args":[]}]
}'
```

**Comment by lerencao** [comment]
closed as discussed in feishu.
