### ISSUE TITLE
subscribe 接口返回数据不一致

### ISSUE THREAD

**Issue by fanngyuan** [starcoinorg/starcoin#2810]
订阅event的时候，如果使用EventFilter 参数，返回的数据跟预期一致，比如客户端订阅了send/recv event，返回数据：
EventNotificationResult{blockHash='0x368d91e955822ddea328dcca0953a8ce29194fe47fcb866c237c0f54c7f1dfae', blockNumber='6', transactionHash='0x00aad38f1b9c958d2756d4b94cf39eb5fa17fa8865336d435e01005fa0a6bbeb', transactionIndex=1, data='0x00c2eb0b00000000000000000000000000000000000000000000000000000001035354430353544300', typeTag='0x00000000000000000000000000000001::Account::DepositEvent', eventKey='0x0100000000000000b75994d55eae88219dc57e7e62a11bc0', eventSeqNumber='4'}

如果使用EventParam 参数，其中filter字段与之前相同，decode 设置为true/false 都会出现返回没有订阅的 event：
EventNotificationResult{blockHash='0x0403a677a91b52d393cd1e0277bda323b9b17a32439fbd2e5f59616b2b95d7ba', blockNumber='5', transactionHash='0xb8f6224586218021b98d731f5896cd19488c962de429aed703ebb319693a8626', transactionIndex=1, data='0x00c2eb0b00000000000000000000000000000000000000000000000000000001035354430353544300', typeTag='0x00000000000000000000000000000001::Account::WithdrawEvent', eventKey='0x0000000000000000a76b896725a088beafb470fe93251c4d', eventSeqNumber='3'}
EventNotificationResult{blockHash='0x0403a677a91b52d393cd1e0277bda323b9b17a32439fbd2e5f59616b2b95d7ba', blockNumber='5', transactionHash='0xb8f6224586218021b98d731f5896cd19488c962de429aed703ebb319693a8626', transactionIndex=1, data='0x00c2eb0b00000000000000000000000000000000000000000000000000000001035354430353544300', typeTag='0x00000000000000000000000000000001::Account::DepositEvent', eventKey='0x0100000000000000b75994d55eae88219dc57e7e62a11bc0', eventSeqNumber='3'}
EventNotificationResult{blockHash='0x0403a677a91b52d393cd1e0277bda323b9b17a32439fbd2e5f59616b2b95d7ba', blockNumber='5', transactionHash='0x70f1cd728d96d8d67dbb5b36e810ff7f5adfb7c39693c7e066cbc91a14beef78', transactionIndex=0, data='0x0500000000000000a76b896725a088beafb470fe93251c4dafa40000000000000000000000000000', typeTag='0x00000000000000000000000000000001::Block::NewBlockEvent', eventKey='0x040000000000000000000000000000000000000000000001', eventSeqNumber='4'}
EventNotificationResult{blockHash='0x0403a677a91b52d393cd1e0277bda323b9b17a32439fbd2e5f59616b2b95d7ba', blockNumber='5', transactionHash='0x70f1cd728d96d8d67dbb5b36e810ff7f5adfb7c39693c7e066cbc91a14beef78', transactionIndex=0, data='0x00e40b54020000000000000000000000', typeTag='0x00000000000000000000000000000001::Treasury::WithdrawEvent', eventKey='0x100000000000000000000000000000000000000000000001', eventSeqNumber='4'}
EventNotificationResult{blockHash='0x0403a677a91b52d393cd1e0277bda323b9b17a32439fbd2e5f59616b2b95d7ba', blockNumber='5', transactionHash='0x70f1cd728d96d8d67dbb5b36e810ff7f5adfb7c39693c7e066cbc91a14beef78', transactionIndex=0, data='0xd9b70d5402000000000000000000000000000000000000000000000000000001035354430353544300', typeTag='0x00000000000000000000000000000001::Account::DepositEvent', eventKey='0x0100000000000000a76b896725a088beafb470fe93251c4d', eventSeqNumber='4'}
EventNotificationResult{blockHash='0x0403a677a91b52d393cd1e0277bda323b9b17a32439fbd2e5f59616b2b95d7ba', blockNumber='5', transactionHash='0x70f1cd728d96d8d67dbb5b36e810ff7f5adfb7c39693c7e066cbc91a14beef78', transactionIndex=0, data='0x040000000000000000e40b54020000000000000000000000d9d30100000000000000000000000000a76b896725a088beafb470fe93251c4d', typeTag='0x00000000000000000000000000000001::BlockReward::BlockRewardEvent', eventKey='0x0d0000000000000000000000000000000000000000000001', eventSeqNumber='3'}

**Comment by lerencao** [comment]
你的 filter 是嵌套在 param 里面传的？
不用嵌套，对外json 接口，相比之前，只是加了个 decode 参数。

```  rust
#[derive(Debug, PartialEq, Clone, Serialize, Deserialize, Eq, Hash)]
pub struct EventParams {
    #[serde(flatten)]
    pub filter: EventFilter,
    #[serde(default)]
    pub decode: bool,
}

```
