### ISSUE TITLE
move functional-test命令无法使用

### ISSUE THREAD

**Issue by Ultron42** [starcoinorg/starcoin#2927]
本地功能测试move functional-test命令报错
流程：
1.最开始使用v1.5.1，没有测试move functional-test命令，其他命令都可以正常使用
2.更新升级v1.6.0，测试move functional-test命令报错
3.删除本地包，使用v1.7.0，测试move functional-test命令报错
截图：
![image](https://user-images.githubusercontent.com/91652355/135393575-48850f81-e837-494a-bc75-bf4766917b22.png)
![image](https://user-images.githubusercontent.com/91652355/135393603-a37bc467-d329-49b2-b716-3d0c91b9a44b.png)
![image](https://user-images.githubusercontent.com/91652355/135393620-5ed6c720-222f-4877-834e-8747a7090ff6.png)

**Comment by Ultron42** [comment]
**代码：my_test.move**

//! account: alice, 10000000000000, 77
//! account: bob, 0x3
//! account: tom,10000000000

//! block-prologue
//! author: alice
//! block-number: 1
//! block-time: 10000

//! new-transaction
//! sender:alice
//! args: 10u64
//! max-gas: 7700000
//! sequence-number:77
//! gas-price: 1

script {
    use 0x3::MyMoney;
    use 0x1::Signer;
    use 0x1::Debug;
    fun main(account: signer, expected: u64){
        MyMoney::init0(&account);
        Debug::print<u64>(666);
        assert(MyMoney::get_money(Signer::address_of(&account)) == expected, 100);
}

//! block-prologue
//! author: alice
//! block-number: 2
//! block-time: 20000

**Comment by lerencao** [comment]
谢谢反馈。麻烦 `MoMoney.move` 的代码也贴一下。

**Comment by Ultron42** [comment]
> 谢谢反馈。麻烦 `MoMoney.move` 的代码也贴一下。

address 0x3{
module MyMoney{

    const MAX: u64 = 666;
    const ZERO: u64 = 0;

    use 0x1::Signer;

    struct MyMoney has key, store{
        value: u64
    }

    public fun genesis(account: &signer){
        if(!exists<MyMoney>(Signer::address_of(account))){
            move_to<MyMoney>(account, MyMoney{value: MAX})
        }
    }

    public fun init0(account: &signer){
        if(!exists<MyMoney>(Signer::address_of(account))){
            move_to<MyMoney>(account, MyMoney{value: ZERO})
        }
    }

    public fun get_money(addr: address) : u64 acquires MyMoney{
        borrow_global<MyMoney>(addr).value
    }

    // must public function
    public fun modify_money(account: &signer, i: u64) acquires MyMoney{
        borrow_global_mut<MyMoney>(Signer::address_of(account)).value = i;
    }

    public fun incr_money(account: &signer, i: u64) acquires MyMoney{
        let cur = get_money(Signer::address_of(account));
        modify_money(account, cur+i);
    }

    public fun decr_money(account: &signer, i: u64) acquires MyMoney{
        let cur = get_money(Signer::address_of(account));
        assert(cur>=i, 6);
        modify_money(account, cur-i);
    }

    public fun trans_money(a1: &signer, a2: &signer, i: u64) acquires MyMoney{
        let a1_cur = get_money(Signer::address_of(a1));
        assert(a1_cur>=i, 6);
        decr_money(a1, i);
        incr_money(a2, i);
    }

}
}

**Comment by Ultron42** [comment]
切换到1.5.1和1.5.0都不行，怀疑是环境没配好。。

**Comment by Ultron42** [comment]
$ rustc -V
rustc 1.55.0 (c8dfcfe04 2021-09-06)
$ cargo -V
cargo 1.55.0 (32da73ab1 2021-08-23)

**Comment by Ultron42** [comment]
$ move functional-test

running 1 tests
thread 'functional-test::my_test.move' panicked at 'called `Result::unwrap()` on an `Err` value: Error { depth: 0, inner: Io { path: Some("/Users/runner/work/starcoin/starcoin/vm/stdlib/modules"), err: Os { code: 2, kind: NotFound, message: "No such file or directory" } } }', /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:150:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test functional-test::my_test.move ... FAILED

failures:
    functional-test::my_test.move

test result: FAILED. 0 passed; 1 failed; 0 filtered out

报错是这个，但是 /Users/runner/work/starcoin/starcoin/vm/stdlib/modules 并不是我本地的路径
