### ISSUE TITLE
[statedb] Statedb cache optimize

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#299]
优化 statedb 的缓存使用

**Comment by jolestar** [comment]
#302

**Comment by ssyuan** [comment]
整理需求：
1、size计算接口：
    每次apply writeset，需要返回当前状态增减的字节数；
    每棵树本身记录整个树当前的总字节数，作为一个字段保存；
2、ChainStateDB本身记录update，这样commit判断是否更新，就不用进入每棵树判断；
3、ChainStateWriter 重构set、apply_write_set方法，统一一个write_set批量方法；
4、构建测试场景验证当前AccountState的两个root_hash是否在没flush之前是否有bug
