### ISSUE TITLE
[storage] provide a way to export and import chain database

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#2997]
当前新启动一个节点后同步数据较慢，可以考虑提供一种导入导出数据库的方式，便于快速搭建节点。

### 方法1: 只提供区块导入导出

1. 可指定高度范围打包导出区块
2. 可直接导入打包的区块，导入时可以跳过区块难度校验。

优点：实现比较简单。
缺点：所有区块需要重新执行，不能节省执行时间。

### 方法2: 提供区块，交易以及状态树数据库的快照功能

1. 指定高度导出快照。
2. 导入快照后继续执行后面的区块。

优点：导入速度快。
缺点：实现比较复杂，通过这种方式搭建的节点没有历史状态。

**Comment by nkysg** [comment]
区块导入导出
https://github.com/starcoinorg/starcoin/pull/3017

快照功能
https://github.com/starcoinorg/starcoin/pull/3291
https://github.com/starcoinorg/starcoin/pull/3294
