### ISSUE TITLE
测试 native-u256 分支时，move publish 会涉及到 dep 路径下的文件，导致 modul_address_does_not_match_sender 错误

### ISSUE THREAD

**Issue by 6543ngc** [starcoinorg/starcoin#3045]
#3032 
@lerencao 
使用 native-u256 分支进行 move-publish 时，由于 dep 路径下有地址不一致的模块导致报错
![image](https://user-images.githubusercontent.com/92702228/143255448-708f28ee-bc56-4dab-bbaf-13768fbd1be1.png)

使用 move v1.7.0 运行 move publish 不会报错，表现正常

**Comment by jolestar** [comment]
现在 src 下面不能放 deps 目录吧 @lerencao

**Comment by lerencao** [comment]
用 move publish --ignore-breaking-changes 试试。

**Comment by lerencao** [comment]
closed as disscussed.
