### ISSUE TITLE
Wrong ERROR prompt while forgotten use

### ISSUE THREAD

**Issue by welbon** [starcoinorg/starcoin#3075]
有时在引用未use的模块时候并不提示未定义模块，而是提示无法引用返回的值，如下图，场景是TokenSwapConfig 调用函数的时候提示返回值无法引用而不是提示缺失模块

![image](https://user-images.githubusercontent.com/2261238/145352090-9a14c49d-adad-4f3c-8414-8525a75d8e45.png)

**Comment by welbon** [comment]
顺序不对，应该是未定义模块的错误信息在前面

**Comment by lerencao** [comment]
Yeah, that's a problem. But wont fix in starcoin.
Maybe you can fire the issue in diem repo.
