### ISSUE TITLE
Have some problem sync a node

### ISSUE THREAD

**Issue by 6543ngc** [starcoinorg/starcoin#3098]
I want to sync a node as my dev enviroment, but have no lucky here whether sync main net, proxima or halley.
It says that:
![image](https://user-images.githubusercontent.com/92702228/146508658-38055d79-175f-4b95-b62a-ca81c4643576.png)
My starcoin version is:
![image](https://user-images.githubusercontent.com/92702228/146508749-ae7aa862-3b9a-401d-a67a-4a03ffc74cb1.png)

**Comment by jolestar** [comment]
No peers, see your startup log. 
please give your command line arguments.

**Comment by 6543ngc** [comment]
It finally found my os enviroment not work well. when I switch to mac, it's work fine, and now I have proxima/barnard node, main net in the way.
