### ISSUE TITLE
[wallet] "deploy" doesn't work，STORAGE_ERROR

### ISSUE THREAD

**Issue by guangyuz** [starcoinorg/starcoin#310]
step to reproduce:
1. 启动dev环境
2.创建新用户并transfer一定数量coins给它
3.编译test.move
wallet compile -o /Users/guangyu/work/project/starcoin/demos -f /Users/guangyu/work/project/starcoin/demos/my_token/module/test.move -s 0x.....
4.部署test.mv
wallet deploy -f /Users/guangyu/work/project/stargate/starcoin/demos/test.mv -g 10000
5.wallet show xxx

test.move:
module MyToken {
    struct T { }
    public fun issue() {
    }
}

**Comment by guangyuz** [comment]
分析：
按照上面提供的复现方法 "wallet show" report internal_error for: Missing node at HashValue
按照早先使用的复现方法，也就是用wallet的default账号deploy，报错：[VM] Error getting data from storage for AccessPath { address: 734994d221f677f2144fc0db3053c610, path: 01563aa5f6fe21fef8a41bf056cdac846f0574927c8311084a913f291606a92bd2 }，[VM] (BorrowGlobal) Error reading data for AccessPath { address: 734994d221f677f2144fc0db3053c610, type: Resource, hash: "563aa5f6fe21fef8a41bf056cdac846f0574927c8311084a913f291606a92bd2", suffix: "" } : VMStatus { major_status: STORAGE_ERROR, sub_status: None, message: None }

进一步打印了error，和上面的复现方法结果相同，也是报Missing node at HashValue(25482b9f050fc45ecb04c664ca46c6a11aa3159b436b6e035147085f402513fd)

在log中搜索该HashValue，没有发现其它搜索结果

**Comment by guangyuz** [comment]
访问出错的resource的确是写入state了：
<img width="1428" alt="屏幕快照 2020-04-23 下午11 44 20" src="https://user-images.githubusercontent.com/13956325/80119861-d6a98080-85bc-11ea-85ef-45838429cc88.png">

**Comment by lerencao** [comment]
closed in #318
