### ISSUE TITLE
Update the database snapshot with a scheduled task

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#3102]
Update the database snapshot with a scheduled task

定时更新 [import_net_block.sh](https://github.com/starcoinorg/starcoin/blob/master/scripts/import_net_block.sh) 的数据库快照, 确保每个网络的快照都正确( halley 和 proxiam 会重置 genesis)

**Comment by yourmoonlight** [comment]
https://github.com/starcoinorg/starcoin/pull/3360
https://github.com/starcoinorg/starcoin/pull/3374
