### ISSUE TITLE
Get a problem when I sync main net with the import_net_block.sh scripts.

### ISSUE THREAD

**Issue by 6543ngc** [starcoinorg/starcoin#3116]
I'm syncing my main net in a Mac,it's working good import the first three .csv file, but the fourth one gave me a error here.
My starcoin version is: starcoin 1.9.0-rc.2 (build:v1.9.0-rc.2)

(base) ➜  scripts git:(master) ✗ ./import_net_block.sh main ../../main
main block_list.csv exists. use it
main block_1_500000.csv exists. use it
file block_1_500000.csv has apply
main block_500001_1000000.csv exists. use it
file block_500001_1000000.csv has apply
main block_1000001_1500000.csv exists. use it
file block_1000001_1500000.csv has apply
main block_1500001_2000000.csv exists. use it
current number 1500000, import [1500001,2000000] block number
load blocks from file use time: 5451
Error: Verify block header failed: Invalid block: Parent id mismatch, expect:0x3a0f166281adf33e15a89eef3cdbceefd68c8b13eb01753ef60ca3bdfae33bd1, got: 0x793f5c59a19a68cc71d733ea8cead49589d38b6aa4babfbaa6c39dc45268d67f, number:1500001.
apply-block main block_1500001_2000000.csv fail

**Comment by nkysg** [comment]
in the import_net_block.sh path, run `rm block*csv` command and retry。 may be there are other net block_1500001_2000000.csv.

**Comment by 6543ngc** [comment]
oooh! That's correct! I removed all the block file, and it's importing now! Maybe there have some old file in my path.
thx guys
