### ISSUE TITLE
[dev] Support windows develop enviroment 

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#3126]
### Requirements

- [x] Provider a script to init windows dev environment.
- [x] Try to fix some build errors on windows.
- [x] Run ci on windows environment.
- [x] #3131 
- [x] #3330

**Comment by LemonHX** [comment]
move-cli compile pass with migrate to crossterm
diem depends on rocksdb has dep bitflags v1.2 but tui 0.17 requires v1.3

**Comment by LemonHX** [comment]
[ ] try to resolve dependency problem

**Comment by LemonHX** [comment]
4 WIP reviewd

**Comment by LemonHX** [comment]
3 Powershell done

**Comment by jolestar** [comment]
1,2,3,4 finished, 5 tracked by #3330
