### ISSUE TITLE
Compile example contracts failed on Windows

### ISSUE THREAD

**Issue by zhutoulala** [starcoinorg/starcoin#3130]
I was able to do a local dev build of starcoin on Windows 10, but running into below error when following the tutorial to compile example contracts. Perhaps due to the different line ending? 
```
starcoin% dev compile -o examples examples
[0m[1m[38;5;9merror[E01001][0m[1m: invalid character[0m
  [0m[36m┌─[0m C:\Users\peter\AppData\Local\Temp\e5f468ac479d3806f90bbd40ac032011\Account.move:1:14
  [0m[36m│[0m
[0m[36m1[0m [0m[36m│[0m address 0x1 {
' found when reading file. Only ASCII printable characters, tabs (\t), and line endings (\n) are permitted.[0m

[0m[1m[38;5;9merror[E01001][0m[1m: invalid character[0m
  [0m[36m┌─[0m C:\Users\peter\AppData\Local\Temp\e5f468ac479d3806f90bbd40ac032011\AccountScripts.move:1:14
  [0m[36m│[0m
[0m[36m1[0m [0m[36m│[0m address 0x1 {
' found when reading file. Only ASCII printable characters, tabs (\t), and line endings (\n) are permitted.[0m

[0m[1m[38;5;9merror[E01001][0m[1m: invalid character[0m
  [0m[36m┌─[0m C:\Users\peter\AppData\Local\Temp\e5f468ac479d3806f90bbd40ac032011\Authenticator.move:1:1
  [0m[36m│[0m
[0m[36m1[0m [0m[36m│[0m
' found when reading file. Only ASCII printable characters, tabs (\t), and line endings (\n) are permitted.[0m
...
```

**Comment by jolestar** [comment]
Maybe the windows file encode problem, @welbon did you solve the same problem?

**Comment by jolestar** [comment]
We need to support Move windows develop environment. #3131

**Comment by zhutoulala** [comment]
The problem is solved by using `dos2unix` to convert all move files under stdlib folder and example folder. I guess the compiler could add such conversation when reading move files on Windows.

**Comment by zhutoulala** [comment]
Just created a small PR https://github.com/starcoinorg/starcoin/pull/3135 for this issue. Fairly new to Rust, kindly let me know if anything needs to be changed

**Comment by yubing744** [comment]
@jolestar Can help sync the latest code from https://github.com/move-language/move to https://github.com/starcoinorg/move

**Comment by jolestar** [comment]
> @jolestar Can help sync the latest code from https://github.com/move-language/move to https://github.com/starcoinorg/move

@yubing744 I release a alpha version https://github.com/starcoinorg/starcoin/releases/tag/v1.11.8-alpha

**Comment by yubing744** [comment]
I tested v1.11.8-alpha, found new error:

![image](https://user-images.githubusercontent.com/1449069/167275034-eb718933-170f-4aec-b186-5f0a8f2f3a6c.png)

**Comment by yubing744** [comment]
The bad case is \t\r\n

![image](https://user-images.githubusercontent.com/1449069/167275061-48f0b577-5742-422b-a3a1-b10f7d4fa827.png)

**Comment by jolestar** [comment]
> The bad case is \t\r\n
> 
> ![image](https://user-images.githubusercontent.com/1449069/167275061-48f0b577-5742-422b-a3a1-b10f7d4fa827.png)

Does we just need to fix the examples?

**Comment by yubing744** [comment]
> > The bad case is \t\r\n
> > ![image](https://user-images.githubusercontent.com/1449069/167275061-48f0b577-5742-422b-a3a1-b10f7d4fa827.png)
> 
> Does we just need to fix the examples?

No, I submited a new [PR](https://github.com/move-language/move/pull/116) to handle this.

**Comment by yubing744** [comment]
@jolestar The [PR](https://github.com/move-language/move/pull/116) has been merged, can help sync the latest code from https://github.com/move-language/move to https://github.com/starcoinorg/move again.

**Comment by jolestar** [comment]
> @jolestar The [PR](https://github.com/move-language/move/pull/116) has been merged, can help sync the latest code from https://github.com/move-language/move to https://github.com/starcoinorg/move again.

release a new alpha version https://github.com/starcoinorg/starcoin/releases/tag/v1.11.9-alpha

**Comment by yubing744** [comment]
> > @jolestar The [PR](https://github.com/move-language/move/pull/116) has been merged, can help sync the latest code from https://github.com/move-language/move to https://github.com/starcoinorg/move again.
> 
> release a new alpha version https://github.com/starcoinorg/starcoin/releases/tag/v1.11.9-alpha

I tested v1.11.9-alpha and the move file is now compatible with both LF and CRLF line breaks, but there are two other issues:
1. There is no environment variable HOME by default on the Windows platform, and executing mpm package build will prompt an error that the HOME environment variable cannot be found.
![image](https://user-images.githubusercontent.com/1449069/167969028-763dc252-c02b-475f-bee4-b0a424c5cabf.png)

2. Executing the integration test on the Windows platform will cause the verification failure due to the newline of the exp file being replaced by CRLF
![image](https://user-images.githubusercontent.com/1449069/167969532-19d92e73-d780-42bc-af0c-836f46a625cc.png)

I have raised two issues:
https://github.com/starcoinorg/starcoin/issues/3400
https://github.com/starcoinorg/starcoin/issues/3401

**Comment by jolestar** [comment]
resolved
