### ISSUE TITLE
0x1::Config `ConfigValue` parameter properties restricted external asset properties

### ISSUE THREAD

**Issue by 9191stc** [starcoinorg/starcoin#3147]
```
struct Config<ConfigValue: copy + drop + store> has key { payload: ConfigValue }
```

Reference above declaration, You need set `TokenType` has `copy + drop + store` attribute if store `TokenType`. Then you need set the same attribute for the `TokenType` parameter on the call stack. Is there any way to be compatible with looser attributes such as `store`, or change `struct Config<ConfigValue: copy + drop + store>` to `struct Config<ConfigValue: store>`

**Comment by jolestar** [comment]
We expect the `ConfigValue` is `data,` not `resource`. The `TokenType` is safe for having the `copy` attribute.

**Comment by 9191stc** [comment]
How to solve config like this?
```
    struct SwapFeePoundageConfig<X, Y> has store {
        numerator: u64,
        denumerator: u64,
    }
```
This struct must have `copy + drop + store`, therefore, the declaration of template parameter X and Y not only have `store` but also `copy + drop` forced, and the template parameters in function which calling it also forced  `copy + drop + store`. Perhaps only store some data distinct in different token type, but the cost of modification is much higher than the modification of the `copy+drop+store` tag.

**Comment by element2050** [comment]
The TokenType is safe for having the copy attribute, this is all right. 
The problem appears when  has third party dependeny. 
If the project does not have config dependencies, TokenType only define store attribute, enough to use.
But in third third party dependencies, if some function has other attribute , then occurs `CONSTRAINT_NOT_SATISFIED ` error.

**Comment by jolestar** [comment]
> How to solve config like this?
> 
> ```
>     struct SwapFeePoundageConfig<X, Y> has store {
>         numerator: u64,
>         denumerator: u64,
>     }
> ```
> 
> This struct must have `copy + drop + store`, therefore, the declaration of template parameter X and Y not only have `store` but also `copy + drop` forced, and the template parameters in function which calling it also forced `copy + drop + store`. Perhaps only store some data distinct in different token type, but the cost of modification is much higher than the modification of the `copy+drop+store` tag.

Add `phantom` to X and Y.

```
struct SwapFeePoundageConfig<phantom X, phantom Y> has store {
        numerator: u64,
        denumerator: u64,
    }
```
