### ISSUE TITLE
The output of function-test is too long, can be simplified

### ISSUE THREAD

**Issue by 9191stc** [starcoinorg/starcoin#3149]
In functional-test, if an error is reported, a lot of variable information and bytecode instruction information will be printed. This information is very long, especially the vector information. Almost every number occupies one line. Sometimes more than 10,000 lines are output, and there are errors inside. It is very difficult to find the information. Is there any way to optimize it? For example, the constant output in the form of an array can be output without wrapping, or adding a switch can choose to output only errors

![image](https://user-images.githubusercontent.com/91530751/149443856-cf216fdb-1c99-4eb2-943a-8a8316a2ebe5.png)

**Comment by jolestar** [comment]
try the latest mpm, this should be fixed.
