### ISSUE TITLE
[move]Support method to determine two generic type are equal

### ISSUE THREAD

**Issue by element2050** [starcoinorg/starcoin#3178]
Stdlib can determine two token type are equal, it depends native method `name_of` .

```
    /// Return true if the type `TokenType1` is same with `TokenType2`
    public fun is_same_token<TokenType1: store, TokenType2: store>(): bool {
        return token_code<TokenType1>() == token_code<TokenType2>()
    }
```

Can support method to determine any generic type are equals ？ Likes 
```
Generic Type1 == Generic Type2 ？ 
```

**Comment by jolestar** [comment]
Using a Global Registry is one way to achieve this, like the NFT.

```
public fun is_same_type<T1,T2>():bool{
   let type_info_1 = borrow_global<TypeInfo<T1>>();
   let type_info_2 = borrow_global<TypeInfo<T2>>();
   return type_info_1 == type_info_2;
}
```

**Comment by jolestar** [comment]
This feature has been supported in StarcoinFramework by https://github.com/starcoinorg/starcoin-framework/pull/107 and will be supported in MoveStdlib by https://github.com/move-language/move/pull/566
