### ISSUE TITLE
Gas cost table

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#320]
Gas cost table

1. 定义 VM gas cost table
2. 发送交易的相关 cli 命令提供 gas 设置参数

**Comment by guangyuz** [comment]
check了一下，VM的gas table已经定义并生效。

**Comment by jolestar** [comment]
@guangyuz 那确认下部署 module 为什么没有 gas 以及 #216 这个 ERROR

**Comment by jolestar** [comment]
2 tracked by  #400
