### ISSUE TITLE
NFT example `TYPE_MISMATCH` error when deploy package to barnard

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#3208]
Got a `TYPE_MISMATCH` error while deploying the [simple-nft](https://github.com/starcoinorg/guide-to-move-package-manager/tree/main/simple-nft) project to Barnard network.

1. Same error when using starcoin v1.9.x in dev network.
2. It is worked when using starcoin v1.10.0-beta. 
3. I suspect that this bug is caused by the generic type `phantom`.

**Comment by lerencao** [comment]
确实是新的  stdlib 的改动，加了 phantom  导致的。

**Comment by lerencao** [comment]
mpm 依赖的新的 stdlib， NFT 的几个 struct phantom =true。
当部署到链上的时候，会检查 依赖的module 中是否满足 phantom =true。
stdlib 没升级，就会报错。
