### ISSUE TITLE
Migrate move examples to mpm 

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#3218]
Refacor move [examples](https://github.com/starcoinorg/starcoin/tree/master/examples) to mpm project and migrate to https://github.com/starcoinorg/guide-to-move-package-manager/

**Comment by jolestar** [comment]
@zhutoulala Can you help to clean the examples from this repo?

**Comment by zhutoulala** [comment]
> @zhutoulala Can you help to clean the examples from this repo?

Sure, https://github.com/starcoinorg/starcoin/pull/3282
