### ISSUE TITLE
[Feature Request]Don't terminate upon pressing `Ctrl-C`

### ISSUE THREAD

**Issue by whst** [starcoinorg/starcoin#3234]
# Feature Request

When pressing `Ctrl-C`, by default programs terminate due to the SIGINT signal.
However, typical REPL programs (e.g., Bash, Python, GDB) behave differently. Instead of termination, they
regard the `Ctrl-C` action as a user's intention to discard her input and start a new command.
It would be great if *starcoin* console has this feature.

**If the feature request is approved, would you be willing to submit a PR?**
Yes

**Comment by jolestar** [comment]
Expected behavior: if in the console: ignore the Ctrl-C, otherwise handle Ctrl-C and quit the program.
