### ISSUE TITLE
[Feature Request] Initialize all the addresses configured in the toml file

### ISSUE THREAD

**Issue by element2050** [starcoinorg/starcoin#3278]
The problem is that if an address has no module, even though configured in toml file,  when the --public-keys set by task init, the generated address is inconsistent with the address in the toml file.
Initialize the address configured in the toml file, so that after specifying the publickey in the spectest, the generated address can be consistent.
 
Starcoin Framework version:
mpm --version
move-package-manager 1.10.0-rc.2

**Comment by jolestar** [comment]
resolved by #3533
