### ISSUE TITLE
move-package-manager show vm/stdlib/sources NotFound in spectest command

### ISSUE THREAD

**Issue by yubing744** [starcoinorg/starcoin#3326]
# Bug Report

**Starcoin version:**

macOS 10.14.6
move-package-manager 1.10.1

**Current behavior:**

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/1449069/162625136-23794445-d787-44d1-8ac6-73f1e3e3ad42.png">

**Expected behavior:**

exit with code 0

**Steps to reproduce:**

```bash
  git clone https://github.com/starcoinorg/guide-to-move-package-manager.git
  cd guide-to-move-package-manager/simple-nft
  RUST_BACKTRACE=1 mpm spectest
```

**Comment by jolestar** [comment]
try the latest mpm alpha version, this should be fixed.

**Comment by yubing744** [comment]
> try the latest mpm alpha version, this should be fixed.

OK
