### ISSUE TITLE
[Bug Report] using starcoin_db_exporter and command line does not have a newline

### ISSUE THREAD

**Issue by WGB5445** [starcoinorg/starcoin#3339]
# Bug Report

**Starcoin version:**

**Current behavior:**

Use the **starcoin_db_exporter** command on the command line, enter Enter without entering any parameters

**Expected behavior:**
![screenshot 7](https://user-images.githubusercontent.com/6522980/163082677-632a6f71-54fe-4fd5-ba5d-da30e06902a0.jpg)

After printing the help message, the command prompt should be on the next line of the help message ,But now the command prompt line and the last line of the help message are on the same line

**Steps to reproduce:**

**Related code:**

**Other information:**

This may be caused by a problem with the output of clap

**Comment by uvd** [comment]
macos is ok

**Comment by WGB5445** [comment]
I am using wsl ubuntu, and this happens when I use docker

**Comment by djy0** [comment]
unable to reproduce on window 10, wsl ubuntu (or in docker), and ubuntu

**Comment by WGB5445** [comment]
I'm using the latest version and I haven't encountered this problem, I think it should be fixed, thank you
