### ISSUE TITLE
[Feature Request] MPM supports running in the browser, retaining only the build functionality to reduce size.

### ISSUE THREAD

**Issue by yubing744** [starcoinorg/starcoin#3363]
# Feature Request

MPM supports running in the browser, retaining only the build functionality to reduce size.

**Describe Preferred Solution**

Control module compilation by turning on the  feature switch, set the compilation target to wasm32-unknown-unknown support running in the browser.

**Related Code**

(https://github.com/starcoinorg/starcoin/tree/master/vm/move-package-manager)

**Additional Context**

Like [Dove Light](https://github.com/pontem-network/dove/tree/ligth) - Dove package manager built for Web.

**If the feature request is approved, would you be willing to submit a PR?**
Yes

**Comment by yubing744** [comment]
pick!

**Comment by yubing744** [comment]
Since the browser does not support file operations, compiling move-compiler to wasm-unkown-unkown will fail because it cannot read the file. The solution of the pontem-network team is to let move-compiler provide a compilation Callback, and then wasm implements the file access interface separately. Related Commit: https://github.com/pontem-network/diem/commit/11ae64bb7af73c4f7305fc145d359daede77d19e

**Comment by yubing744** [comment]
But now move-language/move has no Callback/Interact function.

**Comment by jolestar** [comment]
> But now [move-language/move](https://github.com/move-language/move) has no Callback/Interact function.

@yubing744, please create a new Feature Request for the callback requirement.

**Comment by yubing744** [comment]
> 

OK

**Comment by yubing744** [comment]
@jolestar I have created a new Feature Request for the callback requirement: https://github.com/move-language/move/issues/89

**Comment by jolestar** [comment]
Is this feature implemented in [move-js](https://github.com/starcoinorg/move-js)?

**Comment by yubing744** [comment]
> Is this feature implemented in [move-js](https://github.com/starcoinorg/move-js)?

Yes, it can be closed
