### ISSUE TITLE
[Bug Report] cannot compile on windows

### ISSUE THREAD

**Issue by geometryolife** [starcoinorg/starcoin#3369]
# Bug Report

**Starcoin version:** Control Version

**Current behavior:** cannot compile on windows10

**Expected behavior:**

**Steps to reproduce:**

```powershell
.\scripts\dev_setup.ps1
cargo build
```

**Related code:**

```
error: failed to run custom build command for `librocksdb-sys v6.20.3`

Caused by:
  process didn't exit successfully: `C:\Users\17169\i\starcoin\target\debug\build\librocksdb-sys-e6c53916d9d45639\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', C:\Users\17169\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.59.2\src/lib.rs:2144:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Other information:**

I tried Msys2 and LLVM, but none of them could solve this compilation error.

**Comment by jolestar** [comment]
@geometryolife is this resolved?

**Comment by geometryolife** [comment]
At present, no solution has been found, and it may need to be tested by others. I can't rule out why it's my computer.

**Comment by LemonHX** [comment]
@geometryolife check your path settings in windows.
and we are not using msys2 nor mingw, we are directly using msvc toolchains.

**Comment by geometryolife** [comment]
I’ll try it again.

**Comment by geometryolife** [comment]
![image](https://user-images.githubusercontent.com/54882546/168204139-04198005-0c5d-4d2e-a0ff-2cb58053e54f.png)

I tried, but I still failed.

**Comment by geometryolife** [comment]
**Solution:**
Set the `LIBCLANG_PATH` environment variable.
