### ISSUE TITLE
[Dev]improve accumulator storage and get_node_hash performance

### ISSUE THREAD

**Issue by nkysg** [starcoinorg/starcoin#3390]
In Accumulator AccumulatorNode define as below 
```rust
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize, CryptoHasher, CryptoHash)]
pub enum AccumulatorNode {
    Internal(InternalNode),
    Leaf(LeafNode),
    Empty,
}
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct InternalNode {
    index: NodeIndex,
    left: HashValue,
    right: HashValue,
    is_frozen: bool,
}
#[derive(Clone, Debug, Hash, Eq, PartialEq, Serialize, Deserialize, CryptoHasher, CryptoHash)]
pub struct LeafNode {
    index: NodeIndex,
    hash: HashValue,
}

```
the Accumulator save in  Rocksdb is use `(Hash(AccumulatorNode), encode(AccumulatorNode))`。We can use `(NodeIndex, Hash(AccumulatorNode)) to improve performance。

I think there are 4 steps
1) create a new ColumnFamily rewrite `(Hash(AccumulatorNode), encode(AccumulatorNode))` , original ColumnFamily are 
BLOCK_ACCUMULATOR_NODE_PREFIX_NAME, TRANSACTION_ACCUMULATOR_NODE_PREFIX_NAME 

2) refactor 
```rust
 pub(crate) fn get_node_hash(&mut self, node_index: NodeIndex) -> Result<Option<HashValue>> 
```
3) refactor 
```rust
fn get_leaves(&self, start_index: u64, reverse: bool, max_size: u64) -> Result<Vec<HashValue>>
```
use rocksdb multiple_get
4) `    pub fn do_upgrade(`  remove BLOCK_ACCUMULATOR_NODE_PREFIX_NAME, TRANSACTION_ACCUMULATOR_NODE_PREFIX_NAME 

the detail about Accumulator https://github.com/starcoinorg/starcoin-cookbook/blob/main/i18n/zh/docusaurus-plugin-content-docs/current/99-concepts/06-accumulator.md
this is chinese version. English version is on the way。

**Comment by 0xpause** [comment]
Here is a problem: 
There are multiple AccumulatorTrees for a given ColumnFamily, which are created by chain fork, uncle blocks, etc. But the `NodeIndex` is not unique across multiple AccumulatorTrees, therefor it cannot be used as a key in a KVstore.

**Comment by nkysg** [comment]
https://github.com/starcoinorg/starcoin/pull/3551 has solve accumulator append, so I will close
