### ISSUE TITLE
[MPM] move-package-manager prompts HOME environment variable not found on Windows platform

### ISSUE THREAD

**Issue by yubing744** [starcoinorg/starcoin#3400]
# Bug Report

MPM prompts HOME environment variable not found on Windows platform。

OS:  Windows 10
mpm:  v1.11.9-alpha

**Current behavior:**

![image](https://user-images.githubusercontent.com/1449069/167970163-0e82fcb0-09b5-4772-8cc9-b4f3f4c467c5.png)

**Expected behavior:**

No error message.

**Steps to reproduce:**

```shell
git clone https://github.com/starcoinorg/guide-to-move-package-manager.git
cd simple-nft
mpm.exe package build
```

**Related code:**

https://github.com/starcoinorg/move/blob/ae12f353227a01da84efeec99943c6185afec338/language/tools/move-package/src/source_package/manifest_parser.rs#L327

**Other information:**

None

**Comment by jolestar** [comment]
We should use crate dirs-next to get home dir in move-package.

```
dirs_next::home_dir()
```

**Comment by jolestar** [comment]
resolved
