### ISSUE TITLE
[MPM] Multi-module move project build fails

### ISSUE THREAD

**Issue by yubing744** [starcoinorg/starcoin#3403]
# Bug Report

Multi-module project build fails

OS:  Windows 10
mpm:  v1.11.9-alpha

**Current behavior:**

![image](https://user-images.githubusercontent.com/1449069/168184678-ceb0d02b-d0d6-477b-aea6-137a786c25b9.png)

**Expected behavior:**

No Error

**Steps to reproduce:**

```shell
git clone https://github.com/starcoinorg/guide-to-move-package-manager.git
cd guide-to-move-package-manager/coin-swap
mpm.exe release
```

**Comment by jolestar** [comment]
confirm, @lerencao is the release bug or the local dependency bug?

**Comment by 0xpause** [comment]
All module addresses are required the same, which was checked here:
https://github.com/starcoinorg/starcoin/blob/85995a1207a91c70feb7235c8cd6134cb04794b4/vm/types/src/transaction/package.rs#L33

So may be the guide is outdated?

**Comment by jolestar** [comment]
> All module addresses are required the same, which was checked here:
> 
> https://github.com/starcoinorg/starcoin/blob/85995a1207a91c70feb7235c8cd6134cb04794b4/vm/types/src/transaction/package.rs#L33
> 
> So may be the guide is outdated?

BasicCoin and CoinSwap are two packages. Maybe local dependency should rename the address to same as main package like https://starcoinorg.github.io/starcoin-cookbook/docs/move/move-language/packages

**Comment by 0xpause** [comment]
> > All module addresses are required the same, which was checked here:
> > https://github.com/starcoinorg/starcoin/blob/85995a1207a91c70feb7235c8cd6134cb04794b4/vm/types/src/transaction/package.rs#L33
> > 
> > So may be the guide is outdated?
> 
> BasicCoin and CoinSwap are two packages. Maybe local dependency should rename the address to same as main package like https://starcoinorg.github.io/starcoin-cookbook/docs/move/move-language/packages

The error is not from BasicCoin. BasicCoin is a local dependency with different address, and that is OK. 
The error is from GoldCoin module whose address is not same as the package address, which is defined using the address of first module SilverCoin.
All module in this package(CoinSwap, GoldCoin, PoolToken, SilverCoin) are required to use same address.

**Comment by 0xpause** [comment]
Change the Move.toml file as follow:
```
[package]
name = "CoinSwap"
version = "0.0.0"

[addresses]
CoinSwap = "0xC5"
GoldCoin = "0xC5"
SilverCoin = "0xC5"
PoolToken = "0xC5"

[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin-framework.git", rev="cf1deda180af40a8b3e26c0c7b548c4c290cd7e7"}
BasicCoin = { local = "../basic-coin"}
```
Then the release command goes right.

**Comment by jolestar** [comment]
> Change the Move.toml file as follow:
> 
> ```
> [package]
> name = "CoinSwap"
> version = "0.0.0"
> 
> [addresses]
> CoinSwap = "0xC5"
> GoldCoin = "0xC5"
> SilverCoin = "0xC5"
> PoolToken = "0xC5"
> BasicCoin = "0xBC"
> StarcoinFramework = "0x01"
> 
> [dependencies]
> StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin-framework.git", rev="cf1deda180af40a8b3e26c0c7b548c4c290cd7e7"}
> BasicCoin = { local = "../basic-coin"}
> ```
> 
> Then the release command goes right.

Can you help to update the examples at https://github.com/starcoinorg/starcoin-cookbook/tree/main/examples?

the guide-to-move-package-manager repo has migrated to the cookbook repo.

**Comment by 0xpause** [comment]
> > Change the Move.toml file as follow:
> > ```
> > [package]
> > name = "CoinSwap"
> > version = "0.0.0"
> > 
> > [addresses]
> > CoinSwap = "0xC5"
> > GoldCoin = "0xC5"
> > SilverCoin = "0xC5"
> > PoolToken = "0xC5"
> > BasicCoin = "0xBC"
> > StarcoinFramework = "0x01"
> > 
> > [dependencies]
> > StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin-framework.git", rev="cf1deda180af40a8b3e26c0c7b548c4c290cd7e7"}
> > BasicCoin = { local = "../basic-coin"}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then the release command goes right.
> 
> Can you help to update the examples at https://github.com/starcoinorg/starcoin-cookbook/tree/main/examples?
> 
> the guide-to-move-package-manager repo has migrated to the cookbook repo.

Done.
