### ISSUE TITLE
[Dev] refactor code,  move resource-exporter cmd to db_exporter as subcommand and use statedb.dump_iter replace statedb.dump 

### ISSUE THREAD

**Issue by nkysg** [starcoinorg/starcoin#3428]
resource-exporter code https://github.com/starcoinorg/starcoin/blob/87991cf0369159dc0135ad8a2143801fd37f20ae/cmd/resource-exporter/src/main.rs#L67-L90, 

db_exporter code https://github.com/starcoinorg/starcoin/blob/87991cf0369159dc0135ad8a2143801fd37f20ae/cmd/db-exporter/src/main.rs#L1207-L1215

```ChainStateDB::dump```
https://github.com/starcoinorg/starcoin/blob/87991cf0369159dc0135ad8a2143801fd37f20ae/state/statedb/src/lib.rs#L381-L391
```ChainStateDB::dump_iter```
https://github.com/starcoinorg/starcoin/blob/87991cf0369159dc0135ad8a2143801fd37f20ae/state/statedb/src/lib.rs#L423-L428

**Comment by aristotll** [comment]
assign me

**Comment by nkysg** [comment]
@jiangying000 could you help me improve this feature?

**Comment by jiangying000** [comment]
> @jiangying000 could you help me improve this feature?

yes, of course

**Comment by nkysg** [comment]
and the code
https://github.com/starcoinorg/starcoin/blob/87991cf0369159dc0135ad8a2143801fd37f20ae/rpc/server/src/module/state_rpc.rs#L248-L262

https://github.com/starcoinorg/starcoin/blob/87991cf0369159dc0135ad8a2143801fd37f20ae/rpc/server/src/module/state_rpc.rs#L304-L316
 I think you can try to improve
