### ISSUE TITLE
[Feature Request] node.peers api return node_name

### ISSUE THREAD

**Issue by yourmoonlight** [starcoinorg/starcoin#3439]
# Feature Request

**Describe the Feature Request**

Could the node.peers api return field node_name as the same level as the field peer_id?

**Additional Context**

Currently, the peer_id is not related to the wallet address, but if we run the node with node_name argument, and set it to wallet address，then it is solved in an easy way.  It makes the later possible airdrop process easier.

**Comment by coldnight** [comment]
Hi, I do a little research about this, and found that we need to add a `node_name` field to [`network_p2p::protocol::message::generic::Status`](https://github.com/starcoinorg/starcoin/blob/master/network-p2p/src/protocol/message.rs) while handshaking, and currently it encoded/decoded by `bcs` which [lacks backwards compatibility](https://docs.rs/bcs/latest/bcs/#backwards-compatibility). The changes that I made could refer to https://github.com/coldnight/starcoin/commit/4da7e2bd355b2fec0fa8d59cdee8a4188c20dd44.

**Comment by jolestar** [comment]
@coldnight I think we do not need to change the handshake message.

```
node network state
{
  "ok": {
    "connectedPeers": {
      "12D3KooW9quK2EEjeyTs3csNRWPnfMw4M3afGE1SHm1dCZDRWSAj": {
        "endpoint": {
          "dialing": "/dns4/main5.seed.starcoin.org/tcp/9840/p2p/12D3KooW9quK2EEjeyTs3csNRWPnfMw4M3afGE1SHm1dCZDRWSAj"
        },
        "knownAddresses": [
          "/dns4/main5.seed.starcoin.org/tcp/9840",
          "/ip4/18.182.8.131/tcp/9840",
          "/dns4/main5.seed.starcoin.org/tcp/9840/p2p/12D3KooW9quK2EEjeyTs3csNRWPnfMw4M3afGE1SHm1dCZDRWSAj"
        ],
        "latestPingTime": {
          "nanos": 248017299,
          "secs": 0
        },
        "versionString": "starcoin/1.11.7-rc (build:1.11.7-rc) (berserk-seashore-0643)"
      },
```

network state `versionString` field contains the node name `(berserk-seashore-0643)`.

We can just add the `versionString` field to `node.peers`'s response. Maybe `version_string` is more suitable for the filed name.

**Comment by coldnight** [comment]
@jolestar Thanks for your help, a PR has been made.
