### ISSUE TITLE
[Feature Request] [RPC] 新增一个带分页的 state.list_resource   state.get_account_state_set

### ISSUE THREAD

**Issue by uvd** [starcoinorg/starcoin#3442]
# Feature Request

**Describe the Feature Request**
新增一个带分页的 state.list_resource  和 state.get_account_state_set    接口

**Describe Preferred Solution**

假如一个地址资源太多 一次拿那么多数据是不是会太影响性能  
比如这个地址 0x8355417c88d969f656935244641256ad

**Describe Alternatives**

**Related Code**

```shell
uvd, [2022/6/2 3:09 PM]
curl --location --request POST 'https://main-seed.starcoin.org/' \
--header 'Content-Type: application/json' \
--data-raw '{"method":"state.get_account_state_set","params":["0x8355417c88d969f656935244641256ad"],"id":56,"jsonrpc":"2.0"}'
```

* 直接返回 23万行json数据 接近40M

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by jolestar** [comment]
resource 和 code 都存为 smt 数结构中，做分页不太好实现，不过优化方式可以考虑：

1. list resource 的时候不要传递 decode 参数，直接拿到 bcs 二进制数据在 js 中 decode，不过需要配合 ABI。
2. 考虑提供 `state.list_resource_key`, `state.list_code_key` 接口，先拿到所有的 resource key（struct type）， code key（module name），然后延迟加载具体的内容。效率可能更好一些。

@nkysg 看看是否有更好的办法。

**Comment by djy0** [comment]
@jolestar I'd like to work on this

**Comment by jolestar** [comment]
> @jolestar I'd like to work on this

👍 @nkysg 给一些指导

**Comment by uvd** [comment]
https://github.com/starcoinorg/starcoin/issues/3447  可以带上这个一起 这个也挺实用的

**Comment by jiangying000** [comment]
Sorry for being kind of slow, I am debuging the codebase and learning the project-structure, chain-structure, underlying data-structures, Rust lang; and planning to submit a PR in one or two weeks.

**Comment by jiangying000** [comment]
Sorry for being kind of slow, I am debuging the codebase and learning the project-structure, chain-structure, underlying data-structures, Rust lang; and planning to submit a PR in one or two weeks.

**Comment by uvd** [comment]
3q  3q  我还说你没搞了的话 我练练手 入门入门呢

**Comment by jiangying000** [comment]
> resource 和 code 都存为 smt 数结构中，做分页不太好实现，不过优化方式可以考虑：
> 
> 1. list resource 的时候不要传递 decode 参数，直接拿到 bcs 二进制数据在 js 中 decode，不过需要配合 ABI。
> 2. 考虑提供 `state.list_resource_key`, `state.list_code_key` 接口，先拿到所有的 resource key（struct type）， code key（module name），然后延迟加载具体的内容。效率可能更好一些。
> 
> @nkysg 看看是否有更好的办法。

bsc能大致线性地压缩数据量（大概变为一半），但是考虑到数据会随时间一直增加，还有前端解析bcs的运算，最终可能还是会比较慢

**Comment by jiangying000** [comment]
`state.get_account_state_set` 会把 resource 和 code 两个 独立的 json 拼起来，还需要看下怎么定义分页

另外 state.get_account_state_set 哪里会用到啊？

**Comment by jolestar** [comment]
> `state.get_account_state_set` 会把 resource 和 code 两个 独立的 list 拼起来，我还不清楚怎么去定义这个数据的分页
> 
> 另外 state.get_account_state_set 哪里会用到啊？

`state.get_account_state_set` 这个接口可以不考虑分页。

**Comment by jiangying000** [comment]
> > `state.get_account_state_set` 会把 resource 和 code 两个 独立的 list 拼起来，我还不清楚怎么去定义这个数据的分页
> > 另外 state.get_account_state_set 哪里会用到啊？
> 
> `state.get_account_state_set` 这个接口可以不考虑分页。

ok

**Comment by jolestar** [comment]
resolved
