### ISSUE TITLE
[Feature Request][RPC] 新增一个能通过 resource name  例如 0x1::Account::Balance  获取到全部余额的的方法 

### ISSUE THREAD

**Issue by uvd** [starcoinorg/starcoin#3447]
# Feature Request

**Describe the Feature Request**

比如我要获取一个 地址的 全部余额  现在的做法的是变量整个 resource 的 0x1::Account::Balance 才能得到 一是不方便 二是有性能问题

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by jolestar** [comment]
可以考虑给 state.list_resource 增加一个过滤参数，用于遍历过滤类似 0x1::Account::Balance<Token> 这种泛型类型的 resource。

**Comment by jiangying000** [comment]
working
