### ISSUE TITLE
[Feature Request] block execute support move feature table-extension

### ISSUE THREAD

**Issue by nkysg** [starcoinorg/starcoin#3465]
# Feature Request
block execute support move feature table-extension
**Describe the Feature Request**
using table-extension can support large-scale storage, 

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by 0xpause** [comment]
Could you please provide more detail about what to do?

**Comment by nkysg** [comment]
> Could you please provide more detail about what to do?

Hi, @0xpause 。I forgot to update this issue。
First need update the new version move-language support feature move-table-extension。 It is 
 almost finished in this [https://github.com/starcoinorg/starcoin/pull/3424](link)。
Second update starcoin_vm.rs support move-table-extension, I'm developing this feature。There are some commit in this [https://github.com/starcoinorg/starcoin/commits/table_extension](url) 。After finish this, I will write some comments to describe it。

**Comment by 0xpause** [comment]
> > Could you please provide more detail about what to do?
> 
> Hi, @0xpause 。I forgot to update this issue。 First need update the new version move-language support feature move-table-extension。 It is almost finished in this [https://github.com/starcoinorg/starcoin/pull/3424](link)。 Second update starcoin_vm.rs support move-table-extension, I'm developing this feature。There are some commit in this [https://github.com/starcoinorg/starcoin/commits/table_extension](url) 。After finish this, I will write some comments to describe it。

Thanks for your reply. I thought that this is unassigned issue so I asked for more detail to see if I can handle it.  As you have almost finished this, no need for me anymore.

**Comment by nkysg** [comment]
Table using 2 level smt tree.  The top  smt tree is TableHandle -> SMT root hash, the bottom smt tree is TableITem insert it.

**Comment by nkysg** [comment]
It has merge in branch dev, so I will close it.
