### ISSUE TITLE
[Bug Report][build] failed to run `cargo build`,  `fatal: couldn't find remote ref HEAD`

### ISSUE THREAD

**Issue by jiangying000** [starcoinorg/starcoin#3508]
# Bug Report

**Starcoin version:**

current master branch HEAD / f5c2da578494248c1292462efd8efc546d525b6a

**Current behavior:**

run `cargo build` fails:
```
error: failed to get `move-bytecode-verifier` as a dependency of package `starcoin-vm-types v1.11.11 (/home/jiangying/code/playground/starcoin/vm/types)`

Caused by:
  failed to load source for dependency `move-bytecode-verifier`

Caused by:
  Unable to update https://github.com/starcoinorg/move?rev=69db2858761045f19935f3aaf43f04a1910ae74d#69db2858

Caused by:
  process didn't exit successfully: `git fetch --tags --force --update-head-ok 'file:///home/jiangying/.cargo/git/db/move-ae0d26a86327ae96' '+refs/heads/*:refs/remotes/origin/*' '+HEAD:refs/remotes/origin/HEAD'` (exit status: 128)
  --- stderr
  fatal: couldn't find remote ref HEAD
```

**Expected behavior:**
build successfully

**Note**

This is difficult to reproduce, it randomly occurs, but at least two developers of us encountered this bug,

unresolvable repo in error message can also be `starcoinorg/starcoin-crypto`

`cargo build` is ran in shell
1. There is no network issue.
2. tried `rm -rf  /home/jiangying/.cargo/git/db/move-ae0d26a86327ae96`，then `cargo build`, not work
3. pull full repo and rebuild not work

remove `git-fetch-with-cli = true` in `.cargo/config` then `cargo build`, temporally resolved this issue, even add this line back, error disappeared

昨天开始不能build。
在shell里跑的
已经确认网络没问题，直接`git clone https://github.com/starcoinorg/move.git`也没问题，但是build时就会报错
试过`rm -rf  /home/jiangying/.cargo/git/db/move-ae0d26a86327ae96`，然后重新`cargo build`也没有用
试过`rm -rf  .git`，然后重新拉取starcoin仓库，git reset origin/master也没有用
建立新的文件夹，拉取仓库`git clone https://github.com/starcoinorg/starcoin.git`，`cargo build`问题照旧

**Comment by jiangying000** [comment]
在shell里跑的，已经确认网络没问题，直接`git clone https://github.com/starcoinorg/move.git`也没问题，但是build时就会报错

**Comment by jiangying000** [comment]
a temporary solution is replace all problematic https:// repo urls with ssh ones (starting with git@)
```
find ./ -name "*.toml" | xargs sed -i "s/https:\/\/github.com\/starcoinorg\/move/ssh:\/\/git\@github\.com\/starcoinorg\/move\.git/g"
```

**Comment by coldnight** [comment]
1. Configure your git to use SSH instead of HTTPS by running:

   ```shell
   git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"                                                                                                                           
   ```
2. If you got a SOCKS5 or HTTP proxy, you can apply it for github.com in your `~/.ssh/config` or `~/.gitconfig`, check more details in https://github.com/comwrg/package-manager-proxy-settings#git

**Comment by jiangying000** [comment]
another tested  (and probably better) workaround  is remove `git-fetch-with-cli = true` in `.cargo/config` and run `cargo build` again

this issue seems to be related to `cargo` cli

**Comment by jiangying000** [comment]
maybe fixed by cargo

**Comment by jiangying000** [comment]
I think this is fixed, as I have tested a lot of times (>5) when git deps got messed and I switch to rusttoolchain  >= 1.64, the error always disappear and git deps are auto fixed
