### ISSUE TITLE
[Bug Report][ci] ci is canceled

### ISSUE THREAD

**Issue by jiangying000** [starcoinorg/starcoin#3509]
# Bug Report

**Starcoin version:**
f5c2da578494248c1292462efd8efc546d525b6a

**Current behavior:**
ci is canceled for latest 3 commits
f5c2da578494248c1292462efd8efc546d525b6a
0fd66afeb8f98f7dcfd4d2b5f93586c3a12d7a52
7471c9387e12644c37d67f70b50c10a096dcbba4

**Expected behavior:**
ci should run

**Other information:**
I encountered a build issue #3508, and took a look at ci, but seems recent CIs are cancelled unexpectedly

**Comment by jiangying000** [comment]
这个好像我看错了，没有cancel，只是没通过coverage

**Comment by coldnight** [comment]
Check https://github.com/starcoinorg/starcoin/blob/master/.github/workflows/cancel.yml
