### ISSUE TITLE
[Feature Request] mpm integration test support use block and state proof as arguments for tests function

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#3513]
# Feature Request

**Describe the Feature Request**

mpm integration test support use block and state proof as arguments for the tests function

**Describe Preferred Solution**

Option 1: Provide integration test commands, and command template:

```
//# init -n dev --enable-rpc

//# faucet --addr creator --amount 100000000000

//# call_rpc --api chain.get_block_by_number --args 1 --args "{decode:true}"

//# run --signers creator --args $call_rpc[0].header.state_root

script{
   fun main(sender:signer, state_root:vector<u8>){
      
   }
}

```

Option 2: Provide Move native methods for Chain API

```
//# init -n dev --enable-rpc

//# faucet --addr creator --amount 100000000000

//# run --signers creator

script{
   fun main(sender:signer, state_root:vector<u8>){
      let block_header = Chain::get_block_header(block_number);
      let state_root = BlockHeader::state_root(&block_header);
   }
}
```

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by yuliyu123** [comment]
I would like to try to solve this feature.
