### ISSUE TITLE
[Feature Request] mpm support check compatibility from previous package

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#3515]
# Feature Request

**Describe the Feature Request**

mpm support checks compatibility from the previous package

**Describe Preferred Solution**

Add a `pre-version` option to `mpm check-compatibility`, and check compatibility between the current version and the previous version. 

**Related Code**

https://github.com/starcoinorg/starcoin/blob/ec44d09465fd5626969307a46614f3967dbaebcc/vm/stdlib/src/main.rs#L301-L346

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by yuliyu123** [comment]
I would like to try to solve this feature.

**Comment by yuliyu123** [comment]
Hi guys, I have a problem now, how can I get the modules by pre-check parameter? I specify the pre-check version by `mpm check-compatibility --pre-version 1.11.11` but I don't know how to get the modules by the pre-check version.

**Comment by jolestar** [comment]
> Hi guys, I have a problem now, how can I get the modules by pre-check parameter? I specify the pre-check version by `mpm check-compatibility --pre-version 1.11.11` but I don't know how to get the modules by the pre-check version.

We need a standard for keeping the release binary.

1. At the `vm/stdlib`, we use `compiled/$version` to keep binary.
2. At the [starcoin-framework](https://github.com/starcoinorg/starcoin-framework/), we use `release/$version` to keep binary.
3. The `mpm release` command writes the package binary to `release/$version.blob`.

If we can't decide which way to go, maybe the parameter should be `--pre-modules`? 

Such as:

`mpm check-compatibility --pre-modules compiled/11/stdlib/`

or

`mpm check-compatibility --pre-modules release/StarcoinFramework.v0.1.0.blob`

the `--pre-modules` can be a dir that contains modules or a package binary file.

**Comment by yuliyu123** [comment]
link to: https://github.com/starcoinorg/starcoin/pull/3522

**Comment by nkysg** [comment]
> link to: #3522

should  convert draft  to review
