### ISSUE TITLE
[Bug Report] fail when importing block

### ISSUE THREAD

**Issue by jiangying000** [starcoinorg/starcoin#3549]
# Bug Report
**Starcoin version:**

[29cf2b5](https://github.com/starcoinorg/starcoin/commit/29cf2b5df50d4f75a1284c1e967c3a385e198bc1)

**Current behavior:**

run: `./import_block.sh main ~/.starcoin/main`

err log
```
download main block_6205515_6215514.csv succ
Error: No such file or directory (os error 2)
apply-block main block_6205515_6215514.csv fail
```

**Expected behavior:**

success
**Steps to reproduce:**

run: `./import_block.sh main ~/.starcoin/main`
and wait for some time (tens of hours)

**Related code:**

```
```

**Other information:**

`block_6205515_6215514.csv.tar` is in https://s3.ap-northeast-1.amazonaws.com/main.starcoin.org/main/block_list.csv.tar.gz

while https://s3.ap-northeast-1.amazonaws.com/main.starcoin.org/main/block_6205515_6215514.csv.tar.gz is a 45 byte file, appearently to small to contain 10000 blocks

**Comment by yourmoonlight** [comment]
Some blocks missing need to retransmit manually, I will fix that.

**Comment by yourmoonlight** [comment]
Missing blocks have been already retransmitted, you can try it now. @jiangying000

**Comment by jiangying000** [comment]
> Missing blocks have been already retransmitted, you can try it now. @jiangying000

thank you, block 6205515 to 6785514 are successful imported on my machine.

**Comment by jiangying000** [comment]
hello

https://s3.ap-northeast-1.amazonaws.com/main.starcoin.org/main/block_6865515_6875514.csv.tar.gz

is broken, it is a 45 bytes file.

---

while 
https://s3.ap-northeast-1.amazonaws.com/main.starcoin.org/main/block_6875515_6885514.csv.tar.gz
https://s3.ap-northeast-1.amazonaws.com/main.starcoin.org/main/block_6885515_6895514.csv.tar.gz
are ok

**Comment by yourmoonlight** [comment]
[block_6865515_6875514.csv.tar.gz](https://s3.ap-northeast-1.amazonaws.com/main.starcoin.org/main/block_6865515_6875514.csv.tar.gz) had been retransmitted
