### ISSUE TITLE
[Bug Report] transaction-builder-generator generate broken Source

### ISSUE THREAD

**Issue by jiangying000** [starcoinorg/starcoin#3554]
# Bug Report

**Starcoin version:**
master HEAD [7bbf1d4](https://github.com/starcoinorg/starcoin/commit/7bbf1d4ec63805293348e646d3051e2c8b29c517)

**Current behavior:**

current classes, import is broken and demo does not run

**Expected behavior:**

**Steps to reproduce:**
following https://github.com/starcoinorg/starcoin/blob/master/vm/transaction-builder-generator/README.md, run
```
target/debug/generate-transaction-builders \
    --language java \
    --module-name org.starcoin.stdlib.Stdlib \
    --with-diem-types "etc/starcoin_types.yml" \
    --target-source-dir "target/java" \
    "vm/stdlib/compiled/latest/transaction_scripts/abi"
```
```
cp language/transaction-builder-generator/examples/java/StdlibDemo.java "$DEST"
(find "$DEST" -name "*.java" | xargs javac -cp "$DEST")
java -cp "$DEST" StdlibDemo
```
produce many errors

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by jolestar** [comment]
#3469
