### ISSUE TITLE
[Dev] the starcoin_db_exporter cmd sometimes not work as expected

### ISSUE THREAD

**Issue by yourmoonlight** [starcoinorg/starcoin#3556]
# Bug Report

**Starcoin version:**

1.11.12

**Current behavior:**

Currently, we are syncing the blocks using a cron action. 
Sometimes, the export behavior did not work as expected.
For example, we would like to export blocks from 6865515 to 6875514, but the export cmd export from 6865515 to 6875106.

**Expected behavior:**

Do exactly as the args or  return an error, so we can retry it.

**Other information:**

The cron action history:
https://github.com/starcoinorg/starcoin/runs/7414649133?check_suite_focus=true

**Comment by nkysg** [comment]
The reason is that starcoin blockchain is Eventual consistency system. when export block it will let the height less than blockchain current height - 1000 to prevent revert。

**Comment by yourmoonlight** [comment]
> The reason is that starcoin blockchain is Eventual consistency system. when export block it will let the height less than blockchain current height - 1000 to prevent revert。So it's not a bug.

Ok, got it, thanks very much, I'll close this issue.
