### ISSUE TITLE
[Bug Report][miner] starcoin node errors when a starcoin_miner connects

### ISSUE THREAD

**Issue by jiangying000** [starcoinorg/starcoin#3557]
# Bug Report

**Starcoin version:**

master HEAD: 7bbf1d4ec63805293348e646d3051e2c8b29c517

**Current behavior:**
first run `target/debug/starcoin`

then run `target/debug/starcoin_miner --user 1`

starcoin node console errors:
```
2022-07-22T03:12:53.589963690+08:00 INFO - Accepted a new tcp connection from 127.0.0.1:56828.
2022-07-22T03:12:53.590594478+08:00 ERROR - WS Error <Http(Token)>: Invalid byte where token is required.
```

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by yourmoonlight** [comment]
looks like this had been fixed, https://github.com/starcoinorg/starcoin/pull/3642

**Comment by jiangying000** [comment]
yes, this is fixed
