### ISSUE TITLE
[Feature Request] insuffient disk space warning

### ISSUE THREAD

**Issue by nkysg** [starcoinorg/starcoin#3562]
# Feature Request

**Describe the Feature Request**
There is a problem when the disk usage reach 99% capacity, the rocksdb write fail, then the starcoin application panic.
Then we cannot restart the starcoin application. It describe in https://github.com/starcoinorg/starcoin/issues/3128.
May be the disk usage reach 90% capacity, we should print some error msg. when it reach 95%, we should panic?
May be frequency of check 5 seconds is ok? 

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by nkysg** [comment]
@jolestar reach 95% disk capacity panic is ok?

**Comment by jolestar** [comment]
> @jolestar reach 95% disk capacity panic is ok?

I think it is ok for protected data.

**Comment by jiangying000** [comment]
For a 10T disk, there would be 500GB free even if 95% of disk space is used.

Maybe we could use fixed `GB` value, e.g. 3GB ?

**Comment by nkysg** [comment]
I think you idea is better.

**Comment by YusongWang** [comment]
Somebody get me a hit, which module or  which file put that check is better?
So  i can work on it.
