### ISSUE TITLE
[Feature Request] mpm integration-test support `package` and `deploy` command

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#3574]
# Feature Request

**Describe the Feature Request**

let mpm integration-test support `package` command, for build Starcoin package transaction.

Currently, We use the `publish` command to publish the modules to storage; it auto compiles the Move modules and builds package transaction.

But sometimes, We need to know the Package hash in integration-test, such as the two-phase upgrade.

So we need to support `package` and `deploy` commands in integration-test files.

**Describe Preferred Solution**

```move
//# package
module default::MyModule{

}

// submit the Upgrade plan.

//# deploy $.package[0].package_file

```

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by yuliyu123** [comment]
which is the related code in the move package manager? Do we need diem-devtool to support such a feature?

**Comment by jolestar** [comment]
> which is the related code in the move package manager? Do we need diem-devtool to support such a feature?

https://github.com/starcoinorg/starcoin/blob/491d1586b06988d99d7ce60e43a5e0de5a51caeb/vm/move-package-manager/src/main.rs#L82


https://github.com/starcoinorg/starcoin/blob/491d1586b06988d99d7ce60e43a5e0de5a51caeb/vm/starcoin-transactional-test-harness/src/lib.rs#L149-L188
