### ISSUE TITLE
[Feature Request]Starcoin console support jpst

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#3576]
# Feature Request

**Describe the Feature Request**

Starcoin console support [jpst](https://github.com/starcoinorg/jpst) expression like

```
starcoin% chain list-block
starcoin% chain get-block $.list-block[0].block_hash
```

**Related Code**

1. integration jpst in scmd crate: [commons/scmd](https://github.com/starcoinorg/starcoin/tree/master/commons/scmd)
2. like mpm integration tests  https://github.com/starcoinorg/starcoin/blob/eef95e5f04d22191f498d170ad26a09a15de07d7/vm/starcoin-transactional-test-harness/tests/cases/arg_variable.move#L9-L11

**Comment by yuliyu123** [comment]
like `chain list-block $.ok[0].author` => "0x00000000000000000000000000000001"?

**Comment by jolestar** [comment]
> like `chain list-block $.ok[0].author` => "0x00000000000000000000000000000001"?

Support retrieve cli history command output.
