### ISSUE TITLE
[Bug Report] mpm release

### ISSUE THREAD

**Issue by dajuguan** [starcoinorg/starcoin#3582]
# Bug Report

**starcoin [1.11.12 Release](https://github.com/starcoinorg/starcoin/releases/download/v1.11.12/starcoin-windows-latest.zip):**

**Current behavior:**

thread 'main' panicked at 'env var 'HOME' must be set: NotPresent', C:\Users\runneradmin\.cargo\git\checkouts\move-ae0d26a86327ae96\69db285\language\tools\move-package\src\source_package\manifest_parser.rs:326:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Expected behavior:**

**Steps to reproduce:**
run `mpm release ` in a folder that contains: `Move.toml` and `sources\MyCounter.move`.

**Comment by jolestar** [comment]
I remember that the Windows env `HOME` issue is resolved, @LemonHX  @yubing744

**Comment by jiangying000** [comment]
https://github.com/starcoinorg/move/compare/starcoin-main...move-language:move:main

因为starcoinorg/move的starcoin-main分支没有pick这个commit？
![image](https://user-images.githubusercontent.com/23182033/182022989-50655664-e04d-4c3f-9e20-cd8e626cc2b7.png)

**Comment by jolestar** [comment]
> [starcoinorg/move@starcoin-main...move-language:move:main](https://github.com/starcoinorg/move/compare/starcoin-main...move-language:move:main)
> 
> 因为starcoinorg/move的starcoin-main分支没有pick这个commit ?[starcoinorg/move@b187724](https://github.com/starcoinorg/move/commit/b18772471c01d5b2c0143bb3078f24327ba63bc1)
> 
> ![image](https://user-images.githubusercontent.com/23182033/182022989-50655664-e04d-4c3f-9e20-cd8e626cc2b7.png)

Can you help to pick up there commits, like https://github.com/starcoinorg/move/commit/b18772471c01d5b2c0143bb3078f24327ba63bc1 and  https://github.com/move-language/move/commit/e0da9976f92b8badca21a222fb582007f9cdaa5f

**Comment by jiangying000** [comment]
> > [starcoinorg/move@starcoin-main...move-language:move:main](https://github.com/starcoinorg/move/compare/starcoin-main...move-language:move:main)
> > 
> > 因为starcoinorg/move的starcoin-main分支没有pick这个commit ?[starcoinorg/move@b187724](https://github.com/starcoinorg/move/commit/b18772471c01d5b2c0143bb3078f24327ba63bc1)
> > 
> > ![image](https://user-images.githubusercontent.com/23182033/182022989-50655664-e04d-4c3f-9e20-cd8e626cc2b7.png)
> 
> 能帮忙把你的一系列 commits，比如 
> https://github.com/starcoinorg/move/commit/b18772471c01d5b2c0143bb3078f24327ba63bc1 and  https://github.com/move-language/move/commit/e0da9976f92b8badca21a222fb582007f9cdaa5f
> 
> pickup 到 starcoinorg/move 的 starcoin-main 分支并且更新 starcoin 的依赖么？
> 
> 

好的
