### ISSUE TITLE
[Bug Report] starcoin --data-dir do not work

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#3595]
# Bug Report

**Starcoin version:**

latest master

**Current behavior:**

```
starcion -n barnard --data-dir $PATH
```

do not change the default data-dir `~/.starcoin/barnard` to $PATH

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

https://github.com/starcoinorg/starcoin/blob/faab0350b136bd0a2ef1b1142688c963e278a078/config/src/lib.rs#L291-L298

**Other information:**

#3570

**Comment by YusongWang** [comment]
working on it
