### ISSUE TITLE
[Bug Report] state.list_resource resource_types filter do not work use short address.

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#3612]
# Bug Report

**Starcoin version:**

latest

**Current behavior:**

```
curl 'http://halley.seed.starcoin.org/' \
  -H 'content-type: application/json' \
  --data-raw '{"jsonrpc":"2.0","method":"state.list_resource","params":["0x4783d08fb16990bd35d83f3e23bf93b8",{"decode":true,"resource_types":["0x1::Account::Balance"]}],"id":0}'

{"jsonrpc":"2.0","result":{"resources":{}},"id":0}


curl 'http://halley.seed.starcoin.org/' \
  -H 'content-type: application/json' \
  --data-raw '{"jsonrpc":"2.0","method":"state.list_resource","params":["0x0000000000000000000000000a550c18",{"decode":true,"resource_types":["0x00000000000000000000000000000001::Account::Balance"]}],"id":0}'


{"jsonrpc":"2.0","result":{"resources":{"0x00000000000000000000000000000001::Account::Balance<0x00000000000000000000000000000001::STC::STC>":{"json":{"token":{"value":159256800000000000}},"raw":"0x00c0104037cb35020000000000000000"}}},"id":0}

```

**Expected behavior:**

"resource_types":["0x1::Account::Balance"] == "resource_types":["0x00000000000000000000000000000001::Account::Balance"]}]

**Steps to reproduce:**

**Related code:**

https://github.com/starcoinorg/starcoin/blob/8aa6bf2e5f150411e3956be50a8bba5bc550cefa/rpc/server/src/module/state_rpc.rs#L279-L287

**Other information:**

**Comment by jolestar** [comment]
@jiangying000 #3586 这个实现好像有点问题

**Comment by YusongWang** [comment]
working on it

**Comment by jiangying000** [comment]
> @jiangying000 #3586 这个实现好像有点问题

当时想的是先实现最严格的匹配，后续根据需求做下扩展就行了

resource_types内部实现稍微改下就可以支持各类级别的筛选，短地址0x1，支持仅地址0x005c80，支持模块0x5588::Abc，支持带泛型0x1::22bc::XXY<A,B>，都是稍微改下都可以了

**Comment by jolestar** [comment]
@YusongWang 你要做的话，和 @jiangying000 沟通一下想法

**Comment by YusongWang** [comment]
@jiangying000  #3615  看下这里。只对address进行了匹配。看了你说的，估计你做的方法应该更普遍合适一些，可以转给你做。

**Comment by jolestar** [comment]
> > @jiangying000 #3586 这个实现好像有点问题
> 
> 当时想的是先实现最严格的Addr::Module::StructTag完全版字符串的匹配，后续根据实际需求做修改
> 
> resource_types内部实现改一下就可以支持各类级别的筛选，短地址0x1，支持仅地址0x005c80，支持模块0x5588::Abc，支持带泛型0x1::22bc::XXY<A,B>，应该都是改下都可以了
> 
> 当时没想到要手打地址的场景😂，以为就是前端调api的时候写死在代码里面的

感觉需要解析一下地址，通过解析后的类型去比较，而不是字符串匹配，可以和 #3614 的方案一起考虑下。
最关键的场景就是不带泛型参数的统配过滤
