### ISSUE TITLE
[Feature Request] Event Filter support filter by TypeTag improvement

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#3614]
# Feature Request

**Describe the Feature Request**

Event Filter 通过类型过滤的时候，如果是带泛型的类型，无法实现根据不带泛型类型的参数过滤

比如: 

```
0x1::NFT::MintEvent<NFTMeta>
```

过滤的时候必须是：

```
0x1::NFT::MintEvent<0xxxxx:MyNFT:MyNFTMeta>
```

而不能直接通过

```
0x1::NFT::MintEvent
```

得到所有的 MintEvent

**Related Code**

https://github.com/starcoinorg/starcoin/blob/737635c9099c1fba7eb5e504b6c0a10c800f7832/types/src/filter.rs#L55-L64

和 #3612 这个问题类似

**Comment by jiangying000** [comment]
这个如何复现？

**Comment by jolestar** [comment]
> 这个如何复现？

```
dev subscribe event --type_tag
```

**Comment by YusongWang** [comment]
这个issue 可以关闭了,老师已经在 #3638  解决了。
