### ISSUE TITLE
[Bug Report] Some test cases failed with the latest master code

### ISSUE THREAD

**Issue by 0xpause** [starcoinorg/starcoin#3654]
# Bug Report

**Starcoin version:**

master latest, commit a991c9b2da402fcd218466def2d562907eca861d

**Current behavior:**

Some test cases failed:

- case1:  thread 'unit_tests::access_path_test::test_access_path' panicked at 'access_path from str should ok: unrecognized token', [vm/types/src/unit_tests/access_path_test.rs:86:73](https://github.com/starcoinorg/starcoin/blob/a991c9b2da402fcd218466def2d562907eca861d/vm/types/src/unit_tests/access_path_test.rs#L86)

- case2:  thread 'unit_tests::access_path_test::test_access_path_str_valid' panicked at 'assertion failed: `(left == right)`
  left: `"0x00000000000000000000000000000001/1/0x00000000000000000000000000000001::Account::Account"`,
 right: `"0x00000000000000000000000000000001/1/0x1::Account::Account"`', [vm/types/src/unit_tests/access_path_test.rs:29:9](https://github.com/starcoinorg/starcoin/blob/a991c9b2da402fcd218466def2d562907eca861d/vm/types/src/unit_tests/access_path_test.rs#L29)

**Expected behavior:**

The unit tests should pass.

**Steps to reproduce:**

- case1: run `cargo test --package starcoin-vm-types --lib -- unit_tests::access_path_test::test_access_path --exact --nocapture --ignored`
- 
- case2: run `cargo test --package starcoin-vm-types --lib -- unit_tests::access_path_test::test_access_path_str_valid --exact --nocapture`

**Related code:**

**Other information:**

Related issues: #3651, #3652

**Comment by 0xpause** [comment]
@jiangying000 @JerryKwan

**Comment by jiangying000** [comment]
> @jiangying000 @JerryKwan

I am trying to temporarily fix them in https://github.com/starcoinorg/starcoin/pull/3655, could be rollback when rolling `short_str` commit back

**Comment by jiangying000** [comment]
This should be fixed
