### ISSUE TITLE
[Feature Request]chain.get_blocks_by_number接口优化

### ISSUE THREAD

**Issue by ssyuan** [starcoinorg/starcoin#3799]
# Feature Request

**Describe the Feature Request**

![image](https://user-images.githubusercontent.com/537535/202596192-34330fbd-ff43-48e7-86c3-65a93bc58369.png)
如上图所示，调用get_blocks_by_number接口获取区块数据，每次传入参数：
第1次： 103，3
第2次：106，3
以此类推
第5次：115，3
理论上应该获取的区块是 [113]，但实际获取的是 [111, 112,113]如红色所框

**Describe Preferred Solution**
期望优化：
1、支持从后往前获取，这样传参数方便些，这样不用每次计算高度；
     这样本地记录的已经获取的offset，直接当参数传递获取，比如第2次调用，那我已经成功获取到103了，那我就直接传104就行
2、对于目前倒序获取，做兼容处理，第5次获取的结果实际几条就返回几条，而不是帮我默认移动offset，这样获取者就不用拿到还需增加判断重复的逻辑

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_ NO

**Comment by WGB5445** [comment]
>期望优化：
1、支持从后往前获取，这样传参数方便些，这样不用每次计算高度；
这样本地记录的已经获取的offset，直接当参数传递获取，比如第2次调用，那我已经成功获取到103了，那我就直接传104就行

这个在接口内增加一个 正/反 的选项，应该可以满足要求，默认与现在相同

>2、对于目前倒序获取，做兼容处理，第5次获取的结果实际几条就返回几条，而不是帮我默认移动offset，这样获取者就不用拿到还需增加判断重复的逻辑

这里的功能有个bug，按照原有逻辑，输入 115，应该返回报错 “result cannot find block by number” ，所以此处功能是否还需要？

如果不需要该功能，当修改该 bug 后，当链的长度为 113 时，输入 114 - 115 都会报错返回 “result cannot find block by number”

**Comment by nkysg** [comment]
> > 期望优化：
> > 1、支持从后往前获取，这样传参数方便些，这样不用每次计算高度；
> > 这样本地记录的已经获取的offset，直接当参数传递获取，比如第2次调用，那我已经成功获取到103了，那我就直接传104就行
> 
> 这个在接口内增加一个 正/反 的选项，应该可以满足要求，默认与现在相同
> 
> > 2、对于目前倒序获取，做兼容处理，第5次获取的结果实际几条就返回几条，而不是帮我默认移动offset，这样获取者就不用拿到还需增加判断重复的逻辑
> 
> 这里的功能有个bug，按照原有逻辑，输入 115，应该返回报错 “result cannot find block by number” ，所以此处功能是否还需要？
> 
> 如果不需要该功能，当修改该 bug 后，当链的长度为 113 时，输入 114 - 115 都会报错返回 “result cannot find block by number”

这里最终结论也帮忙更新下吧

**Comment by WGB5445** [comment]
总结修改：

对该接口增加 "正序获取"的 Option

修改掉之前存在的 Bug（输入 115 返回 111 - 113 ) 改为超过 113 就会报错
