### ISSUE TITLE
[Bug Report] Starcoin node sync failed on ubuntu 22

### ISSUE THREAD

**Issue by sanlee42** [starcoinorg/starcoin#3831]
# Bug Report

**Starcoin version:**

starcoin% version
starcoin 1.12.9 (build:v1.12.9) on ubuntu 22

**Current behavior:**
Sync failed 

ERROR - [sync] collect block error: "Verify block consensus failed: Verify Nonce Error, expect target: 242242864513213797957261474913573028981736369593390301337777372401491903012, got: 399128644261547479880915487342268948000991639220830640541743073
WARN - Failed to process generate block event:block_metadata txn BlockMetadata { id: Some(HashValue(0x7c1742a85fe7e93019bf187ca78eab1118a368ed5a8510775588ada0fdf25638)), parent_hash: HashValue(0x9b15af627a78d9a9494f1aec78a1a6f04febda69ec00a9305ce00b28bb9a8a6e), timestamp: 1673424507734, author: 0x50f9a6640713501dccc83714fbdf651d, author_auth_key: None, uncles: 0, number: 919, chain_id: ChainId { id: 251 }, parent_gas

**Comment by nkysg** [comment]
cryptonight-rs build extension c code use flag("-Ofast"), erase flag("-Ofast") can verify pass

**Comment by nkysg** [comment]
https://github.com/starcoinorg/starcoin/issues/3057 可能一样

**Comment by nkysg** [comment]
测试 nkysg macos barnard main
ubunut18 barnard main
ubuntu22 barnard main
