### ISSUE TITLE
[Bug Report]The commit operation in Flexidag should support reentrance.

### ISSUE THREAD

**Issue by jackzhhuang** [starcoinorg/starcoin#4064]
# Bug Report

In test_with_spawn, it spawns some threads to commit the same block in parallel, causing a problem that the db will return an error   indicating no reentrance support.

And in sync and block connector service, these two thread may commit the block at the same time alike the case above.

There are two ways to fix:

1, Process the error code when committing in parallel.
2, Modify the db write logic to support the reentrance feature.

**Comment by jackzhhuang** [comment]
Let's think about the case:

The miner service create a block 2 with tip 1. The dag store will insert the relation 1-2.

At the same time, the sync process is invoked by the new block notification and sync a block 3 with tip 1 from the other peer. Tha dag store will insert relation 1-3.

Although the probability is low, it is better to fix just in case.

**Comment by nkysg** [comment]
https://github.com/starcoinorg/starcoin/blob/85247e14249b2a79fcef8eb3dcc41f721329f239/flexidag/src/consensusdb/consensus_relations.rs#L152-L178

**Comment by nkysg** [comment]
> Let's think about the case:
> 
> The miner service create a block 2 with tip 1. The dag store will insert the relation 1-2.
> 
> At the same time, the sync process is invoked by the new block notification and sync a block 3 with tip 1 from the other peer. Tha dag store will insert relation 1-3.
> 
> Although the probability is low, it is better to fix just in case.

Could you add this test?

**Comment by jackzhhuang** [comment]
> > Let's think about the case:
> > The miner service create a block 2 with tip 1. The dag store will insert the relation 1-2.
> > At the same time, the sync process is invoked by the new block notification and sync a block 3 with tip 1 from the other peer. Tha dag store will insert relation 1-3.
> > Although the probability is low, it is better to fix just in case.
> 
> Could you add this test?

please check the branch: dag-master-db-reentrance and see the case: test_write_asynchronization.

This case will fail at the last two assertion because the problem metioned above.

**Comment by nkysg** [comment]
> dag

This case is not right.
https://github.com/starcoinorg/starcoin/blob/0c75528b4344900ed81cc34b56e9e92721e55385/flexidag/tests/tests.rs#L159-L205

In your code dag, dag_one, dag_two are three different objects, because DbRelationsStore member has  DagCache, this is different, although dag, dag_one, dag_two reference the same DBstorage , but when they read , they read from cache first. In your test L188, it has set the cache.
https://github.com/starcoinorg/starcoin/blob/0c75528b4344900ed81cc34b56e9e92721e55385/flexidag/src/consensusdb/consensus_relations.rs#L73-L77

https://github.com/starcoinorg/starcoin/blob/0c75528b4344900ed81cc34b56e9e92721e55385/flexidag/src/consensusdb/access.rs#L15-L22

**Comment by jackzhhuang** [comment]
> > dag
> 
> This case is not right.
> 
> https://github.com/starcoinorg/starcoin/blob/0c75528b4344900ed81cc34b56e9e92721e55385/flexidag/tests/tests.rs#L159-L205
> 
> In your code dag, dag_one, dag_two are three different objects, because DbRelationsStore member has DagCache, this is different, although dag, dag_one, dag_two reference the same DBstorage , but when they read , they read from cache first. In your test L188, it has set the cache.
> 
> https://github.com/starcoinorg/starcoin/blob/0c75528b4344900ed81cc34b56e9e92721e55385/flexidag/src/consensusdb/consensus_relations.rs#L73-L77
> 
> https://github.com/starcoinorg/starcoin/blob/0c75528b4344900ed81cc34b56e9e92721e55385/flexidag/src/consensusdb/access.rs#L15-L22
> 
> please check your test and make sure it can pass.

It is ok to clone a dag. It will read from DBStorage if the cache dose not contain the key.

The case will fail at one of the last two assertion because two threads struggle to write the same key. This is the problem we should fix.

**Comment by nkysg** [comment]
Sorry. DagCache is  arc. I don't notice this. You're right.
