### ISSUE TITLE
[compiler-v2] if we need to read old BlockHeader, we need to add auth key back

### ISSUE THREAD

**Issue by nkysg** [starcoinorg/starcoin#4296]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by simonjiao** [comment]
add author_auth_key back for legacy block header #4325
