### ISSUE TITLE
[review] storage review

### ISSUE THREAD

**Issue by ssyuan** [starcoinorg/starcoin#462]
- [ ] common lib and package(storage/src/lib.rs)
- [ ] storage structure（KVStore、InnerStore、InnerStorage、CodecStorage、StorageInstance）(storage/src/storage.rs)
- [ ] db storage （storage/src/db_storage）
- [ ] cache storage （storage/src/cache_storage）
- [ ] write batch（storage/src/batch/mod.rs）
- [ ] macros and service package(storage/src/storage_macros.rs)

**Comment by fikgol** [comment]
#585  Round one finished
