### ISSUE TITLE
[vm]  block transaction execute discard, vmstatus:status STORAGE_ERROR

### ISSUE THREAD

**Issue by ssyuan** [starcoinorg/starcoin#468]
cargo bench --bench bench_chain 
result:
Benchmarking block_try_connect/connect_branch_500: Collecting 10 samples in estimated 575.26 s (55 iterations)thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: block transaction execute discard, vmstatus:status STORAGE_ERROR of type Invariant violation, transaction_id: 22ca2756', benchmarks/src/chain.rs:119:34
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_none_failed
   9: benchmarks::chain::ChainBencher::execute
  10: criterion::Bencher<M>::iter_batched
  11: benchmarks::chain::ChainBencher::bench
  12: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  13: criterion::routine::Routine::sample
  14: criterion::analysis::common
  15: <criterion::benchmark::Benchmark<M> as criterion::benchmark::BenchmarkDefinition<M>>::run
  16: bench_chain::main
  17: std::rt::lang_start::{{closure}}
  18: std::panicking::try::do_call
  19: __rust_maybe_catch_panic
  20: std::rt::lang_start_internal
  21: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic in Arbiter thread.

**Comment by guangyuz** [comment]
问题不再复现。
