### ISSUE TITLE
[review]Chain & Sync

### ISSUE THREAD

**Issue by tiangong3624749** [starcoinorg/starcoin#476]
1. Chain
- [ ] BlockChain
- [ ] ChainService

2. Sync
- [ ] Processor
- [ ] FullSync
- [ ] StateSync

**Comment by lerencao** [comment]
对 chain 的初步review #569

**Comment by lerencao** [comment]
SyncMetadata 暂时还没有理清楚。后续需要配合 sync 模块一起再看看。

**Comment by tiangong3624749** [comment]
SyncMetadata最开始想的是存放原始数据，后面发现很多边界条件也要存储。

**Comment by lerencao** [comment]
这个是第一轮的。可以 close掉了。 sync 代码现在也重构了不少。
