### ISSUE TITLE
run block metadata after txns executed cause block number not increased in contracts

### ISSUE THREAD

**Issue by lerencao** [starcoinorg/starcoin#524]
As discussed.

**Comment by lerencao** [comment]
看起来，要解决这个问题，只需要在初始化是把 hight 设置成1即可。

genesis 后，height 是1。
下一个 block，看到的 block height 就是1。然后 block 末尾的 block meta 交易，将 height +1。
再下一个 block 看到的 height 是2。

**Comment by lerencao** [comment]
cc @jolestar

**Comment by jolestar** [comment]
如果只是 height，这个办法也可以，相当于最后把 hight 增加到下一个块的高度。但有其他一些数据，比如 timestamp， 比如 block 的 HashValue ，难度 等等没法这样处理。 还是得想一个统一的方案来处理这个事情。

1. 方案一，blockmetadta txn 在最开始处理。
2. 如果第一个方案不行，则考虑提供 block_prologue 和 block_epilogue 两个方法处理 blockmetadata.
