### ISSUE TITLE
a discarded txn should not fail the whole block executing

### ISSUE THREAD

**Issue by lerencao** [starcoinorg/starcoin#527]
Currently if a txn is discard, block_executor just return error directly.

Expected handling is:
- the discard txn is removed from tx-pool marked with `invalid` flag.
- block executor continue execute next txn, include it if executed correctly.

**Comment by jolestar** [comment]
正常情况下 discard 状态的的交易理论上不应该包含到区块中，这种交易没法扣 gas 费，包含到区块中会被恶意利用。如果当前区块中包含了 discard 状态，可能是我们的打包程序有问题，或者 vm 的状态处理有问题。

**Comment by lerencao** [comment]
@jolestar 指的是在打包 block template 时的。如果txn  discard， 应该继续打包后面的 txns。

**Comment by jolestar** [comment]
@jolestar create block template 时确实应该如此。
