### ISSUE TITLE
Unify the semantic meaning of txn id, block id, block header id, etc

### ISSUE THREAD

**Issue by lerencao** [starcoinorg/starcoin#559]
目前我们对 id 和 hash 的使用还比较混乱。
举几个我碰到的问题：

1. 在标识 `SignedUserTransaction` 时，我们用它的 crypto_hash。当它被封装成 `Transaction::UserTransaction(SignedUserTransaction)` ，该如何标示它呢？是用 Transaction 的 crypto hash 还是用它里面的 user_txn 的 crypto hash 呢？
因为block 中包含的是 SignedUserTransaction，而在内部，我们存储的时候用的是 Transaction 的 crypto hash。这里很容易出现混乱。

2. 在需要标识一个数据时，该用id 方法还是 crypto hash 方法。
3. 如果一个数据只在内部使用，并不真的落到 DB 中，又该如何标识？

我们现在的数据结构已经比较多了，需要整体的确定一个统一的使用规范。
不然，各个模块使用不同的 id/hash，容易产生比较多的问题，排查起来也麻烦。

cc @jolestar @ssyuan

**Comment by lerencao** [comment]
cc @tiangong3624749

**Comment by jolestar** [comment]
@lerencao 对，这个我写了一个 TODO，但还没想好怎么弄，并且现在每次获取 ID 都要计算一次，也比较浪费。

**Comment by ssyuan** [comment]
transaction的问题，第一步，我们先统一UserTransaction(SignedUserTransaction)的ID用SignedUserTransaction里面的RawUserTransaction的crypto_hash。
