### ISSUE TITLE
node console display does not friendly

### ISSUE THREAD

**Issue by fikgol** [starcoinorg/starcoin#587]
block header in peer info does not define
<img width="1533" alt="Screen Shot 2020-06-01 at 3 01 27 PM" src="https://user-images.githubusercontent.com/2162274/83474432-90e6ae80-a4be-11ea-9634-d07b9d4bef1d.png">

**Comment by jolestar** [comment]
先用了一个临时的方案解决这个问题，长期的方案应该是 #613
