### ISSUE TITLE
[benchmark] bench_sync failed with 'Err' peerId not exist

### ISSUE THREAD

**Issue by guangyuz** [starcoinorg/starcoin#600]
cargo bench --bench bench_sync

Benchmarking full_sync/full_sync_10: Warming up for 3.0000 sthread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: get peer PeerId(PeerId("QmRd4fFbfV9a5dJUAR3FCpY9VyDUER93ytNhXdmdRH5PgE")) not exist.', benchmarks/src/sync.rs:48:13
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_none_failed
   9: <std::future::GenFuture<T> as core::future::future::Future>::poll
  10: tokio::macros::scoped_tls::ScopedKey<T>::set
  11: <std::future::GenFuture<T> as core::future::future::Future>::poll
  12: tokio::macros::scoped_tls::ScopedKey<T>::set
  13: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
  14: tokio::runtime::context::enter
  15: tokio::runtime::handle::Handle::enter
  16: benchmarks::sync::SyncBencher::sync_block
  17: criterion::Bencher<M>::iter_batched
  18: benchmarks::sync::SyncBencher::bench_full_sync
  19: <criterion::routine::Function<M,F,T> as criterion::routine::Routine<M,T>>::warm_up
  20: criterion::routine::Routine::sample
  21: criterion::analysis::common
  22: <criterion::benchmark::Benchmark<M> as criterion::benchmark::BenchmarkDefinition<M>>::run
  23: bench_sync::main
  24: std::rt::lang_start::{{closure}}
  25: std::panicking::try::do_call
  26: __rust_maybe_catch_panic
  27: std::rt::lang_start_internal
  28: main

**Comment by jolestar** [comment]
@guangyuz 这个后来还出现过吗？

**Comment by tiangong3624749** [comment]
”future time out“这个Err应该没有了吧？
