### ISSUE TITLE
Peer Reputation

### ISSUE THREAD

**Issue by tiangong3624749** [starcoinorg/starcoin#608]
1. 通过 peer 的行为记录 peer 的 Reputation，比如返回的结果和请求不匹配，区块校验失败等。
2. 定义网络请求响应速度的 Reputation
3. 是否要关闭 Reputation 太低的 peer ？是否提供永久的 peer 屏蔽机制？

**Comment by jolestar** [comment]
@tiangong3624749 确认下这个 issue 是否还有需要做的工作。
