### ISSUE TITLE
[cmd]Cmd View Object optimize

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#613]
当前 console 显示的结果中的字段是重新定义 View Object 来展示的。
这样有几个缺点：

1. 每次都需要转换，如果忘记转换就会导致 console 的输出很不友好。
2. 修改 Origin Object 的时候可能忘记修改了 View Object。  
3. List View 和 Item View 需要展示的字段可能不一样。
4. 用户无法要求展示完整的字段。

可以尝试通过定义 macro 的方式，自动生成 View Object，并且其中的字段是分展示级别的。

在或者配合 GraphQL 提供一种统一的查询检索方式？

**Comment by jolestar** [comment]
统一使用 JSON Rpc 的 ViewObject

**Comment by yubing744** [comment]
> ViewObject

这个 ViewObject 有相关资料吗？

**Comment by jolestar** [comment]
> > ViewObject
> 
> 这个 ViewObject 有相关资料吗？

比较方便的是看 rust rpc 的代码, 比如

https://github.com/starcoinorg/starcoin/blob/424a830227bcc77c89524b224a2691e6d8caf42b/rpc/api/src/types.rs#L396-L429
