### ISSUE TITLE
settle down what data should be exposed to user in our json rpc.

### ISSUE THREAD

**Issue by lerencao** [starcoinorg/starcoin#639]
”我们需要暴露什么数据“ 这个问题由 #559 延伸出来。
这关系到 json api 接口的设计，以及后面存储该存什么，以及对应hash的存法。
这里总结下，我们可能会暴露的数据结构。

### SignedUserTransaction

用户提交的  user_txn。

包含了：

- RawUserTransaction
- User Signature 相关的字段。

以下用 **user_txn_id** 来标识它。

### Transaction

需要确定的是：

- [ ] 要不要暴露给用户？
- [ ] 如果暴露，怎么定义它的 id ？以下用 txn_id 指代。

### Block

链上存储的 Block 信息。

Block 包含了 

- BlockHeader
- BlockBody。

BlockHeader  的 crypto_hash 用来标识 Block 的 id。

以下用 **block_id** 来标识 BlockHeader 和 Block。

需要确定的是：

- [ ] 暴露给用户的 Block 中 body 该存  SignedUserTransaction 还是 Transaction ？
- 无论是哪种，我们都需要提供 通过 id 去查对应的 txn 数据。

### TransactionInfo

txn 被打包到链上后，执行的结果信息。

包含以下字段：

- txn_id。这里的 txn_id 必须是 Transaction 的 id。
- events。
- others。

需要确定的是：

- [ ] 应该提供什么方法去查询 txn 被打包到链上后，生成的 txn_info？
- 目前可以确定的是，需要提供通过 block_id + index 去查询 txn_info。
- 可以想到的还有：
    - [ ] 通过 version 去查 txn info？前提是：

        当用户通过 block_id+index  查到 txn_info 时，version 需要和 TransacitonInfo 一起返回给用户。

    - [ ] 通过 txn_info_id 直接去查？前提是需要暴露 txn_info_id 给用户。

### BlockInfo

需要确定的是：

-  [ ] BlockInfo 数据结构是否暴露？
- [ ] BlockInfo 中应该包含什么数据？目前有
    - txn_info accumulator 相关的信息。txn version 需要根据这里的信息计算获得。
    - block accumulator  相关的信息。
- [ ] BlockInfo 和 BlockHeader 的定位。两者中包含的字段含义是否适合放在该结构？

**Comment by lerencao** [comment]
cc @jolestar @ssyuan

**Comment by jolestar** [comment]
关于 txn id，我的想法是 Transaction(SignedUserTransaction).id()  == SignedUserTransaction.id() == RawUserTransaction.id() 。 也就是说 txn 的 id 不会因为它被签名了或者封装到 Transaction() 中而改变。

**Comment by jolestar** [comment]
Block 的 Body 中当前存的是 SignedUserTransaction, BlockMetadata Transaction 不在 Block 中，是每次计算的。还有用来升级的 stdlib 的 Transaction，这个还在考虑中。原来也考虑过 Block 中直接打包 Transaction, 但感觉 BlockMetadata 是可以计算出来的，打包进去有点冗余，并且增加了校验的复杂度。这个要再考虑一下。

**Comment by jolestar** [comment]
BlockInfo 的数据需要暴露，BlockInfo 原来的想法是保留 Block 的执行中间结果，比如 accumulator 的 信息，total_difficulty 等。

**Comment by lerencao** [comment]
> 关于 txn id，我的想法是 Transaction(SignedUserTransaction).id() == SignedUserTransaction.id() == RawUserTransaction.id() 。 也就是说 txn 的 id 不会因为它被签名了或者封装到 Transaction() 中而改变。

`Transaction(SignedUserTransaction).id() == SignedUserTransaction.id()` 这个我 ok。
但我不确定 `SignedUserTransaction.id() == RawUserTransaction.id()`把 pubkey 和 signature 排除在外会不会产生其他影响。毕竟我们block 里面存的 UserTransaction。有点违背了 id == hash(data) 的直觉。

**Comment by lerencao** [comment]
> Block 的 Body 中当前存的是 SignedUserTransaction, BlockMetadata Transaction 不在 Block 中，是每次计算的。还有用来升级的 stdlib 的 Transaction，这个还在考虑中。原来也考虑过 Block 中直接打包 Transaction, 但感觉 BlockMetadata 是可以计算出来的，打包进去有点冗余，并且增加了校验的复杂度。这个要再考虑一下。

agree with  it。

block 作为一个整体，同步的时候，应该用原始的 UserTransaction。对外可见也应该是。

**Comment by jolestar** [comment]
> > 关于 txn id，我的想法是 Transaction(SignedUserTransaction).id() == SignedUserTransaction.id() == RawUserTransaction.id() 。 也就是说 txn 的 id 不会因为它被签名了或者封装到 Transaction() 中而改变。
> 
> `Transaction(SignedUserTransaction).id() == SignedUserTransaction.id()` 这个我 ok。
> 但我不确定 `SignedUserTransaction.id() == RawUserTransaction.id()`把 pubkey 和 signature 排除在外会不会产生其他影响。毕竟我们block 里面存的 UserTransaction。有点违背了 id == hash(data) 的直觉。

那或者就叫 SignedUserTransaction.raw_txn_id ，这样就没歧义了。计算 txn 的 hash 不包含 pubkey 以及 signature 也是为了安全，不然会出现同一个交易被多次签名重复广播的问题。有过这样的漏洞。

**Comment by lerencao** [comment]
> > > 关于 txn id，我的想法是 Transaction(SignedUserTransaction).id() == SignedUserTransaction.id() == RawUserTransaction.id() 。 也就是说 txn 的 id 不会因为它被签名了或者封装到 Transaction() 中而改变。
> > 
> > 
> > `Transaction(SignedUserTransaction).id() == SignedUserTransaction.id()` 这个我 ok。
> > 但我不确定 `SignedUserTransaction.id() == RawUserTransaction.id()`把 pubkey 和 signature 排除在外会不会产生其他影响。毕竟我们block 里面存的 UserTransaction。有点违背了 id == hash(data) 的直觉。
> 
> 那或者就叫 SignedUserTransaction.raw_txn_id ，这样就没歧义了。计算 txn 的 hash 不包含 pubkey 以及 signature 也是为了安全，不然会出现同一个交易被多次签名重复广播的问题。有过这样的漏洞。

不清楚你说的这个重复广播。可以详细说明下吗，或者链接啥的。

另外，只用 raw_txn id 可能不可能出现这种情况：

用户（不确定恶意不恶意）在一个长链上签名了一个交易 A，假设pubkey 是P1。链存下来了。用 raw_tx_id 。
假如现在分叉了，用户在分叉的时候提交了一个改key 的交易 Z，把key 变成P2，然后又提交了相同的一个交易A，但是用P2签名，此时节点存下来的 raw_txn_id 的数据就变掉了，因为签名数据不对。

**Comment by jolestar** [comment]
@lerencao https://en.bitcoin.it/wiki/Transaction_malleability 应该是比特币的交易延展性攻击，签名算到 id 里后，修改签名里的一些字节可以导致 id 变化，但签名依然有效。

你后面说的这个情况 sequece_number 检查就过不去吧。

**Comment by jolestar** [comment]
最后决定使用 SignedTransaction hash 作为 txn_id. #559
