### ISSUE TITLE
chain get_txn_by_block and get_txn error

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#745]
chain get_txn_by_block d9e7c19900f6cc23de6f24ed89a26e613ace0524548cbd220dbaadd92f348c23

Failed to parse server response as Vec < TransactionInfo >: invalid type: sequence, expected a borrowed byte array

有时候是这个错误:

2020-06-28T12:07:33.410448+08:00 ERROR - rpc return internal_error for: can't find txn info id list for block 405e2f3a

执行交易后通过 get_txn 执行会报告错误 

```bash
starcoin% wallet execute-builtin --blocking --script empty_script
txn a7988d0a7909aa987a0731ff3947efc358ca625f6a6e5210e1ce28e6da97db0d submitted.
txn mined in block hight: 3, hash: 1bd35d092ab5c52b69de57497c5bdaa1858bb2fe61a4db6303f957940e19f4b2
a7988d0a7909aa987a0731ff3947efc358ca625f6a6e5210e1ce28e6da97db0d
starcoin% chain get_txn a7988d0a7909aa987a0731ff3947efc358ca625f6a6e5210e1ce28e6da97db0d
Server returned rpc error Internal error: Internal error
```

```bash
2020-06-28T12:09:13.631374+08:00 ERROR - rpc return internal_error for: Can not find transaction by hash HashValue(a7988d0a7909aa987a0731ff3947efc358ca625f6a6e5210e1ce28e6da97db0d)
```

**Comment by ssyuan** [comment]
Failed to parse server response as Vec < TransactionInfo >: invalid type: sequence, expected a borrowed byte array 
这个错误还没有完全修复，需要迁移contractEvent
