### ISSUE TITLE
test_notify random fail

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#763]
thread 'service_test::tests::test_notify' panicked at 'explicit panic', <::std::macros::panic macros>:2:4
stack backtrace:
   0:     0x55c081955174 - backtrace::backtrace::libunwind::trace::h5d52ba5f20882f09
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:     0x55c081955174 - backtrace::backtrace::trace_unsynchronized::hceee092869668a74
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:     0x55c081955174 - std::sys_common::backtrace::_print_fmt::ha312c2904605e4d5
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55c081955174 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5b9981092140b727
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55c08197d84c - core::fmt::write::h5f6d7d8de88b4173
                               at src/libcore/fmt/mod.rs:1063
   5:     0x55c080d8b625 - std::io::Write::write_fmt::hfbb72e22b78f9fe3

thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `[47, 115, 116, 97, 114, 99, 111, 105, 110, 47, 99, 111, 110, 115, 101, 110, 115, 117, 115, 47, 49]`,
 right: `[47, 115, 116, 97, 114, 99, 111, 105, 110, 47, 110, 111, 116, 105, 102, 121, 47, 49]`', network-p2p/src/service_test.rs:95:25
stack backtrace:
   0:     0x55c081955174 - backtrace::backtrace::libunwind::trace::h5d52ba5f20882f09
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:     0x55c081955174 - backtrace::backtrace::trace_unsynchronized::hceee092869668a74
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:     0x55c081955174 - std::sys_common::backtrace::_print_fmt::ha312c2904605e4d5
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55c081955174 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5b9981092140b727
                               at src/libstd/sys_common/backtrace.rs:59

**Comment by fikgol** [comment]
Maybe related: https://github.com/paritytech/substrate/pull/6826

**Comment by jolestar** [comment]
可以升级一下试试
