### ISSUE TITLE
[wallet] A rich wallet account implement.

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#878]
1. 可以监听链上的 event，在本地做一些数据的索引，比如用户  accept 了哪些 Token，wallet show 命令展示用户所有的 balance。
2. 封装一些查询用户状态，签名以及发送交易的方法（可以替代 functional_test 中的 Account）。
3. 方便在单元测试中 new 一个新的 wallet account，生成 keypair，发送交易等。

**Comment by lerencao** [comment]
拆分成以下几个任务：
- [ ] 先用新的方案实现之前 wallet service 的功能，完成无缝替换。
- [ ] 实现 event 监听。能够完成 用户 accept token 的 event 监听，并存储到 storage 里。
- [ ] 完成 txn submit。能够连续 submit 多个 txn。
- [ ] 接口抽象。
