### ISSUE TITLE
block timestamp

### ISSUE THREAD

**Issue by tiangong3624749** [starcoinorg/starcoin#939]
1. verify block timestamp;
2. txn timestamp;

**Comment by jolestar** [comment]
这两个 timestamp 都会在 Move prologue 里校验，所以感觉 rust 中不需要再校验了，确认一下 prologue 的逻辑就行。

**Comment by tiangong3624749** [comment]
> 这两个 timestamp 都会在 Move prologue 里校验，所以感觉 rust 中不需要再校验了，确认一下 prologue 的逻辑就行。

推理了一下，block的timestamp
1、如果都写过去时间，会导致后面的Epoch的难度增加，所以没有对整个链来说意义不大；
2、如果填写的是未来时间，Block在Verify的时候，超过本地时间15秒会被丢弃；
3、如果当前节点的系统时间有问题，产生的块会被其他节点丢弃，当前节点抢不到master的head。
所以目前的实现是安全的。
